"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";

type Printer={id:number;name:string;model:string;totalHours:number;maintenanceDueAt:string|null;lastExecutionAt:string|null;maintenanceStatus:string};
type Plan={id:number;printer_id:number;printerName:string;title:string;status:string;effectiveStatus:string;due_at:string|null;due_hours:number|null;items:string;notes:string;totalHours:number};
type RecordRow={id:number;title:string;printerName:string;items:string;cost_cents:number;downtime_minutes:number;operator_email:string;meter_hours:number;completed_at:string};
type Data={canManage:boolean;printers:Printer[];plans:Plan[];records:RecordRow[]};
const labels:Record<string,string>={scheduled:"已计划",due:"即将到期",overdue:"已超时",in_progress:"保养中",completed:"已完成",cancelled:"已取消"};
const list=(value:string)=>{try{return (JSON.parse(value) as string[]).join("、")}catch{return value}};

export default function MaintenanceClient(){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const response=await fetch("/api/maintenance",{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value.error);setData(value)},[]);
  useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
  async function request(method:"POST"|"PATCH",body:unknown){setBusy(true);setError("");try{const response=await fetch("/api/maintenance",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)}),value=await response.json();if(!response.ok)throw new Error(value.error);await load()}catch(e){setError(e instanceof Error?e.message:"操作失败")}finally{setBusy(false)}}
  function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void request("POST",{printerId:Number(form.get("printerId")),title:form.get("title"),dueAt:form.get("dueAt"),dueHours:form.get("dueHours"),items:String(form.get("items")||"").split(/[,，\n]/),notes:form.get("notes")})}
  if(!data)return <main className="maintenance-page"><p>{error||"正在加载维护中心…"}</p></main>;
  return <main className="maintenance-page">
    <header><div><small>FLEET CARE · CLOSED LOOP</small><h1>设备维护中心</h1><p>以日期、累计工时和生产执行记录识别到期风险，形成计划、执行和费用档案。</p></div><a href="/">返回工作台</a></header>
    {error&&<div className="maintenance-error">{error}</div>}
    <section className="maintenance-stats"><article><span>需要处理</span><strong>{data.plans.filter(p=>["due","overdue"].includes(p.effectiveStatus)).length}</strong></article><article><span>保养进行中</span><strong>{data.plans.filter(p=>p.effectiveStatus==="in_progress").length}</strong></article><article><span>设备数量</span><strong>{data.printers.length}</strong></article><article><span>维护总费用</span><strong>RM {(data.records.reduce((n,r)=>n+r.cost_cents,0)/100).toFixed(2)}</strong></article></section>
    <section className="fleet-strip">{data.printers.map(printer=><article key={printer.id} className={printer.maintenanceStatus}><div><b>{printer.name}</b><span>{printer.model}</span></div><strong>{printer.totalHours.toFixed(1)}h</strong><small>保养：{printer.maintenanceDueAt?new Date(printer.maintenanceDueAt).toLocaleDateString():"未设置"} · 最近生产：{printer.lastExecutionAt?new Date(printer.lastExecutionAt).toLocaleDateString():"暂无"}</small></article>)}</section>
    <div className="maintenance-grid">
      {data.canManage&&<form className="maintenance-panel maintenance-form" onSubmit={create}><div><small>NEW PLAN</small><h2>计划保养</h2></div><label>设备<select name="printerId" required><option value="">请选择</option>{data.printers.map(p=><option value={p.id} key={p.id}>{p.name} · {p.totalHours.toFixed(1)}h</option>)}</select></label><label>计划名称<input name="title" required placeholder="例如：喷嘴与导轨周期保养"/></label><div className="form-row"><label>到期日期<input name="dueAt" type="datetime-local"/></label><label>到期工时<input name="dueHours" type="number" min="0" step="0.1"/></label></div><label>保养项目<textarea name="items" required placeholder="清洁喷嘴，润滑导轨，检查皮带（逗号分隔）"/></label><label>备注<textarea name="notes"/></label><button disabled={busy}>建立保养计划</button></form>}
      <section className="maintenance-panel plan-list"><div><small>ACTION QUEUE</small><h2>维护任务</h2></div>{data.plans.length===0?<p className="empty">暂无维护计划</p>:data.plans.map(plan=><article key={plan.id} className={`plan ${plan.effectiveStatus}`}><div className="plan-title"><span className="status">{labels[plan.effectiveStatus]}</span><div><h3>{plan.title}</h3><p>{plan.printerName} · 当前 {Number(plan.totalHours).toFixed(1)}h</p></div></div><p>{list(plan.items)}</p><small>日期：{plan.due_at?new Date(plan.due_at).toLocaleString():"未设置"} · 工时：{plan.due_hours??"未设置"}</small>{data.canManage&&!['completed','cancelled'].includes(plan.effectiveStatus)&&<div className="actions">{plan.effectiveStatus!=="in_progress"&&<button disabled={busy} onClick={()=>request("PATCH",{planId:plan.id,action:"start"})}>开始保养</button>}{plan.effectiveStatus==="in_progress"&&<button disabled={busy} onClick={()=>{const items=prompt("实际完成项目（逗号分隔）",list(plan.items));if(!items)return;const cost=prompt("费用（RM）","0")??"0",downtime=prompt("停机时间（分钟）","0")??"0";void request("PATCH",{planId:plan.id,action:"complete",items:items.split(/[,，]/),costCents:Math.round(Number(cost)*100),downtimeMinutes:Number(downtime)})}}>完成并归档</button>}<button className="quiet" disabled={busy} onClick={()=>request("PATCH",{planId:plan.id,action:"cancel"})}>取消</button></div>}</article>)}</section>
    </div>
    <section className="maintenance-panel records"><div><small>SERVICE HISTORY</small><h2>保养档案</h2></div><div className="record-table"><table><thead><tr><th>完成时间</th><th>设备 / 项目</th><th>表显工时</th><th>费用</th><th>停机</th><th>操作者</th></tr></thead><tbody>{data.records.map(row=><tr key={row.id}><td>{new Date(row.completed_at).toLocaleString()}</td><td><b>{row.printerName} · {row.title}</b><small>{list(row.items)}</small></td><td>{row.meter_hours.toFixed(1)}h</td><td>RM {(row.cost_cents/100).toFixed(2)}</td><td>{row.downtime_minutes} 分钟</td><td>{row.operator_email}</td></tr>)}</tbody></table></div></section>
  </main>
}
