"use client";

import {useCallback,useEffect,useState} from "react";
import styles from "./calibration.module.css";

type Eligible={sessionId:number;filename:string;sessionStatus:string;printerId:number;printerName:string;purposes:string;estimatedGrams:number;spoolId:number;spoolCode:string;material:string;colorName:string};
type Task={id:number;sessionId:number;spoolId:number;status:string;beforeGrossGrams:number|null;afterGrossGrams:number|null;actualConsumedGrams:number|null;notes:string;createdBy:string;startedAt?:string;completedAt?:string;createdAt:string;printerName:string;filename:string;purposes:string;estimatedGrams:number;spoolCode:string;material:string;colorName:string};
type Payload={eligible:Eligible[];tasks:Task[]};
const purpose:Record<string,string>={model:"主体",support:"支撑",support_interface:"支撑界面",purge:"冲刷/屎料",wipe_tower:"擦拭塔",brim:"裙边",calibration:"校准",unknown:"待分类"};
const status:Record<string,string>={planned:"待执行",in_progress:"称重中",completed:"已完成",cancelled:"已取消"};

export default function CalibrationClient({canEdit}:{canEdit:boolean}){
 const[data,setData]=useState<Payload>({eligible:[],tasks:[]}),[selected,setSelected]=useState(""),[weights,setWeights]=useState<Record<number,{before:string;after:string;notes:string}>>({}),[saving,setSaving]=useState(0),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const response=await fetch("/api/calibration",{cache:"no-store"}),body=await response.json() as Payload&{error?:string};if(!response.ok)throw new Error(body.error||"读取校准任务失败");setData(body)},[]);
 useEffect(()=>{void load().catch(error=>setMessage(error.message))},[load]);
 async function act(action:"create"|"start"|"complete"|"cancel",task?:Task){const taskId=task?.id||0,weight=weights[taskId]||{before:"",after:"",notes:""},[sessionId,spoolId]=selected.split(":").map(Number),payload=action==="create"?{action,sessionId,spoolId}:{action,taskId,beforeGrossGrams:Number(weight.before),afterGrossGrams:Number(weight.after),notes:weight.notes};setSaving(taskId||-1);const response=await fetch("/api/calibration",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),body=await response.json() as{error?:string};setMessage(response.ok?action==="complete"?"整卷称重差已按切片用途比例分配，返回结算中心即可按实际总重量结算。":"校准任务已更新。":body.error||"操作失败");setSaving(0);if(response.ok){setSelected("");await load()}}
 function patch(id:number,value:Partial<{before:string;after:string;notes:string}>){setWeights(current=>({...current,[id]:{before:"",after:"",notes:"",...current[id],...value}}))}
 return <main className={styles.page}><header><a href="/settlements">← 返回耗材归集</a><small>FIELD CALIBRATION · SCALE EVIDENCE</small><h1>现场称重校准</h1><p>同一实体卷在打印前、打印后分别称重，重量差作为真实消耗证据。系统不控制打印机，也不会编造设备测量值。</p></header>
  <section className={styles.rules}><b>标准操作</b><span>① 确认实体卷与打印会话一致</span><span>② 打印前称整卷毛重</span><span>③ 打印完成后再次称整卷毛重</span><span>④ 重量差回写结算中心</span></section>
  {message?<div className={styles.message}>{message}<button onClick={()=>setMessage("")}>×</button></div>:null}
  <section className={styles.panel}><div><small>NEW TASK</small><h2>建立校准任务</h2><p>按“打印会话 + 实体卷”称量整卷总消耗，再按切片中的用途比例分配，避免把主体、支撑和冲刷料误算到单一项目。</p></div><div className={styles.create}><select value={selected} onChange={event=>setSelected(event.target.value)}><option value="">选择打印会话和实体卷</option>{data.eligible.map(item=><option key={`${item.sessionId}:${item.spoolId}`} value={`${item.sessionId}:${item.spoolId}`}>{item.printerName} · {item.filename} · {item.purposes.split(",").map(x=>purpose[x]||x).join("+")} · {item.spoolCode} · 预计 {item.estimatedGrams.toFixed(1)}g</option>)}</select>{canEdit?<button disabled={!selected||saving===-1} onClick={()=>void act("create")}>建立任务</button>:null}</div></section>
  <section className={styles.panel}><div><small>WORK QUEUE</small><h2>校准任务</h2><p>打印前后必须使用同一台秤、同一实体卷，并保持附件状态一致。</p></div><div className={styles.tasks}>{data.tasks.map(task=>{const weight=weights[task.id]||{before:"",after:"",notes:""},actual=Number(weight.before)-Number(weight.after);return <article key={task.id}><header><span><b>{task.filename}</b><small>{task.printerName} · {task.material} {task.colorName} · {task.spoolCode}</small></span><em data-status={task.status}>{status[task.status]||task.status}</em></header><div className={styles.facts}><span>用途构成<b>{task.purposes.split(",").map(x=>purpose[x]||x).join(" + ")}</b></span><span>整卷切片预计<b>{task.estimatedGrams.toFixed(1)}g</b></span>{task.actualConsumedGrams!=null?<span>整卷实际消耗<b>{Number(task.actualConsumedGrams).toFixed(1)}g</b></span>:null}</div>{task.status==="in_progress"?<div className={styles.measure}><label>打印前整卷毛重（g）<input type="number" min="0" step="0.1" value={weight.before} onChange={event=>patch(task.id,{before:event.target.value})}/></label><label>打印后整卷毛重（g）<input type="number" min="0" step="0.1" value={weight.after} onChange={event=>patch(task.id,{after:event.target.value})}/></label><label>称重备注<input value={weight.notes} onChange={event=>patch(task.id,{notes:event.target.value})} placeholder="秤编号、附件状态等"/></label><strong>计算消耗：{Number.isFinite(actual)&&actual>0?`${actual.toFixed(1)}g`:"—"}</strong></div>:null}{canEdit?<footer>{task.status==="planned"?<><button onClick={()=>void act("start",task)} disabled={saving===task.id}>开始称重</button><button className={styles.ghost} onClick={()=>void act("cancel",task)}>取消</button></>:null}{task.status==="in_progress"?<><button onClick={()=>void act("complete",task)} disabled={saving===task.id||!(actual>0)}>确认并按比例回写证据</button><button className={styles.ghost} onClick={()=>void act("cancel",task)}>取消</button></>:null}</footer>:null}</article>})}{!data.tasks.length?<p className={styles.empty}>尚未建立现场校准任务。</p>:null}</div></section>
 </main>
}
