CREATE TABLE `external_print_jobs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`printer_id` integer NOT NULL,
	`filename` text DEFAULT '' NOT NULL,
	`item_id` integer,
	`order_id` integer,
	`batch_id` integer,
	`quantity` integer DEFAULT 1 NOT NULL,
	`material` text DEFAULT '' NOT NULL,
	`ams_unit` integer,
	`tray_index` integer,
	`estimated_grams` real DEFAULT 0 NOT NULL,
	`consumed_grams` real DEFAULT 0 NOT NULL,
	`status` text DEFAULT '待认领' NOT NULL,
	`result` text DEFAULT '' NOT NULL,
	`inventory_deducted` integer DEFAULT false NOT NULL,
	`started_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`completed_at` text,
	`claimed_at` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`printer_id`) REFERENCES `printers`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`item_id`) REFERENCES `print_items`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`order_id`) REFERENCES `orders`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`batch_id`) REFERENCES `material_batches`(`id`) ON UPDATE no action ON DELETE no action
);
