"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import styles from "./alerts.module.css";
type Alert={id:number;type:string;severity:string;status:string;title:string;detail:string;resourceType:string;resourceId:string;assignedTo:string|null;signalActive:number;occurrenceCount:number;lastDetectedAt:string;clearedAt:string|null};
type Action={id:number;alertId:number;actorEmail:string;action:string;fromStatus:string;toStatus:string;assignedTo:string|null;note:string;createdAt:string};type Member={email:string;displayName:string;role:string};
type Data={alerts:Alert[];actions:Action[];members:Member[];checkedAt:string};
const labels:Record<string,string>={printer_offline:"设备离线",command_timeout:"命令超时",command_failed:"命令失败",low_stock:"耗材异常",maintenance_due:"维护到期",open:"待处理",acknowledged:"已确认",resolved:"已解决",acknowledge:"确认",assign:"指派",resolve:"解决",reopen:"重开",detected:"检测",cleared:"信号消失"};
const resourceHref=(type:string)=>type==="material_variance"?"/material-variances":type==="print_session"||type==="material_calibration"?"/settlements":type==="printer_feed"?"/inventory":"";
export default function AlertCenter({canManage,canOperate}:{canManage:boolean;canOperate:boolean}){const [data,setData]=useState<Data>({alerts:[],actions:[],members:[],checkedAt:""}),[filter,setFilter]=useState("active"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(0);
  const load=useCallback(async()=>{const response=await fetch("/api/alerts",{cache:"no-store"}),result=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(result.error||"告警读取失败");setData(result)},[]);useEffect(()=>{void load().catch(error=>setNotice(error.message))},[load]);
  const shown=useMemo(()=>data.alerts.filter(item=>filter==="all"||(filter==="active"?item.status!=="resolved":item.status===filter)),[data.alerts,filter]);const active=data.alerts.filter(item=>item.status!=="resolved"),critical=active.filter(item=>item.severity==="critical");
  async function mutate(id:number,action:string,assignedTo?:string){setBusy(id);setNotice("");try{const response=await fetch("/api/alerts",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action,assignedTo})}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"操作失败");await load()}catch(error){setNotice(error instanceof Error?error.message:"操作失败")}finally{setBusy(0)}}
  return <main className={styles.shell}><header><a href="/">← 返回工作台</a><div><small>ALERT OPERATIONS</small><h1>告警中心</h1><p>设备、命令、耗材和维护信号自动归并为可分派、可审计的处理事项。</p></div><button onClick={()=>void load()}>同步当前信号</button></header>
    <section className={styles.kpis}><article><span>未关闭</span><strong>{active.length}</strong></article><article className={critical.length?styles.danger:""}><span>严重告警</span><strong>{critical.length}</strong></article><article><span>已确认</span><strong>{active.filter(x=>x.status==="acknowledged").length}</strong></article><article><span>本次展示</span><strong>{shown.length}</strong></article></section>
    {notice&&<p className={styles.notice} role="status">{notice}</p>}<nav>{[["active","当前告警"],["open","待处理"],["acknowledged","已确认"],["resolved","已解决"],["all","全部"]].map(([key,label])=><button className={filter===key?styles.selected:""} onClick={()=>setFilter(key)} key={key}>{label}</button>)}</nav>
    <section className={styles.layout}><div className={styles.list}>{shown.map(item=><article key={item.id} className={`${styles.card} ${styles[item.severity]}`}><div className={styles.cardhead}><span>{labels[item.type]||item.type}</span><b>{labels[item.status]||item.status}</b></div><h2>{item.title}</h2><p>{item.detail}</p><small>最近检测 {item.lastDetectedAt} · 出现 {item.occurrenceCount} 次 · {item.signalActive?"信号仍存在":"信号已消失"}</small><div className={styles.actions}>{resourceHref(item.resourceType)?<a href={resourceHref(item.resourceType)}>前往处理</a>:null}{item.status==="open"&&canOperate&&<button disabled={busy===item.id} onClick={()=>void mutate(item.id,"acknowledge")}>确认</button>}{item.status!=="resolved"&&canManage&&<button disabled={busy===item.id} onClick={()=>void mutate(item.id,"resolve")}>解决</button>}{item.status==="resolved"&&canOperate&&<button disabled={busy===item.id} onClick={()=>void mutate(item.id,"reopen")}>重开</button>}{canManage&&<select disabled={busy===item.id} value={item.assignedTo||""} onChange={event=>event.target.value&&void mutate(item.id,"assign",event.target.value)}><option value="">指派负责人</option>{data.members.map(member=><option key={member.email} value={member.email}>{member.displayName||member.email}</option>)}</select>}</div></article>)}{!shown.length&&<p className={styles.empty}>当前筛选下没有告警。</p>}</div><aside><h2>最近操作</h2>{data.actions.slice(0,40).map(action=><div key={action.id}><b>{labels[action.action]||action.action}</b><span>告警 #{action.alertId} · {action.actorEmail}</span><small>{action.createdAt}{action.assignedTo?` · 指派 ${action.assignedTo}`:""}</small></div>)}</aside></section>
  </main>}
