export type BulkReceiptRow={rowNumber:number;catalogCode:string;spoolCode:string;lotNo:string;costPerKg:number;netGrams:number;tareGrams:number;locationCode:string;receivedAt:string;note:string;errors:string[]};
const aliases:Record<string,keyof Omit<BulkReceiptRow,"rowNumber"|"errors">>={
 "耗材目录编码":"catalogCode","目录编码":"catalogCode","catalogcode":"catalogCode",
 "实体卷编号":"spoolCode","卷码":"spoolCode","spoolcode":"spoolCode",
 "采购批次":"lotNo","批次号":"lotNo","lotno":"lotNo",
 "采购单价(rm/kg)":"costPerKg","采购单价":"costPerKg","costperkg":"costPerKg",
 "净重(g)":"netGrams","净重":"netGrams","netgrams":"netGrams",
 "空盘重量(g)":"tareGrams","空盘重量":"tareGrams","taregrams":"tareGrams",
 "仓位编码":"locationCode","仓位":"locationCode","locationcode":"locationCode",
 "入库日期":"receivedAt","receivedat":"receivedAt","备注":"note","note":"note",
};
export const bulkReceiptHeaders=["耗材目录编码","实体卷编号","采购批次","采购单价(RM/kg)","净重(g)","空盘重量(g)","仓位编码","入库日期","备注"];
export function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===","&&!quoted){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows}
export function normalizeBulkReceiptRows(matrix:unknown[][],catalogCodes:Set<string>,locationCodes:Set<string>){if(matrix.length<2)return[];const keys=matrix[0].map(value=>aliases[String(value??"").trim().toLowerCase()]||aliases[String(value??"").trim()]||null),seen=new Set<string>();return matrix.slice(1).filter(row=>row.some(value=>String(value??"").trim())).map((values,index)=>{const raw:Record<string,string>={};keys.forEach((key,column)=>{if(key)raw[key]=String(values[column]??"").trim()});const row:BulkReceiptRow={rowNumber:index+2,catalogCode:(raw.catalogCode||"").toUpperCase(),spoolCode:(raw.spoolCode||"").toUpperCase(),lotNo:(raw.lotNo||"").toUpperCase(),costPerKg:Number(raw.costPerKg||0),netGrams:Number(raw.netGrams||0),tareGrams:Number(raw.tareGrams||0),locationCode:(raw.locationCode||"MAIN").toUpperCase(),receivedAt:raw.receivedAt||new Date().toISOString().slice(0,10),note:raw.note||"",errors:[]};if(!row.catalogCode)row.errors.push("缺少耗材目录编码");else if(!catalogCodes.has(row.catalogCode))row.errors.push("耗材目录编码不存在");if(!row.spoolCode)row.errors.push("缺少实体卷编号");if(seen.has(row.spoolCode))row.errors.push("文件内实体卷编号重复");seen.add(row.spoolCode);if(!row.lotNo)row.errors.push("缺少采购批次");if(!Number.isFinite(row.costPerKg)||row.costPerKg<0)row.errors.push("采购单价无效");if(!Number.isFinite(row.netGrams)||row.netGrams<=0)row.errors.push("净重必须大于 0");if(!Number.isFinite(row.tareGrams)||row.tareGrams<0)row.errors.push("空盘重量无效");if(!locationCodes.has(row.locationCode))row.errors.push("仓位编码不存在");if(!/^\d{4}-\d{2}-\d{2}$/.test(row.receivedAt))row.errors.push("入库日期格式应为 YYYY-MM-DD");return row})}
export function receiptTemplate(sample:{catalogCode:string;netGrams:number;tareGrams:number}){const row=[sample.catalogCode,"LT-20260724-0001","PO-20260724",129,Number(sample.netGrams||1000),Number(sample.tareGrams||250),"MAIN",new Date().toISOString().slice(0,10),"采购入库"];const cell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;return "\uFEFF"+[bulkReceiptHeaders,row].map(values=>values.map(cell).join(",")).join("\r\n")}
