import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {materialCostCents,settledGramsForRow,validateSlicePayload} from "../cost-settlement/domain.ts";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
const fingerprint="a".repeat(64),base={protocol:"layertrace.slice-metadata/v1",source:{fileName:"part.3mf",observedAt:"2026-07-21T00:00:00Z"},file:{format:"3mf",fingerprint,byteLength:10,plateCount:1},usage:[{plate:1,filament:0,toolhead:"main",feature:"model",estimatedGrams:100},{plate:1,filament:0,toolhead:"main",feature:"support",estimatedGrams:20}],layers:[{plate:1,layer:0,cumulativeGramsByFeature:{model:10,support:5}},{plate:1,layer:1,cumulativeGramsByFeature:{model:50,support:20}},{plate:1,layer:2,cumulativeGramsByFeature:{model:100,support:20}}]};

test("slice import validator preserves only the v1 financial contract",()=>{const value=validateSlicePayload(base);assert.equal(value.file.fingerprint,fingerprint);assert.equal(value.usage.length,2);assert.throws(()=>validateSlicePayload({...base,protocol:"other"}),/SLICE_PROTOCOL_UNSUPPORTED/);assert.throws(()=>validateSlicePayload({...base,usage:[{...base.usage[0],feature:"invented"}]}),/SLICE_USAGE_ROW_INVALID/)});
test("failed jobs settle each feature at its last confirmed layer instead of progress percent",()=>{const payload=validateSlicePayload(base);assert.equal(settledGramsForRow(payload.usage[0],payload.layers,{1:1},false),50);assert.equal(settledGramsForRow(payload.usage[1],payload.layers,{1:0},false),5);assert.equal(settledGramsForRow(payload.usage[0],payload.layers,{},false),0);assert.equal(settledGramsForRow(payload.usage[0],payload.layers,{},true),100)});
test("material cost converts per-kg cents deterministically",()=>{assert.equal(materialCostCents(250,8000),2000);assert.equal(materialCostCents(-1,8000),0)});
test("settlement API is fingerprint-idempotent, organization scoped and never guesses unbound stock",async()=>{const api=await read("app/api/cost-settlement/route.ts");assert.match(api,/`slice:\$\{payload\.file\.fingerprint\}`/);assert.match(api,/message\.includes\("UNIQUE"\)/);assert.match(api,/repaired:true/);assert.match(api,/organization_id=\?/);assert.match(api,/requireApiAccess\(true,"inventory\.write"\)/);assert.match(api,/if\(!binding\)return fail/);assert.match(api,/pending=!line\.spoolId\|\|source\.feature==="unknown"/);assert.match(api,/outcome!=="completed".*!hasLayer/);assert.doesNotMatch(api,/active.*LIMIT 1[\s\S]{0,120}resolved\.set/)});
test("start reserves without deduction and terminal settlement writes classified immutable consumes",async()=>{const api=await read("app/api/cost-settlement/route.ts");const reserve=api.slice(api.indexOf('action==="reserve"'),api.indexOf('action==="measure"'));assert.doesNotMatch(reserve,/UPDATE material_spools SET remaining_net_grams/);assert.match(api,/settledGramsForRow/);assert.match(api,/movement_type,from_location_id,usage_line_id/);assert.match(api,/'consume'/);assert.match(api,/print-session:\$\{sessionId\}/);assert.match(api,/classified_spool_settlement/)});
test("monitor snapshots cannot erase the reserved fingerprint needed for settlement",async()=>{const api=await read("app/api/cost-settlement/route.ts");assert.match(api,/cost_settlement\.material\.reserved/);assert.match(api,/external_session_key=\?/);assert.match(api,/sliceMetadata=json\(canonical\?\.snapshot\)\.sliceMetadata/)});
test("read API links classified material cost back to print, product and order",async()=>{const api=await read("app/api/cost-settlement/route.ts");assert.match(api,/LEFT JOIN print_jobs/);assert.match(api,/LEFT JOIN orders/);assert.match(api,/LEFT JOIN print_items/);assert.match(api,/unitMaterialCostCents/);for(const purpose of ["model","support","support_interface","purge","wipe_tower","brim","calibration","unknown"])assert.match(await read("cost-settlement/domain.ts"),new RegExp(`"${purpose}"`))});

test("settlement work queue suggests exact same-printer slices but requires confirmation",async()=>{const [api,client,page]=await Promise.all([read("app/api/cost-settlement/route.ts"),read("app/settlements/settlement-client.tsx"),read("app/settlements/page.tsx")]);assert.match(api,/candidates=canonical\.filter\(item=>item\.printerId===Number\(row\.printerId\)\)/);assert.match(api,/baseName\(item\.filename\)===baseName\(row\.filename\)/);assert.match(api,/suggestedFingerprint/);assert.match(api,/unique_exact/);assert.match(client,/文件名只用于推荐，不自动认领/);assert.match(client,/不猜测，等待绑定/);assert.match(client,/确认关联并建立用量预留/);assert.match(page,/warehouse/)});

test("session association scopes jobs to organization and compatible printer",async()=>{const api=await read("app/api/cost-settlement/route.ts");assert.match(api,/SELECT id FROM print_jobs WHERE id=\? AND organization_id=\? AND \(printer_id IS NULL OR printer_id=\?\)/);assert.match(api,/job_id=COALESCE\(\?,job_id\)/);assert.match(api,/feedPositionByFilament/);assert.doesNotMatch(api,/matchState==="unique_exact"[\s\S]{0,80}(UPDATE|INSERT)/)});

test("failed print settlement exposes recoverable layer evidence, scale overrides and variance",async()=>{const [api,client]=await Promise.all([read("app/api/cost-settlement/route.ts"),read("app/settlements/settlement-client.tsx")]);assert.match(api,/reservationsResult/);assert.match(api,/canonicalMetadata/);assert.match(api,/totalLayers/);assert.match(api,/measuredGrams/);assert.match(client,/最后完成层/);assert.match(client,/保存称重/);assert.match(client,/预计 \/ 实际 \/ 偏差/);assert.match(client,/按失败证据结算/);assert.match(client,/请补齐最后完成层/)});

test("calibration suggestions require measured settled samples and never auto-apply",async()=>{const [api,client]=await Promise.all([read("app/api/cost-settlement/route.ts"),read("app/settlements/settlement-client.tsx")]);assert.match(api,/u\.settled_at IS NOT NULL/);assert.match(api,/u\.measured_grams IS NOT NULL/);assert.match(api,/BETWEEN 0\.25 AND 4/);assert.match(api,/sampleCount>=3/);assert.match(api,/sampleCount>=10/);assert.match(client,/少于 3 个样本不生成系数/);assert.match(client,/不会自动修改库存或成本/);assert.match(client,/平均绝对偏差/)});
