import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
test("readiness checks deployment dependencies and operational evidence in parallel",async()=>{const source=await read("operations/readiness.ts");for(const term of ["Promise.all","SELECT 1 AS ok","layertrace_migrations","FILES","organization_members","app_secrets","recovery_backups","recovery_drills","local_gateways"])assert.ok(source.includes(term))});
test("readiness scoring distinguishes blockers from warnings",async()=>{const source=await read("operations/readiness.ts");for(const term of ['item.status==="fail"?18','item.status==="warning"?7','"blocked"','"attention"','"ready"'])assert.ok(source.includes(term))});
test("readiness API requires system management and organization scope",async()=>{const source=await read("app/api/operations/readiness/route.ts");assert.match(source,/system\.manage/);assert.match(source,/user\.organizationId/);assert.match(source,/private, no-store/)});
test("operations page documents read-only boundary and exact remediation routes",async()=>{const page=await read("app/operations/page.tsx"),source=await read("operations/readiness.ts");for(const text of ["不会修改生产数据","CI 负责校验代码","两者不能互相替代","暂不建议上线"])assert.ok(page.includes(text));for(const href of ["/settings","/setup","/recovery","/gateways"])assert.ok(source.includes(`actionHref:"${href}"`))});
test("CI runs migration, lint, node, python and production build gates",async()=>{const workflow=await read(".github/workflows/ci.yml");for(const command of ["npm ci","npm run verify:migrations","npm run lint","npm run test:node","python -m pytest -q","npm run build"])assert.ok(workflow.includes(command));assert.match(workflow,/timeout-minutes/);assert.match(workflow,/cancel-in-progress/)});
test("python tests resolve the local gateway package consistently",async()=>{const config=await read("pytest.ini");assert.match(config,/pythonpath = agent/);assert.ok(config.includes("testpaths = agent/tests"))});
test("pytest does not collect the gateway connection helper as a fixture test",async()=>{const source=await read("agent/manage_local_hub.py");assert.match(source,/test_connection\.__test__ = False/)});
test("migration verifier rejects gaps, duplicates and unloaded runtime migrations",async()=>{const script=await read("scripts/verify-migrations.mjs");for(const text of ["存在重复的迁移编号","缺少迁移","运行时未加载迁移"])assert.ok(script.includes(text))});
