import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {buildProfitReport,formatRm} from "../profit/report.ts";

const settings={electricityRateCentsPerKwh:80,laborRateCentsPerHour:1200,laborMinutesPerJob:30,packagingCentsPerOrder:200,overheadBasisPoints:500};
const fixture={settings,activePrinters:1,revenues:[{organizationId:1,orderId:1,orderNo:"SO-1",customer:"Alpha",status:"完成",quantity:2,unitPriceRm:50},{organizationId:1,orderId:2,orderNo:"SO-2",customer:"Beta",status:"完成",quantity:1,unitPriceRm:10},{organizationId:2,orderId:3,orderNo:"OTHER",customer:"Other",status:"完成",quantity:100,unitPriceRm:999}],jobs:[{organizationId:1,jobId:1,orderId:1,printerId:1,printerName:"A1",status:"completed",quantity:2,estimatedGrams:50,estimatedMinutes:60,startedAt:"2026-07-01T00:00:00Z",completedAt:"2026-07-01T02:00:00Z",hourlyRateRm:2,powerWatts:1000},{organizationId:1,jobId:2,orderId:2,printerId:1,printerName:"A1",status:"completed",quantity:1,estimatedGrams:100,estimatedMinutes:60,startedAt:"2026-07-02T00:00:00Z",completedAt:"2026-07-02T03:00:00Z",hourlyRateRm:2,powerWatts:1000}],materials:[{organizationId:1,orderId:1,jobId:1,grams:100,costPerKgRm:100,kind:"consumption"},{organizationId:1,orderId:2,jobId:2,grams:120,costPerKgRm:100,kind:"consumption"},{organizationId:1,orderId:2,jobId:2,grams:20,costPerKgRm:100,kind:"scrap"}],extras:[]};

test("profit and loss orders use rounded MYR cents",()=>{const report=buildProfitReport(1,fixture);const profit=report.orders.find(row=>row.orderId===1);const loss=report.orders.find(row=>row.orderId===2);assert.equal(formatRm(profit.actualProfit),"RM 75.22");assert.ok(profit.actualProfit.cents>0);assert.ok(loss.actualProfit.cents<0);assert.equal(report.summary.revenue.cents,11000);assert.match(report.summary.actualCost.rm,/^\d+\.\d{2}$/)});
test("zero revenue never divides by zero",()=>{const report=buildProfitReport(1,{...fixture,revenues:[{...fixture.revenues[0],quantity:0,unitPriceRm:0}],jobs:[],materials:[],extras:[]});assert.equal(report.summary.revenue.cents,0);assert.equal(report.summary.marginBasisPoints,0);assert.ok(Number.isFinite(report.summary.actualProfit.cents))});
test("organization boundary excludes foreign revenue and costs",()=>{const report=buildProfitReport(1,fixture);assert.equal(report.orders.some(row=>row.orderNo==="OTHER"),false);assert.equal(report.summary.revenue.cents,11000)});
test("empty organization returns a stable empty report",()=>{const report=buildProfitReport(99,fixture);assert.equal(report.empty,true);assert.deepEqual(report.orders,[]);assert.equal(report.summary.actualProfit.cents,0)});
test("profit API and migration enforce finance and organization scope",async()=>{const api=await readFile(new URL("../app/api/profit/route.ts",import.meta.url),"utf8"),data=await readFile(new URL("../profit/data.ts",import.meta.url),"utf8"),migration=await readFile(new URL("../drizzle/0031_profit_analytics.sql",import.meta.url),"utf8");assert.match(api,/finance\.read/);assert.match(data,/WHERE o\.organization_id=\?/);assert.match(data,/WHERE j\.organization_id=\?/);assert.match(data,/WHERE organization_id=\?/);assert.match(migration,/amount_cents/);assert.match(migration,/profit_cost_entries_org_date_idx/)});
