import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {checksumBackup,containsSensitiveKeys,sanitizeBackupValue,serializeBackup,validateBackup} from "../recovery/backup.ts";
const sample={format:"layertrace-org-backup",schemaVersion:1,organizationId:7,createdAt:"2026-07-21T00:00:00.000Z",tables:{organization_members:[{id:1,email:"owner@example.com",password_hash:"nope",tokenHash:"nope",profile:{access_code:"nope",name:"Owner"}}]}};
test("backup recursively excludes sensitive credential fields",()=>{const clean=sanitizeBackupValue(sample);assert.equal(containsSensitiveKeys(clean),false);const text=serializeBackup(clean);assert.doesNotMatch(text,/password_hash|tokenHash|access_code|nope/);assert.match(text,/owner@example\.com/)});
test("backup checksum is deterministic and tampering is rejected",async()=>{const clean=sanitizeBackupValue(sample);const first=await checksumBackup(clean),second=await checksumBackup(JSON.parse(JSON.stringify(clean)));assert.equal(first,second);assert.match(first,/^[a-f0-9]{64}$/);await assert.rejects(()=>validateBackup({...clean,createdAt:"tampered"},first,7),/校验和/)});
test("backup from another organization is rejected before drill",async()=>{const clean=sanitizeBackupValue(sample),checksum=await checksumBackup(clean);await assert.rejects(()=>validateBackup(clean,checksum,8),/不属于当前组织/)});
test("recovery API is system-managed, scoped and never writes production tables",async()=>{const api=await readFile(new URL("../app/api/recovery/route.ts",import.meta.url),"utf8"),migration=await readFile(new URL("../drizzle/0037_disaster_recovery.sql",import.meta.url),"utf8");assert.match(api,/system\.manage/);assert.ok((api.match(/organization_id=\?/g)??[]).length>=5);assert.match(api,/productionWrites:0/);assert.doesNotMatch(api,/UPDATE (orders|print_jobs|printers|material_batches)|DELETE FROM (orders|print_jobs|printers|material_batches)/);assert.match(migration,/recovery_approvals_drill_unique/)});
