import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("all D1 migrations run in order during application startup",async()=>{const schema=await read("db/ensure-schema.ts");const layout=await read("app/layout.tsx");assert.match(schema,/migration0000/);assert.match(schema,/migration0019/);assert.match(schema,/migration0020/);assert.match(schema,/migration0021/);assert.match(schema,/migration0022/);assert.match(schema,/layertrace_migrations/);assert.match(schema,/statement-breakpoint/);assert.match(layout,/await ensureDatabaseSchema\(\)/);});
test("gateway foundation shares contracts and persists durable integration state",async()=>{const contracts=await read("shared/contracts/index.ts");const printer=await read("shared/contracts/printer.ts");const commands=await read("shared/contracts/commands.ts");const gateway=await read("shared/contracts/gateway.ts");const preflight=await read("shared/contracts/preflight.ts");const migration=await read("drizzle/0021_gateway_foundation.sql");const schema=await read("db/schema.ts");assert.match(contracts,/\.\/printer/);assert.match(printer,/PrinterCapabilities/);assert.match(printer,/PrinterStatus/);assert.match(commands,/idempotencyKey/);assert.match(gateway,/GatewayHeartbeat/);assert.match(preflight,/dispatchAllowed/);for(const table of ["local_gateways","gateway_tokens","printer_bindings","printer_events","background_jobs"]){assert.match(migration,new RegExp(`CREATE TABLE .${table}.`));assert.match(schema,new RegExp(`sqliteTable\\("${table}"`));}assert.doesNotMatch(migration,/CREATE TABLE `audit_logs`/);assert.doesNotMatch(migration,/CREATE TABLE `printer_commands`/);assert.doesNotMatch(migration,/CREATE TABLE `print_job_events`/);assert.match(migration,/token_hash/);assert.doesNotMatch(migration,/access_code|token_plaintext/i);});
test("print jobs link and validate printer, item, order and file records",async()=>{const schema=await read("db/schema.ts");const workspace=await read("app/api/workspace/route.ts");const page=await read("app/page.tsx");assert.match(schema,/printerId: integer\("printer_id"\)/);assert.match(schema,/fileId: integer\("file_id"\)/);assert.match(schema,/expectedCompleteAt: text\("expected_complete_at"\)/);assert.match(workspace,/所选打印机不存在或已停用/);assert.match(workspace,/所选物品不属于该订单/);assert.match(workspace,/所选文件不属于该打印物品/);assert.match(workspace,/allowedKinds/);assert.match(workspace,/plannedStartAt/);assert.match(workspace,/printerName: printer.name/);assert.match(page,/select name="printerId" required/);assert.match(page,/select name="fileId"/);assert.match(page,/物料可用性/);});
test("secondary pages use the same local administrator session",async()=>{const fleet=await read("app/fleet/page.tsx");const team=await read("app/team/page.tsx");assert.match(fleet,/getAccessContext/);assert.match(team,/getAccessContext/);assert.doesNotMatch(fleet,/requireChatGPTUser/);});

test("inventory bootstrap creates base tables before dependent indexes",async()=>{const api=await read("app/api/inventory/route.ts");const table=api.indexOf("CREATE TABLE IF NOT EXISTS inventory_transactions");const index=api.indexOf("CREATE INDEX IF NOT EXISTS inventory_transactions_batch_created_idx");assert.ok(table>=0);assert.ok(index>table);assert.match(api,/CREATE TABLE IF NOT EXISTS material_batches/);assert.match(api,/CREATE TABLE IF NOT EXISTS printers/);});

test("all browser business APIs enforce authenticated access",async()=>{for(const path of ["app/api/workspace/route.ts","app/api/details/route.ts","app/api/files/route.ts","app/api/printers/route.ts","app/api/spools/route.ts","app/api/analytics/route.ts","app/api/system/route.ts","app/api/external-jobs/route.ts"]){const source=await read(path);assert.match(source,/requireApiAccess\(/,path);}});
test("agent endpoints authenticate bearer tokens and never expose connector hashes in backup",async()=>{const agent=await read("app/api/agent/route.ts");const system=await read("app/api/system/route.ts");assert.match(agent,/authorization/i);assert.match(agent,/connectorTokenHash/);assert.doesNotMatch(system,/SELECT \* FROM printers/);});
test("role permissions and employee administration are enforced server-side",async()=>{const access=await read("app/access-control.ts");const team=await read("app/api/team/route.ts");assert.match(access,/team\.manage/);assert.match(access,/status='active'/);assert.match(team,/can\([^,]+,"team\.manage"\)/);assert.match(team,/organization_id=\?/);});
test("first-run admin setup is single-use and stores only a password hash",async()=>{const auth=await read("app/session-auth.ts");const setup=await read("app/api/setup/route.ts");assert.match(auth,/INSERT OR IGNORE INTO auth_setup\(id,owner_email\) VALUES\(1,\?\)/);assert.match(auth,/passwordHash = await hashPassword\(password\)/);assert.match(auth,/"owner", "active"/);assert.match(setup,/password\.length < 10/);assert.doesNotMatch(setup,/ADMIN_PASSWORD/);});
test("Bambu connector keeps printer credentials local and authenticates cloud reports",async()=>{const agent=await read("agent/layertrace_agent.py");const api=await read("app/api/agent/route.ts");assert.match(agent,/BAMBU_ACCESS_CODE/);assert.match(agent,/device\/\{self\.serial\}\/report/);assert.match(agent,/BambuMqtt/);assert.doesNotMatch(api,/BAMBU_ACCESS_CODE|accessCode/);assert.match(api,/authenticate\(request\)/);});
test("Local Hub supports discovery, camera gateway and material usage records",async()=>{const agent=await read("agent/layertrace_agent.py");const compose=await read("local-hub/docker-compose.yml");const api=await read("app/api/agent/route.ts");assert.match(agent,/urn:bambulab-com:device:3dprinter:1/);assert.match(agent,/estimate_3mf_grams/);assert.match(compose,/camera-gateway/);assert.match(api,/bambuMaterialUsage/);});
test("product costing and material reservations are calculated server-side",async()=>{const workspace=await read("app/api/workspace/route.ts");assert.match(workspace,/estimatedUnitCost/);assert.match(workspace,/actualUnitCost/);assert.match(workspace,/reservedGrams/);assert.match(workspace,/可用量不足/);});
test("Bambu Studio external jobs can be claimed and settled into inventory",async()=>{const agent=await read("agent/layertrace_agent.py");const api=await read("app/api/external-jobs/route.ts");assert.match(agent,/external/);assert.match(api,/external_print_jobs/);assert.match(api,/inventory_transactions/);});
test("inventory control keeps an immutable gram ledger with stocktakes and document metadata",async()=>{const api=await read("app/api/inventory/route.ts");const page=await read("app/page.tsx");const center=await read("app/inventory-center.tsx");assert.match(api,/material_inventory_meta/);assert.match(api,/inventory_transaction_meta/);assert.match(api,/inventory_stocktakes/);assert.match(api,/inventory_printer_allocations/);assert.match(api,/inventory_in_transit/);assert.match(api,/transferToPrinter/);assert.match(api,/bulkImport/);assert.match(api,/一次请导入 1 至 500 行/);assert.match(api,/usage30Days/);assert.match(api,/库存不足/);assert.match(api,/requireApiAccess\(true\)/);assert.match(page,/InventoryCenter/);assert.match(center,/库存管理/);assert.match(center,/正在使用中/);assert.match(center,/出库到打印机/);assert.match(center,/库存盘点/);assert.match(center,/批量导入/);assert.match(center,/下载 CSV 模板/);});

test("model library keeps large files in R2 and validates organization ownership",async()=>{const migration=await read("drizzle/0022_model_asset_library.sql");const api=await read("app/api/models/route.ts");const page=await read("app/models/model-library-client.tsx");assert.match(migration,/CREATE TABLE `model_assets`/);assert.match(migration,/CREATE TABLE `model_files`/);assert.match(migration,/UNIQUE\(`organization_id`,`sha256`\)/);assert.match(api,/requireApiAccess\(true\)/);assert.match(api,/context\.organizationId/);assert.match(api,/getFilesBucket\(\)\.put/);assert.match(api,/crypto\.subtle\.digest/);assert.match(api,/200\*1024\*1024/);assert.match(api,/allowedExtensions/);assert.match(api,/相同文件已在模型库中/);assert.match(page,/原始模型/);assert.match(page,/切片工程/);assert.match(page,/生产文件/);assert.match(page,/来源链接/);assert.match(page,/许可证/);});
