import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("all browser business APIs enforce authenticated access",async()=>{for(const path of ["app/api/workspace/route.ts","app/api/details/route.ts","app/api/files/route.ts","app/api/printers/route.ts","app/api/spools/route.ts","app/api/analytics/route.ts","app/api/system/route.ts","app/api/external-jobs/route.ts"]){const source=await read(path);assert.match(source,/requireApiAccess\(/,path);}});
test("agent endpoints authenticate bearer tokens and never expose connector hashes in backup",async()=>{const agent=await read("app/api/agent/route.ts");const system=await read("app/api/system/route.ts");assert.match(agent,/authorization/i);assert.match(agent,/connectorTokenHash/);assert.doesNotMatch(system,/SELECT \* FROM printers/);});
test("role permissions and employee administration are enforced server-side",async()=>{const access=await read("app/access-control.ts");const team=await read("app/api/team/route.ts");assert.match(access,/team\.manage/);assert.match(access,/status='active'/);assert.match(team,/can\([^,]+,"team\.manage"\)/);assert.match(team,/organization_id=\?/);});
test("Bambu connector keeps printer credentials local and authenticates cloud reports",async()=>{const agent=await read("agent/layertrace_agent.py");const api=await read("app/api/agent/route.ts");assert.match(agent,/BAMBU_ACCESS_CODE/);assert.match(agent,/device\/\{self\.serial\}\/report/);assert.match(agent,/BambuMqtt/);assert.doesNotMatch(api,/BAMBU_ACCESS_CODE|accessCode/);assert.match(api,/authenticate\(request\)/);});
test("Local Hub supports discovery, camera gateway and material usage records",async()=>{const agent=await read("agent/layertrace_agent.py");const compose=await read("local-hub/docker-compose.yml");const api=await read("app/api/agent/route.ts");assert.match(agent,/urn:bambulab-com:device:3dprinter:1/);assert.match(agent,/estimate_3mf_grams/);assert.match(compose,/camera-gateway/);assert.match(api,/bambuMaterialUsage/);});
test("product costing and material reservations are calculated server-side",async()=>{const workspace=await read("app/api/workspace/route.ts");assert.match(workspace,/estimatedUnitCost/);assert.match(workspace,/actualUnitCost/);assert.match(workspace,/reservedGrams/);assert.match(workspace,/可用量不足/);});
test("Bambu Studio external jobs can be claimed and settled into inventory",async()=>{const agent=await read("agent/layertrace_agent.py");const api=await read("app/api/external-jobs/route.ts");assert.match(agent,/external/);assert.match(api,/external_print_jobs/);assert.match(api,/inventory_transactions/);});
test("inventory control keeps an immutable gram ledger with stocktakes and document metadata",async()=>{const api=await read("app/api/inventory/route.ts");const page=await read("app/page.tsx");const center=await read("app/inventory-center.tsx");assert.match(api,/material_inventory_meta/);assert.match(api,/inventory_transaction_meta/);assert.match(api,/inventory_stocktakes/);assert.match(api,/inventory_printer_allocations/);assert.match(api,/inventory_in_transit/);assert.match(api,/transferToPrinter/);assert.match(api,/bulkImport/);assert.match(api,/一次请导入 1 至 500 行/);assert.match(api,/usage30Days/);assert.match(api,/库存不足/);assert.match(api,/requireApiAccess\(true\)/);assert.match(page,/InventoryCenter/);assert.match(center,/库存管理/);assert.match(center,/正在使用中/);assert.match(center,/出库到打印机/);assert.match(center,/库存盘点/);assert.match(center,/批量导入/);assert.match(center,/下载 CSV 模板/);});
