import {getAccessContext,recordAudit} from "../../access-control";
import {requireApiAccess} from "../../api-auth";
import {getD1,getFilesBucket} from "../../../db";

const allowedExtensions=new Set(["stl","3mf","step","stp","obj","gcode","gco"]),allowedLayers=new Set(["original","project","production"]),maxBytes=200*1024*1024;
type FileRow={id:number;asset_id:number;name:string;category:string;description:string;asset_layer:string;format:string;filename:string;size_bytes:number;version:string;source_platform:string;source_url:string;source_author:string;license_name:string;sha256:string;created_at:string;tags:string};
const clean=(value:FormDataEntryValue|null,length=200)=>String(value??"").trim().slice(0,length);
const extensionOf=(filename:string)=>filename.split(".").pop()?.toLowerCase()??"";
const contentTypeFor=(extension:string)=>({"3mf":"model/3mf",stl:"model/stl",obj:"model/obj",step:"model/step",stp:"model/step",gcode:"text/x.gcode",gco:"text/x.gcode"}[extension]||"application/octet-stream");
async function sha256(bytes:ArrayBuffer){const digest=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join("")}

export async function GET(request:Request){
  const denied=await requireApiAccess();if(denied)return denied;const context=await getAccessContext();if(!context)return Response.json({error:"请先登录"},{status:401});
  try{const url=new URL(request.url),downloadId=Number(url.searchParams.get("download")),d1=getD1();
    if(downloadId){const file=await d1.prepare("SELECT object_key,filename,content_type,size_bytes FROM model_files WHERE id=? AND organization_id=?").bind(downloadId,context.organizationId).first<{object_key:string;filename:string;content_type:string;size_bytes:number}>();if(!file)return Response.json({error:"文件不存在"},{status:404});const object=await getFilesBucket().get(file.object_key);if(!object)return Response.json({error:"文件内容不存在"},{status:404});return new Response(object.body,{headers:{"Content-Type":file.content_type,"Content-Length":String(file.size_bytes),"Content-Disposition":`attachment; filename*=UTF-8''${encodeURIComponent(file.filename)}`}})}
    const query=(url.searchParams.get("q")??"").trim().slice(0,100),category=(url.searchParams.get("category")??"").trim().slice(0,60),layer=(url.searchParams.get("layer")??"").trim(),tag=(url.searchParams.get("tag")??"").trim().slice(0,60);const params:Array<string|number>=[context.organizationId],filters=["a.organization_id=?","a.status='active'"];
    if(query){filters.push("(a.name LIKE ? OR f.filename LIKE ? OR a.description LIKE ?)");params.push(`%${query}%`,`%${query}%`,`%${query}%`)}if(category){filters.push("a.category=?");params.push(category)}if(layer&&allowedLayers.has(layer)){filters.push("f.asset_layer=?");params.push(layer)}if(tag){filters.push("EXISTS(SELECT 1 FROM model_tag_links x JOIN model_tags mt ON mt.id=x.tag_id WHERE x.asset_id=a.id AND mt.name=?)");params.push(tag)}
    const result=await d1.prepare(`SELECT f.id,f.asset_id,a.name,a.category,a.description,f.asset_layer,f.format,f.filename,f.size_bytes,f.version,f.source_platform,f.source_url,f.source_author,f.license_name,f.sha256,f.created_at,COALESCE(GROUP_CONCAT(DISTINCT t.name),'') tags FROM model_files f JOIN model_assets a ON a.id=f.asset_id LEFT JOIN model_tag_links l ON l.asset_id=a.id LEFT JOIN model_tags t ON t.id=l.tag_id WHERE ${filters.join(" AND ")} GROUP BY f.id ORDER BY f.created_at DESC LIMIT 250`).bind(...params).all<FileRow>();return Response.json({files:result.results??[]});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"读取模型库失败"},{status:500})}
}

export async function POST(request:Request){
  const denied=await requireApiAccess(true);if(denied)return denied;const context=await getAccessContext();if(!context)return Response.json({error:"请先登录"},{status:401});
  try{const form=await request.formData(),upload=form.get("file");if(!(upload instanceof File))return Response.json({error:"请选择模型文件"},{status:400});const extension=extensionOf(upload.name);if(!allowedExtensions.has(extension))return Response.json({error:"仅支持 STL、3MF、STEP、OBJ 和 G-code 文件"},{status:400});if(upload.size<=0||upload.size>maxBytes)return Response.json({error:"文件必须大于 0 且不能超过 200MB"},{status:400});
    const layer=clean(form.get("layer"),20)||(extension==="gcode"||extension==="gco"?"production":extension==="3mf"?"project":"original");if(!allowedLayers.has(layer))return Response.json({error:"资产层级无效"},{status:400});if(layer==="production"&&!["3mf","gcode","gco"].includes(extension))return Response.json({error:"生产文件仅支持已切片 3MF 或 G-code"},{status:400});const sourceUrl=clean(form.get("sourceUrl"),1000);if(sourceUrl&&!/^https?:\/\//i.test(sourceUrl))return Response.json({error:"来源链接必须以 http:// 或 https:// 开头"},{status:400});
    const bytes=await upload.arrayBuffer(),hash=await sha256(bytes),d1=getD1();const duplicate=await d1.prepare("SELECT id,asset_id,filename FROM model_files WHERE organization_id=? AND sha256=?").bind(context.organizationId,hash).first<{id:number;asset_id:number;filename:string}>();if(duplicate)return Response.json({duplicate:true,file:duplicate,message:"相同文件已在模型库中，无需重复上传"});
    const safeName=upload.name.replace(/[^a-zA-Z0-9._\-\u4e00-\u9fa5]/g,"_"),objectKey=`models/${context.organizationId}/${hash.slice(0,2)}/${hash}-${safeName}`;await getFilesBucket().put(objectKey,bytes,{httpMetadata:{contentType:upload.type||contentTypeFor(extension)},customMetadata:{originalName:upload.name,sha256:hash}});
    try{const name=clean(form.get("name"),160)||upload.name.replace(/\.[^.]+$/,"");const asset=await d1.prepare("INSERT INTO model_assets(organization_id,name,category,description,created_by) VALUES(?,?,?,?,?) RETURNING id").bind(context.organizationId,name,clean(form.get("category"),60)||"未分类",clean(form.get("description"),1200),context.email).first<{id:number}>();if(!asset)throw new Error("无法创建模型资产");const file=await d1.prepare("INSERT INTO model_files(organization_id,asset_id,asset_layer,format,filename,object_key,sha256,size_bytes,content_type,version,source_platform,source_url,source_author,license_name) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id").bind(context.organizationId,asset.id,layer,extension==="gco"?"gcode":extension,upload.name,objectKey,hash,upload.size,upload.type||contentTypeFor(extension),clean(form.get("version"),30)||"v1",clean(form.get("sourcePlatform"),60)||"本地上传",sourceUrl,clean(form.get("sourceAuthor"),120),clean(form.get("license"),120)).first<{id:number}>();const tags=[...new Set(clean(form.get("tags"),500).split(/[,，]/).map(item=>item.trim().slice(0,40)).filter(Boolean))].slice(0,12);for(const tag of tags){await d1.prepare("INSERT OR IGNORE INTO model_tags(organization_id,name) VALUES(?,?)").bind(context.organizationId,tag).run();await d1.prepare("INSERT OR IGNORE INTO model_tag_links(asset_id,tag_id) SELECT ?,id FROM model_tags WHERE organization_id=? AND name=?").bind(asset.id,context.organizationId,tag).run()}await recordAudit(context,"model.upload","model_asset",String(asset.id),{filename:upload.name,sha256:hash,layer,sizeBytes:upload.size});return Response.json({assetId:asset.id,fileId:file?.id,sha256:hash},{status:201})}catch(error){await getFilesBucket().delete(objectKey);throw error}
  }catch(error){return Response.json({error:error instanceof Error?error.message:"上传模型失败"},{status:500})}
}
