import { desc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { gatewayDiscoveries, gatewayTokens, localGateways, printerBindings, printers } from "../../../db/schema";
import { can, getAccessContext, recordAudit } from "../../access-control";
import { assessGatewayHealth } from "../../../lib/gateway-health";

async function digest(value:string){const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(hash),byte=>byte.toString(16).padStart(2,"0")).join("")}
async function context(write=false){const user=await getAccessContext();if(!user)return {response:Response.json({error:"请先登录"},{status:401})};if(write&&!can(user,"printers.control"))return {response:Response.json({error:"没有设备管理权限"},{status:403})};return {user}}

export async function GET(){const auth=await context();if("response" in auth)return auth.response;const db=getDb();const gateways=await db.select().from(localGateways).where(eq(localGateways.organizationId,auth.user.organizationId)).orderBy(desc(localGateways.createdAt));const ids=new Set(gateways.map(item=>item.id));const discoveries=(await db.select().from(gatewayDiscoveries)).filter(item=>ids.has(item.gatewayId));const bindings=(await db.select().from(printerBindings).where(eq(printerBindings.organizationId,auth.user.organizationId)));return Response.json({gateways:gateways.map(gateway=>{const gatewayDiscoveries=discoveries.filter(item=>item.gatewayId===gateway.id),gatewayBindings=bindings.filter(item=>item.gatewayId===gateway.id);return {...gateway,discoveries:gatewayDiscoveries,bindings:gatewayBindings,health:assessGatewayHealth({lastSeenAt:gateway.lastSeenAt,discoveries:gatewayDiscoveries,bindings:gatewayBindings})}})})}

export async function POST(request:Request){const auth=await context(true);if("response" in auth)return auth.response;const body=await request.json() as {name?:string;gatewayId?:string;version?:string;platform?:string};if(!body.name?.trim())return Response.json({error:"请输入网关名称"},{status:400});const gatewayId=(body.gatewayId||crypto.randomUUID()).trim();const token=`ltgw_${crypto.randomUUID().replaceAll("-","")}_${crypto.randomUUID().replaceAll("-","")}`;const db=getDb();try{const [gateway]=await db.insert(localGateways).values({organizationId:auth.user.organizationId,gatewayId,name:body.name.trim(),version:String(body.version||""),platform:String(body.platform||"")}).returning();await db.insert(gatewayTokens).values({gatewayId:gateway.id,tokenHash:await digest(token),label:"initial"});await recordAudit(auth.user,"gateway.register","gateway",String(gateway.id),{gatewayId});return Response.json({gateway,token},{status:201})}catch{return Response.json({error:"网关标识已存在"},{status:409})}}

export async function PATCH(request:Request){const auth=await context(true);if("response" in auth)return auth.response;const body=await request.json() as {action?:string;gatewayId?:number;discoveryId?:number;printerName?:string};const db=getDb();if(body.action!=="bind"||!body.gatewayId||!body.discoveryId)return Response.json({error:"不支持的操作"},{status:400});const [gateway]=await db.select().from(localGateways).where(eq(localGateways.id,body.gatewayId)).limit(1);const [device]=await db.select().from(gatewayDiscoveries).where(eq(gatewayDiscoveries.id,body.discoveryId)).limit(1);if(!gateway||gateway.organizationId!==auth.user.organizationId||!device||device.gatewayId!==gateway.id)return Response.json({error:"设备不存在"},{status:404});const existing=await db.select().from(printerBindings).where(eq(printerBindings.deviceSerial,device.deviceSerial)).limit(1);if(existing.length)return Response.json({error:"该序列号已绑定"},{status:409});const [printer]=await db.insert(printers).values({name:(body.printerName||device.deviceName).trim(),model:device.deviceModel,connectorType:"bambu_lan",connectionState:"等待本地凭据确认"}).returning();const [binding]=await db.insert(printerBindings).values({organizationId:auth.user.organizationId,gatewayId:gateway.id,printerId:printer.id,deviceSerial:device.deviceSerial,deviceModel:device.deviceModel,status:"pending_local_credential"}).returning();await recordAudit(auth.user,"printer.bind.requested","printer",String(printer.id),{gatewayId:gateway.id,deviceModel:device.deviceModel});return Response.json({binding,credentialAction:{deviceId:device.deviceId,required:true,message:"请在本地网关安全输入 LAN Access Code"}})}
