"use client";
import {useCallback,useEffect,useState} from "react";
import styles from "./material-master.module.css";
type Item={id:number;catalogCode:string;brand:string;series:string;material:string;colorName:string;colorNameEn:string;colorCode:string;colorHex:string;sourceType:string;sourceUrl:string;sourceCheckedAt:string|null;officialVerified:number;amsCompatibility:string};
type Alias={id:number;catalogItemId:number;aliasType:string;aliasValue:string;source:string};type Starter={code:string;name:string;nameZh:string;hex:string};type Data={catalog:Item[];aliases:Alias[];starter:Starter[];source:{url:string;checkedAt:string}};
const aliasNames:Record<string,string>={material:"材质别名",rfid_material:"RFID材质值",color_name:"颜色名称",color_code:"官方色号",color_hex:"HEX色值"};
export default function MaterialMasterClient({canEdit}:{canEdit:boolean}){const[data,setData]=useState<Data>({catalog:[],aliases:[],starter:[],source:{url:"",checkedAt:""}}),[selected,setSelected]=useState(0),[type,setType]=useState("material"),[value,setValue]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const load=useCallback(async()=>{const response=await fetch("/api/material-master",{cache:"no-store"}),body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error||"读取主数据失败");setData(body)},[]);useEffect(()=>{void load().catch(error=>setMessage(error.message))},[load]);async function mutate(body:Record<string,unknown>){setBusy(true);const response=await fetch("/api/material-master",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json() as{error?:string;imported?:number};setMessage(response.ok?result.imported?`已导入或更新 ${result.imported} 条官方基础色。`:"别名已保存。":result.error||"操作失败");setBusy(false);if(response.ok){setValue("");await load()}}
 return <main className={styles.page}><header><div><a href="/inventory">← 返回耗材库存</a><small>MATERIAL MASTER DATA</small><h1>Bambu 耗材与颜色主数据</h1><p>官方字段保存来源与核验日期；AMS 上报值通过别名匹配，不直接覆盖库存档案。</p></div>{canEdit?<button disabled={busy} onClick={()=>void mutate({action:"importBambuStarter"})}>导入/更新官方基础色</button>:null}</header>{message?<p className={styles.message}>{message}</p>:null}<section className={styles.source}><b>官方快照来源</b><a href={data.source.url} target="_blank" rel="noreferrer">Bambu Lab PLA Basic 官方商品页</a><span>核验日期：{data.source.checkedAt}</span><small>商品颜色会调整；本系统只内置名称、色号和 HEX 均能交叉确认的基础集合。</small></section><section className={styles.preview}>{data.starter.map(item=><article key={item.code}><i style={{background:`#${item.hex}`}}/><span><b>{item.nameZh}</b><small>{item.name} · {item.code}</small></span><code>#{item.hex}</code></article>)}</section>
  <section className={styles.panel}><header><div><h2>组织耗材目录</h2><p>{data.catalog.filter(x=>x.officialVerified).length} 条已标记官方核验</p></div></header><div className={styles.catalog}>{data.catalog.map(item=><article key={item.id}><i style={{background:`#${item.colorHex}`}}/><span><b>{item.brand} · {item.series}</b><strong>{item.colorName} / {item.colorNameEn}</strong><small>{item.catalogCode} · 色号 {item.colorCode||"—"} · #{item.colorHex}</small><small>{item.officialVerified?`官方核验 · ${item.sourceCheckedAt}`:"人工维护"}</small></span><div>{data.aliases.filter(alias=>alias.catalogItemId===item.id).map(alias=><em key={alias.id}>{aliasNames[alias.aliasType]}：{alias.aliasValue}</em>)}</div>{canEdit?<button onClick={()=>setSelected(item.id)}>添加别名</button>:null}</article>)}</div></section>{selected?<div className={styles.modal}><form onSubmit={event=>{event.preventDefault();void mutate({action:"addAlias",catalogItemId:selected,aliasType:type,aliasValue:value});setSelected(0)}}><h2>添加设备识别别名</h2><select value={type} onChange={event=>setType(event.target.value)}>{Object.entries(aliasNames).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><input required value={value} onChange={event=>setValue(event.target.value)} placeholder="例如 PLA_BASIC、#FFFFFF"/><footer><button type="button" onClick={()=>setSelected(0)}>取消</button><button disabled={busy}>保存别名</button></footer></form></div>:null}</main>}
