"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {catalogImportTemplate} from "../../materials/catalog-import";
import styles from "./material-master.module.css";
type Item={id:number;catalogCode:string;brand:string;series:string;material:string;colorName:string;colorNameEn:string;colorCode:string;colorHex:string;densityGcm3?:number;defaultNetGrams?:number;defaultTareGrams?:number;sourceType:string;sourceUrl:string;sourceCheckedAt:string|null;officialVerified:number;amsCompatibility:string;reorderPointSpools:number;targetStockSpools:number};
type Alias={id:number;catalogItemId:number;aliasType:string;aliasValue:string;source:string};type Starter={code:string;name:string;nameZh:string;hex:string};
type Summary={total:number;create:number;update:number;unchanged:number;rejected:number};type ReviewRow={rowNumber:number;catalogCode:string;brand:string;series:string;material:string;colorName:string;colorCode:string;colorHex:string;action:"create"|"update"|"unchanged"|"rejected";errors:string[]};
type Batch={id:number;batchKey:string;fileName:string;status:string;summary:Summary;createdBy:string;createdAt:string;appliedBy:string|null;appliedAt:string|null};
type Data={catalog:Item[];aliases:Alias[];batches:Batch[];starter:Starter[];source:{url:string;checkedAt:string}};
const aliasNames:Record<string,string>={material:"材质别名",rfid_material:"RFID材质值",color_name:"颜色名称",color_code:"官方色号",color_hex:"HEX色值"};
const actionNames={create:"新增",update:"更新",unchanged:"无变化",rejected:"拒绝"};

export default function MaterialMasterClient({canEdit}:{canEdit:boolean}){
 const[data,setData]=useState<Data>({catalog:[],aliases:[],batches:[],starter:[],source:{url:"",checkedAt:""}}),[selected,setSelected]=useState(0),[editing,setEditing]=useState<Item|Record<string,never>|null>(null),[policy,setPolicy]=useState<Item|null>(null),[reorder,setReorder]=useState("2"),[target,setTarget]=useState("5"),[type,setType]=useState("material"),[value,setValue]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[review,setReview]=useState<{batchId:number;rows:ReviewRow[];summary:Summary}|null>(null);
 const aliasesByItem=useMemo(()=>{const map=new Map<number,Alias[]>();for(const alias of data.aliases)map.set(alias.catalogItemId,[...(map.get(alias.catalogItemId)||[]),alias]);return map},[data.aliases]);
 const load=useCallback(async()=>{const response=await fetch("/api/material-master",{cache:"no-store"}),body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error||"读取主数据失败");setData(body)},[]);
 useEffect(()=>{void load().catch(error=>setMessage(error.message))},[load]);
 async function mutate(body:Record<string,unknown>){setBusy(true);try{const response=await fetch("/api/material-master",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json() as{error?:string;imported?:number;applied?:number;targetStockSpools?:number};if(!response.ok)throw new Error(result.error||"操作失败");setMessage(result.imported?`已导入或更新 ${result.imported} 条官方基础色。`:result.applied!==undefined?`已应用 ${result.applied} 条目录变更。`:result.targetStockSpools!==undefined?"补货策略已保存。":"别名已保存。");setValue("");setReview(null);setPolicy(null);await load()}catch(error){setMessage(error instanceof Error?error.message:"操作失败")}finally{setBusy(false)}}
 async function preview(file:File){setBusy(true);try{const csv=await file.text(),response=await fetch("/api/material-master",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"previewImport",csv,fileName:file.name})}),result=await response.json() as{error?:string;batchId:number;rows:ReviewRow[];summary:Summary};if(!response.ok)throw new Error(result.error||"预览失败");setReview(result);setMessage("预览已生成，请核对后确认应用。");await load()}catch(error){setMessage(error instanceof Error?error.message:"预览失败")}finally{setBusy(false)}}
 function downloadTemplate(){const blob=new Blob(["\uFEFF",catalogImportTemplate()],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="耗材主数据导入模板.csv";link.click();URL.revokeObjectURL(url)}
 return <main className={styles.page}>
  <header><div><a href="/inventory">← 返回耗材库存</a><small>MATERIAL MASTER DATA</small><h1>Bambu 耗材与颜色主数据</h1><p>官方字段保存来源与核验日期；AMS 上报值通过别名匹配，不直接覆盖库存档案。</p></div>{canEdit?<button disabled={busy} onClick={()=>void mutate({action:"importBambuStarter"})}>导入/更新官方基础色</button>:null}</header>
  {message?<p className={styles.message}>{message}</p>:null}
  <section className={styles.source}><b>官方快照来源</b><a href={data.source.url} target="_blank" rel="noreferrer">Bambu Lab PLA Basic 官方商品页</a><span>核验日期：{data.source.checkedAt}</span><small>商品颜色会调整；本系统只内置名称、色号和 HEX 均能交叉确认的基础集合。</small></section>
  <section className={styles.preview}>{data.starter.map(item=><article key={item.code}><i style={{background:`#${item.hex}`}}/><span><b>{item.nameZh}</b><small>{item.name} · {item.code}</small></span><code>#{item.hex}</code></article>)}</section>
  {canEdit?<section className={styles.panel}><header><div><h2>批量导入与变更审核</h2><p>最多 500 行；先预览再应用。普通 CSV 不能覆盖官方核验记录。</p></div><div className={styles.importActions}><button onClick={downloadTemplate}>下载 CSV 模板</button><label className={styles.upload}>选择 CSV<input type="file" accept=".csv,text/csv" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void preview(file);event.currentTarget.value=""}}/></label></div></header>
   {review?<div className={styles.review}><div className={styles.summary}><b>共 {review.summary.total}</b><span>新增 {review.summary.create}</span><span>更新 {review.summary.update}</span><span>无变化 {review.summary.unchanged}</span><span className={review.summary.rejected?styles.danger:""}>拒绝 {review.summary.rejected}</span><button disabled={busy||review.summary.rejected>0} onClick={()=>void mutate({action:"applyImport",batchId:review.batchId})}>确认应用变更</button></div><div className={styles.reviewRows}>{review.rows.map(row=><article key={`${row.rowNumber}-${row.catalogCode}`}><b>第 {row.rowNumber} 行 · {row.catalogCode}</b><span>{row.brand} / {row.series} / {row.material} / {row.colorName}</span><em className={styles[row.action]}>{actionNames[row.action]}</em>{row.errors.length?<small>{row.errors.join("；")}</small>:null}</article>)}</div></div>:null}
   <div className={styles.history}><h3>最近导入批次</h3>{data.batches.length?data.batches.map(batch=><article key={batch.id}><b>{batch.fileName}</b><span>{batch.status==="applied"?"已应用":"待审核"} · 新增 {batch.summary.create} / 更新 {batch.summary.update} / 拒绝 {batch.summary.rejected}</span><small>{batch.createdBy} · {batch.createdAt}</small></article>):<p>暂无导入记录</p>}</div>
  </section>:null}
  <section className={styles.panel}><header><div><h2>组织耗材目录</h2><p>{data.catalog.filter(item=>item.officialVerified).length} 条已标记官方核验</p></div>{canEdit?<button onClick={()=>setEditing({})}>新增耗材主数据</button>:null}</header><div className={styles.catalog}>{data.catalog.map(item=><article key={item.id}><i style={{background:`#${item.colorHex}`}}/><span><b>{item.brand} · {item.series}</b><strong>{item.colorName} / {item.colorNameEn}</strong><small>{item.catalogCode} · 色号 {item.colorCode||"—"} · #{item.colorHex}</small><small>{item.officialVerified?`官方核验 · ${item.sourceCheckedAt}`:"人工维护"}</small></span><div>{(aliasesByItem.get(item.id)||[]).map(alias=><em key={alias.id}>{aliasNames[alias.aliasType]}：{alias.aliasValue}</em>)}<em>≤ {item.reorderPointSpools} 卷触发补货</em><em>目标 {item.targetStockSpools} 卷</em></div>{canEdit?<aside className={styles.rowActions}><button onClick={()=>setEditing(item)}>编辑</button><button onClick={()=>setSelected(item.id)}>添加别名</button><button onClick={()=>{setPolicy(item);setReorder(String(item.reorderPointSpools));setTarget(String(item.targetStockSpools))}}>补货策略</button>{!item.officialVerified?<button className={styles.delete} onClick={()=>{if(window.confirm(`确认删除 ${item.catalogCode}？仅无库存和采购引用时允许删除。`))void mutate({action:"deleteCatalog",catalogItemId:item.id})}}>删除</button>:null}</aside>:null}</article>)}</div></section>
  {editing?<div className={styles.modal}><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void mutate({action:"saveCatalog",catalogItemId:"id" in editing?editing.id:undefined,...Object.fromEntries(form)}).then(()=>setEditing(null))}}><h2>{"id" in editing?"编辑耗材主数据":"新增耗材主数据"}</h2><label>目录编码 / SKU<input name="catalogCode" required defaultValue={"catalogCode" in editing?editing.catalogCode:""}/></label><label>品牌<input name="brand" required defaultValue={"brand" in editing?editing.brand:"Bambu Lab"}/></label><label>系列<input name="series" defaultValue={"series" in editing?editing.series:""}/></label><label>材质<input name="material" required defaultValue={"material" in editing?editing.material:"PLA"}/></label><label>颜色名称<input name="colorName" required defaultValue={"colorName" in editing?editing.colorName:""}/></label><label>英文颜色<input name="colorNameEn" defaultValue={"colorNameEn" in editing?editing.colorNameEn:""}/></label><label>官方色号<input name="colorCode" defaultValue={"colorCode" in editing?editing.colorCode:""}/></label><label>HEX 色值<input name="colorHex" required pattern="[0-9A-Fa-f#]{6,7}" defaultValue={"colorHex" in editing?editing.colorHex:""}/></label><label>密度 g/cm³<input name="densityGcm3" type="number" step=".001" min=".1" defaultValue={"densityGcm3" in editing?editing.densityGcm3||1.24:1.24}/></label><label>默认净重 g<input name="defaultNetGrams" type="number" min="1" defaultValue={"defaultNetGrams" in editing?editing.defaultNetGrams||1000:1000}/></label><label>默认空盘重量 g<input name="defaultTareGrams" type="number" min="0" defaultValue={"defaultTareGrams" in editing?editing.defaultTareGrams||0:0}/></label><label>AMS 兼容<select name="amsCompatibility" defaultValue={"amsCompatibility" in editing?editing.amsCompatibility:"unknown"}><option value="compatible">兼容</option><option value="conditional">有条件兼容</option><option value="incompatible">不兼容</option><option value="unknown">待确认</option></select></label><footer><button type="button" onClick={()=>setEditing(null)}>取消</button><button disabled={busy}>保存主数据</button></footer></form></div>:null}
  {selected?<div className={styles.modal}><form onSubmit={event=>{event.preventDefault();void mutate({action:"addAlias",catalogItemId:selected,aliasType:type,aliasValue:value});setSelected(0)}}><h2>添加设备识别别名</h2><select value={type} onChange={event=>setType(event.target.value)}>{Object.entries(aliasNames).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><input required value={value} onChange={event=>setValue(event.target.value)} placeholder="例如 PLA_BASIC、#FFFFFF"/><footer><button type="button" onClick={()=>setSelected(0)}>取消</button><button disabled={busy}>保存别名</button></footer></form></div>:null}
  {policy?<div className={styles.modal}><form onSubmit={event=>{event.preventDefault();void mutate({action:"updateStockPolicy",catalogItemId:policy.id,reorderPointSpools:Number(reorder),targetStockSpools:Number(target)})}}><h2>设置补货策略</h2><p>{policy.catalogCode} · {policy.material}/{policy.colorName}</p><label>触发补货库存（卷）<input type="number" min="0" max="10000" required value={reorder} onChange={event=>setReorder(event.target.value)}/></label><label>目标库存（卷）<input type="number" min={Number(reorder)||0} max="10000" required value={target} onChange={event=>setTarget(event.target.value)}/></label><footer><button type="button" onClick={()=>setPolicy(null)}>取消</button><button disabled={busy||Number(target)<Number(reorder)}>保存策略</button></footer></form></div>:null}
 </main>
}
