import {getD1} from "../db";import {getCashflowForecast} from "../finance/cashflow";import {getBusinessTargets} from "../business-targets/data";
export async function getExecutiveWorkbench(organizationId:number){const db=getD1(),today=new Date().toISOString().slice(0,10),soon=new Date(Date.now()+2*86400000).toISOString().slice(0,10),[cashflow,targets,receivables,payables,stock,alerts,orders,settlements]=await Promise.all([
 getCashflowForecast(organizationId),
 getBusinessTargets(organizationId),
 db.prepare("SELECT COUNT(*) count,COALESCE(SUM(amount_cents-paid_cents),0) cents FROM invoices WHERE organization_id=? AND status='overdue'").bind(organizationId).first<{count:number;cents:number}>(),
 db.prepare(`SELECT COUNT(*) count,COALESCE(SUM(i.actual_total_cents-COALESCE((SELECT SUM(p.amount_cents) FROM supplier_payments p WHERE p.organization_id=i.organization_id AND p.supplier_invoice_id=i.id),0)),0) cents FROM supplier_invoices i WHERE i.organization_id=? AND i.status IN ('matched','approved') AND COALESCE(i.due_date,date(i.invoice_date,'+'||i.payment_terms_days||' days'))<? AND i.actual_total_cents>COALESCE((SELECT SUM(p.amount_cents) FROM supplier_payments p WHERE p.organization_id=i.organization_id AND p.supplier_invoice_id=i.id),0)`).bind(organizationId,today).first<{count:number;cents:number}>(),
 db.prepare(`SELECT COUNT(*) count FROM material_catalog_items c WHERE c.organization_id=? AND COALESCE((SELECT COUNT(*) FROM material_spools s WHERE s.organization_id=c.organization_id AND s.catalog_item_id=c.id AND s.state IN ('sealed','open_storage')),0)<c.reorder_point_spools`).bind(organizationId).first<{count:number}>(),
 db.prepare("SELECT COUNT(*) count FROM alerts WHERE organization_id=? AND signal_active=1 AND status!='resolved' AND severity='critical'").bind(organizationId).first<{count:number}>(),
 db.prepare("SELECT COUNT(*) count FROM orders WHERE organization_id=? AND status NOT IN ('已完成','completed','cancelled') AND due_at IS NOT NULL AND substr(due_at,1,10)<=?").bind(organizationId,soon).first<{count:number}>(),
 db.prepare(`SELECT COUNT(DISTINCT ps.id) count FROM print_sessions ps JOIN print_material_usage_lines u ON u.print_session_id=ps.id AND u.organization_id=ps.organization_id WHERE ps.organization_id=? AND ps.status IN ('completed','failed','cancelled') AND u.settled_at IS NULL`).bind(organizationId).first<{count:number}>(),
]);const horizon30=cashflow.horizons[0],priorities:Array<{key:string;tone:"danger"|"warning"|"info";title:string;detail:string;href:string}> = [];
 if(horizon30.gapCents)priorities.push({key:"cash-gap",tone:"danger",title:"未来30天存在资金缺口",detail:`低于安全储备 ${(horizon30.gapCents/100).toFixed(2)} MYR`,href:"/cashflow"});
 if(Number(receivables?.count))priorities.push({key:"receivables",tone:"danger",title:`${receivables?.count} 笔应收逾期`,detail:`待回款 ${(Number(receivables?.cents)/100).toFixed(2)} MYR`,href:"/receivables"});
 if(Number(payables?.count))priorities.push({key:"payables",tone:"warning",title:`${payables?.count} 笔应付逾期`,detail:`待付款 ${(Number(payables?.cents)/100).toFixed(2)} MYR`,href:"/payables"});
 if(targets.offTrack)priorities.push({key:"business-targets",tone:"warning",title:`${targets.offTrack} 项经营指标偏离目标`,detail:"查看实际值、目标值和偏差处理建议",href:"/business-targets"});
 return {generatedAt:new Date().toISOString(),metrics:{cashGap30Cents:horizon30.gapCents,projectedCash30Cents:horizon30.endingCashCents,overdueReceivableCents:Number(receivables?.cents??0),overduePayableCents:Number(payables?.cents??0),lowStock:Number(stock?.count??0),criticalAlerts:Number(alerts?.count??0),orderRisks:Number(orders?.count??0),unsettledPrints:Number(settlements?.count??0),offTrackTargets:targets.offTrack},priorities};}
