/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-html-link-for-pages, @typescript-eslint/no-unused-expressions */
"use client";
import{FormEvent,useEffect,useState}from"react";
import{DialogProvider,useDialogs}from"../ui-dialogs";
type Member={id:number;email:string;displayName:string;role:string;status:string};
type Log={id:number;actorEmail:string;action:string;resource:string;resourceId:string;createdAt:string};
const names:Record<string,string>={owner:"超级管理员",manager:"主管",orders:"订单人员",operator:"打印操作员",warehouse:"仓库人员",finance:"财务人员",viewer:"只读账号"};

export default function TeamClient(props:{user:{displayName:string;email:string};signOut:string}){return <DialogProvider><TeamWorkspace {...props}/></DialogProvider>}
function TeamWorkspace({user,signOut}:{user:{displayName:string;email:string};signOut:string}){
  const dialogs=useDialogs();
  const[members,setMembers]=useState<Member[]>([]),[logs,setLogs]=useState<Log[]>([]),[error,setError]=useState("");
  const load=async()=>{const response=await fetch("/api/team",{cache:"no-store"}),value=await response.json();response.ok?(setMembers(value.members),setLogs(value.logs)):setError(value.error)};
  useEffect(()=>{void load()},[]);
  async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,response=await fetch("/api/team",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))}),value=await response.json();if(!response.ok)return setError(value.error);form.reset();setError("");await load()}
  async function update(member:Member,status:string,role=member.role){const response=await fetch("/api/team",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:member.id,status,role})}),value=await response.json();response.ok?await load():setError(value.error)}
  async function resetPassword(member:Member){const password=await dialogs.prompt({title:"重置员工密码",message:`为 ${member.displayName||member.email} 设置新密码，至少 10 位。`,inputType:"password",placeholder:"输入新密码",confirmLabel:"确认重置"});if(!password)return;const response=await fetch("/api/team",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:member.id,password})}),value=await response.json();response.ok?setError("密码已重置，请安全告知员工"):setError(value.error)}
  return <main className="team-shell"><header className="team-top"><div><a href="/" className="team-brand">LAYERTRACE</a><span>员工与权限</span></div><div><small>{user.displayName} · {user.email}</small><a href={signOut}>退出</a></div></header><section className="team-hero"><div><p>TEAM ACCESS</p><h1>让每位员工只看到<br/>自己该负责的工作</h1><span>独立密码、岗位权限、停用控制与操作审计集中管理。</span></div><form onSubmit={invite}><h2>创建员工账号</h2><input name="displayName" placeholder="员工姓名" required/><input name="email" type="email" placeholder="员工邮箱" required/><input name="password" type="password" minLength={10} placeholder="初始密码（至少 10 位）" required/><select name="role" defaultValue="operator">{Object.entries(names).filter(([value])=>value!=="owner").map(([value,name])=><option value={value} key={value}>{name}</option>)}</select><button>创建账号</button>{error&&<em>{error}</em>}</form></section><section className="team-grid"><article className="team-panel"><div className="team-title"><small>MEMBERS</small><h2>员工账号 · {members.length}</h2></div>{members.map(member=><div className="member-row" key={member.id}><i>{(member.displayName||member.email)[0].toUpperCase()}</i><div><strong>{member.displayName||"待填写姓名"}</strong><span>{member.email}</span></div><select value={member.role} disabled={member.role==="owner"} onChange={event=>void update(member,member.status,event.target.value)}>{Object.entries(names).map(([value,name])=><option value={value} key={value}>{name}</option>)}</select><b className={`member-status ${member.status}`}>{member.status==="active"?"已启用":member.status==="invited"?"待设置密码":"已停用"}</b>{member.role!=="owner"&&<><button onClick={()=>void resetPassword(member)}>重置密码</button><button onClick={()=>void update(member,member.status==="disabled"?"active":"disabled")}>{member.status==="disabled"?"启用":"停用"}</button></>}</div>)}</article><article className="team-panel"><div className="team-title"><small>AUDIT TRAIL</small><h2>最近操作记录</h2></div><div className="audit-list">{logs.map(log=><div key={log.id}><i/><p><strong>{log.actorEmail}</strong><span>{log.action} · {log.resource}{log.resourceId?` #${log.resourceId}`:""}</span></p><time>{new Date(log.createdAt+"Z").toLocaleString("zh-CN")}</time></div>)}{!logs.length&&<p>暂无操作记录</p>}</div></article></section></main>
}
