"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./quotes.module.css";
type Customer={id:number;customerNo:string;name:string;contacts:string};
type Quote={id:number;quoteNo:string;status:string;validUntil:string;customerName:string;subtotalCents:number;costCents:number;acceptedOrderId:number|null};
type Product={id:number;sku:string;name:string;unitCostCents:number};
type Data={customers:Customer[];quotes:Quote[];products:Product[]};
const money=(cents:number)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:"MYR"}).format(cents/100);
export default function QuotesClient({canEdit}:{canEdit:boolean}){
  const [data,setData]=useState<Data>({customers:[],quotes:[],products:[]}),[message,setMessage]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/quotes");const value=await response.json();if(response.ok)setData(value);else setMessage(value.error);},[]);
  useEffect(()=>{void load()},[load]);
  const submit=async(event:FormEvent<HTMLFormElement>,action:string)=>{event.preventDefault();const form=new FormData(event.currentTarget),body=Object.fromEntries(form);let payload:Record<string,unknown>={action,...body};if(action==="quote")payload={...payload,items:[{itemId:Number(body.itemId),quantity:Number(body.quantity),unitPriceCents:body.unitPriceCents?Number(body.unitPriceCents):undefined}]};const response=await fetch("/api/quotes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),value=await response.json();setMessage(response.ok?"保存成功":value.error);if(response.ok){event.currentTarget.reset();await load()}};
  const accept=async(id:number)=>{const response=await fetch("/api/quotes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"accept",quoteId:id})}),value=await response.json();setMessage(response.ok?`已转为订单 #${value.orderId}${value.idempotent?"（无需重复创建）":""}`:value.error);if(response.ok)await load()};
  return <main className={styles.page}><header><span>CRM & QUOTATION</span><h1>客户与报价</h1><p>以标准成本和目标毛利生成建议售价，接受后自动进入生产订单。</p></header>{message?<div className={styles.message}>{message}</div>:null}
    {canEdit?<section className={styles.forms}><form onSubmit={e=>void submit(e,"customer")}><h2>新建客户</h2><input name="name" placeholder="客户名称" required/><input name="customerNo" placeholder="客户编号（可自动生成）"/><input name="taxId" placeholder="税务编号"/><button>保存客户</button></form><form onSubmit={e=>void submit(e,"quote")}><h2>新建报价</h2><select name="customerId" required defaultValue=""><option value="" disabled>选择客户</option>{data.customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="itemId" required defaultValue=""><option value="" disabled>选择产品</option>{data.products.map(x=><option key={x.id} value={x.id}>{x.sku} · {x.name}（成本 {money(x.unitCostCents)}）</option>)}</select><div className={styles.row}><input name="quantity" type="number" min="1" defaultValue="1" required/><input name="targetMarginBasisPoints" type="number" min="0" max="9900" defaultValue="3000" title="目标毛利，3000 表示 30%"/></div><input name="unitPriceCents" type="number" min="0" placeholder="自定单价 cents（留空使用建议价）"/><input name="validUntil" type="date" required/><button>生成报价</button></form></section>:null}
    <section className={styles.panel}><h2>报价记录</h2><div className={styles.table}><div className={styles.head}><b>报价 / 客户</b><b>有效期</b><b>成本 / 金额</b><b>状态</b><b>操作</b></div>{data.quotes.map(q=><div className={styles.line} key={q.id}><span><strong>{q.quoteNo}</strong><small>{q.customerName}</small></span><span>{q.validUntil}</span><span>{money(q.costCents)}<small>{money(q.subtotalCents)}</small></span><span className={styles.status}>{q.status}</span><span>{canEdit&&["draft","sent"].includes(q.status)?<button onClick={()=>void accept(q.id)}>接受并转订单</button>:q.acceptedOrderId?`订单 #${q.acceptedOrderId}`:"—"}</span></div>)}</div></section></main>
}
