import {getD1} from "../../../db";
import {getAccessContext} from "../../access-control";
import {requireApiAccess} from "../../api-auth";
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
async function ensureSettings(org:number){await getD1().prepare("INSERT OR IGNORE INTO cost_settings(id) VALUES(?)").bind(org).run()}
export async function GET(request:Request){const denied=await requireApiAccess(false,"finance.read");if(denied)return denied;const user=await getAccessContext();if(!user)return Response.json({error:"请先登录"},{status:401});try{const db=getD1(),org=user.organizationId;await ensureSettings(org);const [summary,settings,orders,trends,byPrinter,byItem,reasons]=await Promise.all([
db.prepare(`SELECT COALESCE((SELECT SUM(oi.quantity*oi.unit_price) FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.organization_id=?),0) revenue,COALESCE((SELECT SUM(ABS(t.grams)*b.cost_per_kg/1000.0) FROM inventory_transactions t JOIN material_batches b ON b.id=t.batch_id JOIN material_batch_organizations mbo ON mbo.batch_id=b.id WHERE mbo.organization_id=? AND t.type='打印消耗'),0) material_cost,COALESCE((SELECT SUM(MAX(0,(julianday(j.completed_at)-julianday(j.started_at))*24)*COALESCE(p.hourly_rate,0)) FROM print_jobs j LEFT JOIN printers p ON p.id=j.printer_id WHERE j.organization_id=? AND j.completed_at IS NOT NULL),0) machine_cost,COALESCE((SELECT SUM(MAX(0,(julianday(j.completed_at)-julianday(j.started_at))*24)*COALESCE(p.power_watts,1000)/1000.0) FROM print_jobs j LEFT JOIN printers p ON p.id=j.printer_id WHERE j.organization_id=? AND j.completed_at IS NOT NULL),0) energy_kwh,(SELECT COUNT(*) FROM print_jobs WHERE organization_id=? AND status='已完成') completed,(SELECT COUNT(*) FROM print_jobs WHERE organization_id=? AND status IN ('已完成','失败','已取消')) terminal,COALESCE((SELECT SUM(MAX(0,(julianday(completed_at)-julianday(started_at))*24)) FROM print_jobs WHERE organization_id=? AND completed_at IS NOT NULL AND datetime(completed_at)>=datetime('now','-30 days')),0) productive_hours,(SELECT COUNT(*) FROM printer_bindings WHERE organization_id=? AND status!='disabled') active_printers,(SELECT COUNT(*) FROM print_job_events e JOIN print_jobs j ON j.id=e.job_id WHERE j.organization_id=? AND e.action='retry') reworks`).bind(org,org,org,org,org,org,org,org,org).first<Record<string,number>>(),
db.prepare("SELECT electricity_rate electricityRate,labor_rate laborRate,labor_minutes_per_job laborMinutesPerJob,overhead_percent overheadPercent FROM cost_settings WHERE id=?").bind(org).first<Record<string,number>>(),
db.prepare(`SELECT o.order_no orderNo,o.customer,o.status,COALESCE(SUM(oi.quantity*oi.unit_price),0) revenue,(SELECT COUNT(*) FROM print_jobs j WHERE j.order_id=o.id AND j.organization_id=o.organization_id) jobs,(SELECT COUNT(*) FROM print_jobs j WHERE j.order_id=o.id AND j.organization_id=o.organization_id AND j.status='已完成') completedJobs FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id WHERE o.organization_id=? GROUP BY o.id ORDER BY o.created_at DESC LIMIT 100`).bind(org).all(),
db.prepare(`WITH RECURSIVE days(day) AS (SELECT date('now','-6 days') UNION ALL SELECT date(day,'+1 day') FROM days WHERE day<date('now')) SELECT day,COUNT(j.id) completed FROM days LEFT JOIN print_jobs j ON date(j.completed_at)=day AND j.status='已完成' AND j.organization_id=? GROUP BY day ORDER BY day`).bind(org).all(),
db.prepare(`SELECT COALESCE(p.name,j.printer_name) name,COUNT(*) total,SUM(CASE WHEN j.status='已完成' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN j.status='失败' THEN 1 ELSE 0 END) failed FROM print_jobs j LEFT JOIN printers p ON p.id=j.printer_id WHERE j.organization_id=? AND j.status IN ('已完成','失败') GROUP BY COALESCE(p.name,j.printer_name) ORDER BY total DESC`).bind(org).all(),
db.prepare(`SELECT COALESCE(i.name,'未关联物品') name,COUNT(*) total,SUM(CASE WHEN j.status='已完成' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN j.status='失败' THEN 1 ELSE 0 END) failed FROM print_jobs j LEFT JOIN print_items i ON i.id=j.item_id AND i.organization_id=j.organization_id WHERE j.organization_id=? AND j.status IN ('已完成','失败') GROUP BY j.item_id ORDER BY total DESC LIMIT 20`).bind(org).all(),
db.prepare(`SELECT CASE WHEN TRIM(e.note)='' THEN '未填写' ELSE e.note END reason,COUNT(*) count FROM print_job_events e JOIN print_jobs j ON j.id=e.job_id WHERE j.organization_id=? AND e.action='fail' GROUP BY CASE WHEN TRIM(e.note)='' THEN '未填写' ELSE e.note END ORDER BY count DESC LIMIT 10`).bind(org).all()]);
const s=summary||{},c=settings||{},revenue=Number(s.revenue||0),materialCost=Number(s.material_cost||0),machineCost=Number(s.machine_cost||0),energyCost=Number(s.energy_kwh||0)*Number(c.electricityRate||0),laborCost=Number(s.completed||0)*Number(c.laborMinutesPerJob||0)/60*Number(c.laborRate||0),baseCost=materialCost+machineCost+energyCost+laborCost,overheadCost=baseCost*Number(c.overheadPercent||0)/100,totalCost=baseCost+overheadCost,result={summary:{revenue,materialCost,machineCost,energyCost,laborCost,overheadCost,totalCost,grossProfit:revenue-totalCost,margin:revenue?(revenue-totalCost)/revenue*100:0,successRate:Number(s.terminal)?Number(s.completed)/Number(s.terminal)*100:0,utilization:Number(s.active_printers)?Number(s.productive_hours)/(Number(s.active_printers)*720)*100:0,completed:Number(s.completed||0),reworks:Number(s.reworks||0)},settings:c,orders:orders.results,trends:trends.results,byPrinter:byPrinter.results,byItem:byItem.results,reasons:reasons.results};if(new URL(request.url).searchParams.get("format")==="csv"){const rows=[["订单编号","客户","状态","订单收入","任务数","完成数"],...result.orders.map((o:Record<string,unknown>)=>[o.orderNo,o.customer,o.status,o.revenue,o.jobs,o.completedJobs])];return new Response("\uFEFF"+rows.map(row=>row.map(csvCell).join(",")).join("\r\n"),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="layertrace-report-${new Date().toISOString().slice(0,10)}.csv"`}})}return Response.json(result)}catch(error){return Response.json({error:error instanceof Error?error.message:"分析读取失败"},{status:500})}}
