"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
type Material={id:number;sku:string;material:string;color:string;remainingGrams:number;lowStockGrams:number;incomingGrams:number;suggestedGrams:number};
type Supplier={id:number;code:string;name:string};type RequestRow={id:number;request_no:string;status:string;requestedGrams:number;created_at:string};
type Order={id:number;purchase_no:string;requestNo:string;supplierName:string;status:string;orderedGrams:number;receivedGrams:number};
type Item={id:number;orderId:number;sku:string;material:string;color:string;orderedGrams:number;receivedGrams:number};
type Receipt={id:number;receipt_no:string;purchaseNo:string;received_by:string;received_at:string};
type Data={canManage:boolean;canReceive:boolean;materials:Material[];suppliers:Supplier[];requests:RequestRow[];orders:Order[];orderItems:Item[];receipts:Receipt[]};
const status:Record<string,string>={draft:"草稿",pending:"待审批",approved:"已审批",ordered:"采购中",partially_received:"部分收货",completed:"已完成",cancelled:"已取消"};
export default function ProcurementClient(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const r=await fetch("/api/procurement",{cache:"no-store"}),v=await r.json();if(!r.ok)throw new Error(v.error);setData(v)},[]);useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 async function mutate(method:"POST"|"PATCH",body:unknown){setBusy(true);setError("");try{const r=await fetch("/api/procurement",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)}),v=await r.json();if(!r.ok)throw new Error(v.error);await load()}catch(e){setError(e instanceof Error?e.message:"操作失败")}finally{setBusy(false)}}
 const low=useMemo(()=>data?.materials.filter(x=>x.suggestedGrams>0)??[],[data]);
 function request(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);void mutate("POST",{action:"request",batchId:Number(f.get("batchId")),grams:Number(f.get("grams")),reason:f.get("reason")})}
 if(!data)return <main className="procurement-page"><p>{error||"正在加载采购中心…"}</p></main>;
 return <main className="procurement-page"><header><div><small>SUPPLY LOOP · CONTROLLED RECEIVING</small><h1>采购与补货中心</h1><p>从低库存建议、审批下单到分批收货和库存流水，形成可审计闭环。</p></div><a href="/">返回工作台</a></header>{error&&<div className="error">{error}</div>}
 <section className="stats"><article><span>低库存建议</span><b>{low.length}</b></article><article><span>待审批申请</span><b>{data.requests.filter(x=>x.status==="pending").length}</b></article><article><span>在途订单</span><b>{data.orders.filter(x=>["ordered","partially_received"].includes(x.status)).length}</b></article><article><span>累计收货</span><b>{data.receipts.length}</b></article></section>
 <div className="grid"><section className="panel"><small>REPLENISHMENT</small><h2>低库存补货建议</h2>{low.length===0?<p className="empty">当前没有需要补货的耗材</p>:low.map(m=><article className="material" key={m.id}><div><b>{m.sku} · {m.material} / {m.color}</b><span>库存 {m.remainingGrams}g · 在途 {m.incomingGrams}g</span></div><strong>建议 {m.suggestedGrams}g</strong></article>)}
 {data.canReceive&&<form onSubmit={request}><label>耗材<select name="batchId" required><option value="">选择低库存耗材</option>{low.map(m=><option key={m.id} value={m.id}>{m.sku} · 建议 {m.suggestedGrams}g</option>)}</select></label><label>申请克重<input name="grams" type="number" min="1" step="1" required/></label><label>补货原因<input name="reason" placeholder="低库存补货、生产计划需求…"/></label><button disabled={busy}>提交采购申请</button></form>}</section>
 <section className="panel"><small>APPROVAL QUEUE</small><h2>采购申请</h2>{data.requests.map(r=><article className="row" key={r.id}><div><b>{r.request_no}</b><span>{status[r.status]} · {Number(r.requestedGrams)}g</span></div>{data.canManage&&r.status==="pending"&&<button disabled={busy} onClick={()=>mutate("PATCH",{action:"approve",requestId:r.id})}>审批</button>}{data.canManage&&r.status==="approved"&&<button disabled={busy||!data.suppliers.length} onClick={()=>mutate("PATCH",{action:"order",requestId:r.id,supplierId:data.suppliers[0]?.id})}>向首选供应商下单</button>}</article>)}</section></div>
 <section className="panel orders"><small>PURCHASE ORDERS</small><h2>采购订单与收货</h2>{data.orders.map(o=><article className="order" key={o.id}><div className="order-head"><div><b>{o.purchase_no} · {o.supplierName}</b><span>{status[o.status]} · 已收 {Number(o.receivedGrams)} / {Number(o.orderedGrams)}g</span></div>{data.canManage&&["ordered","partially_received"].includes(o.status)&&<button className="quiet" onClick={()=>mutate("PATCH",{action:"cancel",orderId:o.id})}>取消订单</button>}</div>{data.orderItems.filter(i=>i.orderId===o.id).map(i=><div className="item" key={i.id}><span>{i.sku} · {i.material}/{i.color} · 未收 {i.orderedGrams-i.receivedGrams}g</span>{data.canReceive&&["ordered","partially_received"].includes(o.status)&&i.receivedGrams<i.orderedGrams&&<button disabled={busy} onClick={()=>{const grams=prompt("本次实收克重",String(i.orderedGrams-i.receivedGrams));if(!grams)return;void mutate("PATCH",{action:"receive",orderId:o.id,itemId:i.id,grams:Number(grams),idempotencyKey:crypto.randomUUID()})}}>登记收货</button>}</div>)}</article>)}</section>
 {data.canReceive&&<section className="panel supplier"><small>SUPPLIER MASTER</small><h2>新增供应商</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate("POST",{action:"supplier",code:f.get("code"),name:f.get("name"),contact:f.get("contact")})}}><input name="code" required placeholder="供应商编码"/><input name="name" required placeholder="供应商名称"/><input name="contact" placeholder="联系人"/><button disabled={busy}>保存供应商</button></form></section>}</main>
}
