"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import SpoolLabel,{type LabelSpool} from "../inventory/spool-label";
type Material={id:number;sku:string;material:string;color:string;remainingGrams:number;lowStockGrams:number;incomingGrams:number;suggestedGrams:number};
type Supplier={id:number;code:string;name:string};type RequestRow={id:number;request_no:string;status:string;requestedGrams:number;created_at:string};
type Order={id:number;purchase_no:string;requestNo:string;supplierName:string;status:string;orderedGrams:number;receivedGrams:number};
type Item={id:number;orderId:number;sku:string;material:string;color:string;colorHex:string;catalogItemId:number|null;catalogCode:string|null;defaultNetGrams:number|null;defaultTareGrams:number|null;orderedGrams:number;receivedGrams:number};
type Receipt={id:number;receipt_no:string;purchaseNo:string;received_by:string;received_at:string;spoolCount:number};
type Data={canManage:boolean;canReceive:boolean;materials:Material[];suppliers:Supplier[];requests:RequestRow[];orders:Order[];orderItems:Item[];receipts:Receipt[]};
const status:Record<string,string>={draft:"草稿",pending:"待审批",approved:"已审批",ordered:"采购中",partially_received:"部分收货",completed:"已完成",cancelled:"已取消"};
export default function ProcurementClient(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[receiving,setReceiving]=useState<Item|null>(null),[labels,setLabels]=useState<LabelSpool[]>([]),[labelIndex,setLabelIndex]=useState(0);
 const load=useCallback(async()=>{const response=await fetch("/api/procurement",{cache:"no-store"}),value=await response.json();if(!response.ok)throw new Error(value.error);setData(value)},[]);useEffect(()=>{void load().catch(reason=>setError(reason.message))},[load]);
 async function mutate(method:"POST"|"PATCH",body:unknown){setBusy(true);setError("");try{const response=await fetch("/api/procurement",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)}),value=await response.json();if(!response.ok)throw new Error(value.error);await load();return value}catch(reason){setError(reason instanceof Error?reason.message:"操作失败")}finally{setBusy(false)}}
 const low=useMemo(()=>data?.materials.filter(item=>item.suggestedGrams>0)??[],[data]);
 const itemsByOrder=useMemo(()=>{const map=new Map<number,Item[]>();for(const item of data?.orderItems??[])map.set(item.orderId,[...(map.get(item.orderId)||[]),item]);return map},[data?.orderItems]);
 function request(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void mutate("POST",{action:"request",batchId:Number(form.get("batchId")),grams:Number(form.get("grams")),reason:form.get("reason")})}
 async function receive(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!receiving)return;const form=new FormData(event.currentTarget),result=await mutate("PATCH",{action:"receive",orderId:receiving.orderId,itemId:receiving.id,spoolCount:Number(form.get("spoolCount")),perSpoolNetGrams:Number(form.get("perSpoolNetGrams")),tareGrams:Number(form.get("tareGrams")),lotNo:form.get("lotNo"),idempotencyKey:crypto.randomUUID()});if(result?.spools){setLabels(result.spools);setLabelIndex(0);setReceiving(null)}}
 if(!data)return <main className="procurement-page"><p>{error||"正在加载采购中心…"}</p></main>;
 return <main className="procurement-page"><header><div><small>SUPPLY LOOP · SERIALIZED RECEIVING</small><h1>采购与补货中心</h1><p>从低库存建议、审批下单到逐卷收货和二维码标签，形成可审计闭环。</p></div><a href="/">返回工作台</a></header>{error?<div className="error">{error}</div>:null}
 <section className="stats"><article><span>低库存建议</span><b>{low.length}</b></article><article><span>待审批申请</span><b>{data.requests.filter(item=>item.status==="pending").length}</b></article><article><span>在途订单</span><b>{data.orders.filter(item=>["ordered","partially_received"].includes(item.status)).length}</b></article><article><span>已生成实体卷</span><b>{data.receipts.reduce((sum,item)=>sum+Number(item.spoolCount||0),0)}</b></article></section>
 <div className="grid"><section className="panel"><small>REPLENISHMENT</small><h2>低库存补货建议</h2>{low.length===0?<p className="empty">当前没有需要补货的耗材</p>:low.map(material=><article className="material" key={material.id}><div><b>{material.sku} · {material.material} / {material.color}</b><span>库存 {material.remainingGrams}g · 在途 {material.incomingGrams}g</span></div><strong>建议 {material.suggestedGrams}g</strong></article>)}
 {data.canReceive?<form onSubmit={request}><label>耗材<select name="batchId" required><option value="">选择低库存耗材</option>{low.map(material=><option key={material.id} value={material.id}>{material.sku} · 建议 {material.suggestedGrams}g</option>)}</select></label><label>申请克重<input name="grams" type="number" min="1" step="1" required/></label><label>补货原因<input name="reason" placeholder="低库存补货、生产计划需求…"/></label><button disabled={busy}>提交采购申请</button></form>:null}</section>
 <section className="panel"><small>APPROVAL QUEUE</small><h2>采购申请</h2>{data.requests.map(row=><article className="row" key={row.id}><div><b>{row.request_no}</b><span>{status[row.status]} · {Number(row.requestedGrams)}g</span></div>{data.canManage&&row.status==="pending"?<button disabled={busy} onClick={()=>void mutate("PATCH",{action:"approve",requestId:row.id})}>审批</button>:null}{data.canManage&&row.status==="approved"?<button disabled={busy||!data.suppliers.length} onClick={()=>void mutate("PATCH",{action:"order",requestId:row.id,supplierId:data.suppliers[0]?.id})}>向首选供应商下单</button>:null}</article>)}</section></div>
 <section className="panel orders"><small>PURCHASE ORDERS</small><h2>采购订单与逐卷收货</h2>{data.orders.map(order=><article className="order" key={order.id}><div className="order-head"><div><b>{order.purchase_no} · {order.supplierName}</b><span>{status[order.status]} · 已收 {Number(order.receivedGrams)} / {Number(order.orderedGrams)}g</span></div>{data.canManage&&["ordered","partially_received"].includes(order.status)?<button className="quiet" onClick={()=>void mutate("PATCH",{action:"cancel",orderId:order.id})}>取消订单</button>:null}</div>{(itemsByOrder.get(order.id)||[]).map(item=><div className="item" key={item.id}><span><i style={{background:item.colorHex?`#${item.colorHex}`:"#d9dfdc"}}/>{item.sku} · {item.material}/{item.color} · 未收 {item.orderedGrams-item.receivedGrams}g<small>{item.catalogItemId?`已关联 ${item.catalogCode}`:"未关联耗材主数据，不能生成实体卷"}</small></span>{data.canReceive&&["ordered","partially_received"].includes(order.status)&&item.receivedGrams<item.orderedGrams?<button disabled={busy||!item.catalogItemId} onClick={()=>setReceiving(item)}>逐卷登记收货</button>:null}</div>)}</article>)}</section>
 {data.canReceive?<section className="panel supplier"><small>SUPPLIER MASTER</small><h2>新增供应商</h2><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void mutate("POST",{action:"supplier",code:form.get("code"),name:form.get("name"),contact:form.get("contact")})}}><input name="code" required placeholder="供应商编码"/><input name="name" required placeholder="供应商名称"/><input name="contact" placeholder="联系人"/><button disabled={busy}>保存供应商</button></form></section>:null}
 {receiving?<div className="receive-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setReceiving(null)}><form className="receive-dialog" onSubmit={receive}><header><div><h2>逐卷登记收货</h2><p>{receiving.sku} · {receiving.material}/{receiving.color} · 剩余 {receiving.orderedGrams-receiving.receivedGrams}g</p></div><button type="button" onClick={()=>setReceiving(null)}>×</button></header><div><label>本次卷数<input name="spoolCount" type="number" min="1" max="100" defaultValue={Math.max(1,Math.floor((receiving.orderedGrams-receiving.receivedGrams)/Number(receiving.defaultNetGrams||1000)))} required/></label><label>单卷净重（g）<input name="perSpoolNetGrams" type="number" min="1" step="0.001" defaultValue={receiving.defaultNetGrams||1000} required/></label><label>空盘重量（g）<input name="tareGrams" type="number" min="0" step="0.001" defaultValue={receiving.defaultTareGrams||0}/></label><label>供应商批号<input name="lotNo" maxLength={80} placeholder="留空则自动生成"/></label></div><aside>确认后将同时生成采购批次、独立实体卷、入库流水和二维码标签。卷数 × 单卷净重不能超过未收数量。</aside><footer><button type="button" className="quiet" onClick={()=>setReceiving(null)}>取消</button><button disabled={busy}>确认收货并生成实体卷</button></footer></form></div>:null}
 {labels[labelIndex]?<SpoolLabel spool={labels[labelIndex]} onClose={()=>{if(labelIndex<labels.length-1)setLabelIndex(index=>index+1);else setLabels([])}}/>:null}
 </main>
}
