"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import SpoolLabel,{type LabelSpool} from "../inventory/spool-label";
import {supplierOfferCost} from "../../procurement/workflow";
type Material={id:number;catalogCode:string;material:string;color:string;colorHex:string;brand:string;defaultNetGrams:number;defaultTareGrams:number;onHandSpools:number;incomingSpools:number;reorderPointSpools:number;targetStockSpools:number;suggestedSpools:number};
type Supplier={id:number;code:string;name:string};type RequestRow={id:number;request_no:string;status:string;requestedGrams:number;requestedSpools:number;catalogItemId:number|null;created_at:string};
type Order={id:number;purchase_no:string;requestNo:string;supplierName:string;status:string;costStatus:string;subtotalCents:number;taxCents:number;freightCents:number;landedTotalCents:number;orderedGrams:number;receivedGrams:number;orderedSpools:number;receivedSpools:number};
type Item={id:number;orderId:number;sku:string;material:string;color:string;colorHex:string;catalogItemId:number|null;catalogCode:string|null;defaultNetGrams:number|null;defaultTareGrams:number|null;orderedGrams:number;receivedGrams:number;orderedSpools:number;receivedSpools:number;perSpoolNetGrams:number};
type Receipt={id:number;receipt_no:string;purchaseNo:string;received_by:string;received_at:string;spoolCount:number};
type Offer={id:number;supplierId:number;catalogItemId:number;unitPriceCentsPerSpool:number;taxRateBps:number;freightCentsPerOrder:number;minOrderSpools:number;leadTimeDays:number;validFrom:string;validUntil:string|null;status:string;supplierName:string;catalogCode:string;material:string;colorName:string};
type Data={canManage:boolean;canReceive:boolean;materials:Material[];suppliers:Supplier[];requests:RequestRow[];orders:Order[];orderItems:Item[];receipts:Receipt[];offers:Offer[]};
const status:Record<string,string>={draft:"草稿",pending:"待审批",approved:"已审批",ordered:"采购中",partially_received:"部分收货",completed:"已完成",cancelled:"已取消"};
const currencyFormatter=new Intl.NumberFormat("zh-CN",{style:"currency",currency:"MYR"});const money=(cents:number)=>currencyFormatter.format(Number(cents||0)/100);
export default function ProcurementClient(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[receiving,setReceiving]=useState<Item|null>(null),[labels,setLabels]=useState<LabelSpool[]>([]),[labelIndex,setLabelIndex]=useState(0);
 const load=useCallback(async()=>{const response=await fetch("/api/procurement",{cache:"no-store"}),value=await response.json();if(!response.ok)throw new Error(value.error);setData(value)},[]);useEffect(()=>{void load().catch(reason=>setError(reason.message))},[load]);
 async function mutate(method:"POST"|"PATCH",body:unknown){setBusy(true);setError("");try{const response=await fetch("/api/procurement",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)}),value=await response.json();if(!response.ok)throw new Error(value.error);await load();return value}catch(reason){setError(reason instanceof Error?reason.message:"操作失败")}finally{setBusy(false)}}
 const low=useMemo(()=>data?.materials.filter(item=>item.suggestedSpools>0)??[],[data]);
 const itemsByOrder=useMemo(()=>{const map=new Map<number,Item[]>();for(const item of data?.orderItems??[])map.set(item.orderId,[...(map.get(item.orderId)||[]),item]);return map},[data?.orderItems]);
 const bestOfferByRequest=useMemo(()=>{const map=new Map<number,Offer>(),today=new Date().toISOString().slice(0,10);for(const request of data?.requests??[]){if(!request.catalogItemId||!request.requestedSpools)continue;const eligible=(data?.offers??[]).filter(offer=>offer.catalogItemId===request.catalogItemId&&offer.status==="active"&&offer.validFrom<=today&&(!offer.validUntil||offer.validUntil>=today)&&request.requestedSpools>=offer.minOrderSpools);let best:Offer|undefined,bestTotal=Infinity;for(const offer of eligible){const total=supplierOfferCost(request.requestedSpools,offer.unitPriceCentsPerSpool,offer.taxRateBps,offer.freightCentsPerOrder).landedTotalCents;if(total<bestTotal){best=offer;bestTotal=total}}if(best)map.set(request.id,best)}return map},[data?.offers,data?.requests]);
 function request(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void mutate("POST",{action:"request",catalogItemId:Number(form.get("catalogItemId")),requestedSpools:Number(form.get("requestedSpools")),perSpoolNetGrams:Number(form.get("perSpoolNetGrams")),reason:form.get("reason")})}
 async function receive(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!receiving)return;const form=new FormData(event.currentTarget),result=await mutate("PATCH",{action:"receive",orderId:receiving.orderId,itemId:receiving.id,spoolCount:Number(form.get("spoolCount")),perSpoolNetGrams:Number(form.get("perSpoolNetGrams")),tareGrams:Number(form.get("tareGrams")),lotNo:form.get("lotNo"),idempotencyKey:crypto.randomUUID()});if(result?.spools){setLabels(result.spools);setLabelIndex(0);setReceiving(null)}}
 if(!data)return <main className="procurement-page"><p>{error||"正在加载采购中心…"}</p></main>;
 return <main className="procurement-page"><header><div><small>SUPPLY LOOP · SERIALIZED RECEIVING</small><h1>采购与补货中心</h1><p>从低库存建议、审批下单到逐卷收货和二维码标签，形成可审计闭环。</p></div><a href="/">返回工作台</a></header>{error?<div className="error">{error}</div>:null}
 <section className="stats"><article><span>低库存建议</span><b>{low.length}</b></article><article><span>待审批申请</span><b>{data.requests.filter(item=>item.status==="pending").length}</b></article><article><span>在途订单</span><b>{data.orders.filter(item=>["ordered","partially_received"].includes(item.status)).length}</b></article><article><span>已生成实体卷</span><b>{data.receipts.reduce((sum,item)=>sum+Number(item.spoolCount||0),0)}</b></article></section>
 <div className="grid"><section className="panel"><small>REPLENISHMENT</small><h2>按耗材主数据补货</h2>{low.length===0?<p className="empty">当前没有需要补货的耗材</p>:low.map(material=><article className="material" key={material.id}><i style={{background:material.colorHex?`#${material.colorHex}`:"#d9dfdc"}}/><div><b>{material.catalogCode} · {material.material} / {material.color}</b><span>可用 {material.onHandSpools} 卷 · 在途 {material.incomingSpools} 卷 · 目标 {material.targetStockSpools} 卷</span></div><strong>建议 {material.suggestedSpools} 卷</strong></article>)}
 {data.canReceive?<form onSubmit={request}><label>耗材主数据<select name="catalogItemId" required><option value="">选择需要补货的耗材</option>{data.materials.map(material=><option key={material.id} value={material.id}>{material.catalogCode} · {material.material}/{material.color} · 建议 {material.suggestedSpools} 卷</option>)}</select></label><label>采购卷数<input name="requestedSpools" type="number" min="1" max="1000" step="1" required/></label><label>单卷净重（g）<input name="perSpoolNetGrams" type="number" min="1" step="0.001" placeholder="留空使用主数据规格"/></label><label>补货原因<input name="reason" placeholder="低库存补货、生产计划需求…"/></label><button disabled={busy}>提交采购申请</button></form>:null}</section>
 <section className="panel"><small>APPROVAL QUEUE</small><h2>采购申请</h2>{data.requests.map(row=>{const offer=bestOfferByRequest.get(row.id),cost=offer?supplierOfferCost(row.requestedSpools,offer.unitPriceCentsPerSpool,offer.taxRateBps,offer.freightCentsPerOrder):null;return <article className="row" key={row.id}><div><b>{row.request_no}</b><span>{status[row.status]} · {Number(row.requestedSpools)>0?`${Number(row.requestedSpools)} 卷`:`历史申请 ${Number(row.requestedGrams)}g`}</span>{offer&&cost?<small>最优报价：{offer.supplierName} · 到岸 {money(cost.landedTotalCents)} · {offer.leadTimeDays} 天</small>:null}</div>{data.canManage&&row.status==="pending"?<button disabled={busy} onClick={()=>void mutate("PATCH",{action:"approve",requestId:row.id})}>审批</button>:null}{data.canManage&&row.status==="approved"?<button disabled={busy||(row.catalogItemId?!offer:!data.suppliers.length)} onClick={()=>void mutate("PATCH",{action:"order",requestId:row.id,offerId:offer?.id,supplierId:data.suppliers[0]?.id})}>{row.catalogItemId?offer?"按最优到岸成本下单":"缺少有效报价":"历史申请下单"}</button>:null}</article>})}</section></div>
 <section className="panel orders"><small>PURCHASE ORDERS</small><h2>采购订单、成本审批与逐卷收货</h2>{data.orders.map(order=><article className="order" key={order.id}><div className="order-head"><div><b>{order.purchase_no} · {order.supplierName}</b><span>{status[order.status]} · {Number(order.orderedSpools)>0?`已收 ${Number(order.receivedSpools)} / ${Number(order.orderedSpools)} 卷`:`已收 ${Number(order.receivedGrams)} / ${Number(order.orderedGrams)}g`}</span>{order.costStatus!=="legacy"?<small>到岸成本 {money(order.landedTotalCents)}（货款 {money(order.subtotalCents)}＋税 {money(order.taxCents)}＋运费 {money(order.freightCents)}）· {order.costStatus==="approved"?"成本已审批":"等待成本审批"}</small>:<small>历史订单成本</small>}</div><div className="order-actions">{data.canManage&&order.costStatus==="pending"?<button onClick={()=>void mutate("PATCH",{action:"approveCost",orderId:order.id})}>审批成本</button>:null}{data.canManage&&["ordered","partially_received"].includes(order.status)?<button className="quiet" onClick={()=>void mutate("PATCH",{action:"cancel",orderId:order.id})}>取消订单</button>:null}</div></div>{(itemsByOrder.get(order.id)||[]).map(item=><div className="item" key={item.id}><span><i style={{background:item.colorHex?`#${item.colorHex}`:"#d9dfdc"}}/>{item.sku} · {item.material}/{item.color} · {item.orderedSpools>0?`未收 ${item.orderedSpools-item.receivedSpools} 卷`:`未收 ${item.orderedGrams-item.receivedGrams}g`}<small>{item.catalogItemId?`已关联 ${item.catalogCode} · ${item.perSpoolNetGrams||item.defaultNetGrams}g/卷`:"历史采购未关联耗材主数据，不能生成实体卷"}</small></span>{data.canReceive&&["ordered","partially_received"].includes(order.status)&&item.receivedGrams<item.orderedGrams?<button disabled={busy||!item.catalogItemId||order.costStatus==="pending"} onClick={()=>setReceiving(item)}>{order.costStatus==="pending"?"等待成本审批":"逐卷登记收货"}</button>:null}</div>)}</article>)}</section>
 {data.canReceive?<section className="panel supplier"><small>SUPPLIER MASTER</small><h2>新增供应商</h2><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void mutate("POST",{action:"supplier",code:form.get("code"),name:form.get("name"),contact:form.get("contact")})}}><input name="code" required placeholder="供应商编码"/><input name="name" required placeholder="供应商名称"/><input name="contact" placeholder="联系人"/><button disabled={busy}>保存供应商</button></form></section>:null}
 {data.canManage?<section className="panel offer-panel"><small>SUPPLIER PRICE BOOK</small><h2>供应商报价档案</h2><div className="offer-list">{data.offers.map(offer=><article key={offer.id}><b>{offer.catalogCode} · {offer.supplierName}</b><span>{money(offer.unitPriceCentsPerSpool)}/卷 · 税率 {(offer.taxRateBps/100).toFixed(2)}% · 运费 {money(offer.freightCentsPerOrder)}</span><small>MOQ {offer.minOrderSpools} 卷 · 交期 {offer.leadTimeDays} 天 · {offer.validUntil||"长期有效"}</small></article>)}</div><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void mutate("POST",{action:"offer",supplierId:Number(form.get("supplierId")),catalogItemId:Number(form.get("catalogItemId")),unitPrice:Number(form.get("unitPrice")),taxRate:Number(form.get("taxRate")),freight:Number(form.get("freight")),minOrderSpools:Number(form.get("minOrderSpools")),leadTimeDays:Number(form.get("leadTimeDays")),validFrom:form.get("validFrom"),validUntil:form.get("validUntil")})}}><select name="supplierId" required><option value="">选择供应商</option>{data.suppliers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="catalogItemId" required><option value="">选择耗材</option>{data.materials.map(item=><option key={item.id} value={item.id}>{item.catalogCode} · {item.material}/{item.color}</option>)}</select><input name="unitPrice" type="number" min="0" step="0.01" required placeholder="含税前单价 RM/卷"/><input name="taxRate" type="number" min="0" max="100" step="0.01" defaultValue="0" placeholder="税率 %"/><input name="freight" type="number" min="0" step="0.01" defaultValue="0" placeholder="每单运费 RM"/><input name="minOrderSpools" type="number" min="1" defaultValue="1" placeholder="最小起订卷数"/><input name="leadTimeDays" type="number" min="0" defaultValue="0" placeholder="交期天数"/><input name="validFrom" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/><input name="validUntil" type="date"/><button disabled={busy}>保存报价</button></form></section>:null}
 {receiving?<div className="receive-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setReceiving(null)}><form className="receive-dialog" onSubmit={receive}><header><div><h2>逐卷登记收货</h2><p>{receiving.sku} · {receiving.material}/{receiving.color} · {receiving.orderedSpools>0?`剩余 ${receiving.orderedSpools-receiving.receivedSpools} 卷`:`历史订单剩余 ${receiving.orderedGrams-receiving.receivedGrams}g`}</p></div><button type="button" onClick={()=>setReceiving(null)}>×</button></header><div><label>本次卷数<input name="spoolCount" type="number" min="1" max={Math.min(100,receiving.orderedSpools>0?receiving.orderedSpools-receiving.receivedSpools:100)} defaultValue={receiving.orderedSpools>0?Math.min(100,receiving.orderedSpools-receiving.receivedSpools):Math.max(1,Math.floor((receiving.orderedGrams-receiving.receivedGrams)/Number(receiving.defaultNetGrams||1000)))} required/></label><label>单卷净重（g）<input name="perSpoolNetGrams" type="number" min="1" step="0.001" defaultValue={receiving.perSpoolNetGrams||receiving.defaultNetGrams||1000} required/></label><label>空盘重量（g）<input name="tareGrams" type="number" min="0" step="0.001" defaultValue={receiving.defaultTareGrams||0}/></label><label>供应商批号<input name="lotNo" maxLength={80} placeholder="留空则自动生成"/></label></div><aside>确认后将同时生成采购批次、独立实体卷、入库流水和二维码标签。卷数与总净重均不得超过订单未收数量。</aside><footer><button type="button" className="quiet" onClick={()=>setReceiving(null)}>取消</button><button disabled={busy}>确认收货并生成实体卷</button></footer></form></div>:null}
 {labels[labelIndex]?<SpoolLabel spool={labels[labelIndex]} onClose={()=>{if(labelIndex<labels.length-1)setLabelIndex(index=>index+1);else setLabels([])}}/>:null}
 </main>
}
