"use client";

import { useCallback, useEffect, useState } from "react";
import stylesBase from "./settlements.module.css";
import evidence from "./settlement-evidence.module.css";

const styles={...stylesBase,...evidence};

type Candidate={id:number;printerId:number;fingerprint:string;filename:string;estimatedGrams:number;filaments:number[]};
type QueueRow={sessionId:number;printerId:number;printerName:string;filename:string;status:string;startedAt?:string;lastObservedAt:string;matchState:"unique_exact"|"ambiguous"|"none";suggestedFingerprint?:string|null;candidates:Candidate[]};
type Job={id:number;jobNo:string;printerId:number|null;quantity:number;status:string;orderNo?:string;sku?:string;itemName?:string};
type Feed={id:number;printerId:number;label:string;feedKind:string;toolhead:string;spoolId:number|null;spoolCode?:string;remainingGrams?:number;material?:string;colorName?:string;colorHex?:string};
type Breakdown={purpose:string;toolhead:string;estimatedGrams:number;settledGrams:number;measuredGrams:number;costCents:number;pendingLines:number};
type UsageLine={id:number;spoolId:number|null;spoolCode?:string;toolhead:string;purpose:string;plate:number|null;filament:number;totalLayers:number;estimatedGrams:number;settledGrams:number|null;measuredGrams:number|null;costCents:number;settledAt?:string|null;pendingReason?:string|null};
type Session={sessionId:number;filename:string;status:string;printerName?:string;jobNo?:string;orderNo?:string;itemName?:string;estimatedGrams:number;settledGrams:number;materialCostCents:number;pendingLines:number;breakdown:Breakdown[];lines:UsageLine[]};
type Calibration={printerId:number;printerName:string;material:string;purpose:string;sampleCount:number;estimatedGrams:number;measuredGrams:number;meanAbsoluteError:number;factor:number;recommendedFactor:number|null;confidence:"collecting"|"initial"|"stable"};
type Payload={workQueue:QueueRow[];jobs:Job[];feeds:Feed[];sessions:Session[];calibration:Calibration[]};
type Selection={fingerprint?:string;jobId?:string;feeds:Record<string,string>};
const empty:Payload={workQueue:[],jobs:[],feeds:[],sessions:[],calibration:[]};
const purpose:Record<string,string>={model:"主体",support:"支撑",support_interface:"支撑界面",purge:"冲刷/屎料",wipe_tower:"擦拭塔",brim:"裙边",calibration:"校准",unknown:"待分类"};
const money=(cents:number)=>`RM ${(Number(cents||0)/100).toFixed(2)}`;

export default function SettlementClient({canEdit}:{canEdit:boolean}){
 const[data,setData]=useState<Payload>(empty),[selections,setSelections]=useState<Record<number,Selection>>({}),[measurements,setMeasurements]=useState<Record<number,string>>({}),[layers,setLayers]=useState<Record<string,string>>({}),[message,setMessage]=useState(""),[saving,setSaving]=useState(0);
 const load=useCallback(async()=>{const response=await fetch("/api/cost-settlement",{cache:"no-store"}),body=await response.json() as Payload&{error?:string};if(!response.ok)throw new Error(body.error||"读取归集任务失败");setData(body)},[]);
 useEffect(()=>{void load().catch(error=>setMessage(error.message))},[load]);
 function selection(row:QueueRow){const current=selections[row.sessionId]||{feeds:{}};return {...current,fingerprint:current.fingerprint||row.suggestedFingerprint||undefined}}
 function patch(row:QueueRow,value:Partial<Selection>){setSelections(current=>({...current,[row.sessionId]:{...selection(row),...current[row.sessionId],...value,feeds:value.feeds||current[row.sessionId]?.feeds||{}}}))}
 async function reserve(row:QueueRow){const chosen=selection(row),candidate=row.candidates.find(item=>item.fingerprint===chosen.fingerprint);if(!candidate)return setMessage("请先确认对应的切片记录");const mappings=candidate.filaments.flatMap(filament=>chosen.feeds[String(filament)]?[{filament,feedPositionId:Number(chosen.feeds[String(filament)])}]:[]);setSaving(row.sessionId);const response=await fetch("/api/cost-settlement",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"reserve",sessionId:row.sessionId,fingerprint:candidate.fingerprint,jobId:Number(chosen.jobId||0)||null,feedPositionByFilament:mappings})}),body=await response.json() as{error?:string;pendingBindings?:number};setMessage(response.ok?body.pendingBindings?`已关联，但仍有 ${body.pendingBindings} 条用量未绑定实体卷。`:"打印会话、任务和实体耗材已确认关联。":body.error||"关联失败");setSaving(0);if(response.ok)await load()}
 async function measure(session:Session,line:UsageLine){const value=Number(measurements[line.id]);if(!Number.isFinite(value)||value<0)return setMessage("请输入有效的称重克数");setSaving(line.id);const response=await fetch("/api/cost-settlement",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"measure",sessionId:session.sessionId,usageLineId:line.id,measuredGrams:value})}),body=await response.json() as{error?:string};setMessage(response.ok?"称重结果已保存，将优先于切片估算用于结算。":body.error||"称重保存失败");setSaving(0);if(response.ok)await load()}
 async function settle(session:Session){const outcome=session.status==="failed"?"failed":session.status==="cancelled"?"cancelled":"completed",lastLayerByPlate=Object.fromEntries([...new Set(session.lines.map(line=>line.plate).filter(value=>value!=null))].flatMap(plate=>layers[`${session.sessionId}:${plate}`]!==undefined?[[String(plate),Number(layers[`${session.sessionId}:${plate}`])]]:[]));setSaving(session.sessionId);const response=await fetch("/api/cost-settlement",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"settle",sessionId:session.sessionId,outcome,lastLayerByPlate})}),body=await response.json() as{error?:string;pendingLines?:number};setMessage(response.ok?body.pendingLines?`已结算有证据的部分，仍有 ${body.pendingLines} 条待处理。`:"耗材扣减与订单材料成本已完成归集。":body.error||"结算失败");setSaving(0);if(response.ok)await load()}
 return <main className={styles.page}><header><a href="/costing">← 成本与定价</a>　<a href="/calibration">现场称重校准 →</a><small>PRINT SESSION · MATERIAL SETTLEMENT</small><h1>打印会话与耗材归集</h1><p>Bambu Studio 继续负责打印；这里仅确认实时会话、切片分类、生产任务和实际供料卷。</p></header>
  <section className={styles.guard}><b>三条防错边界</b><span>文件名只用于推荐，不自动认领</span><span>未绑定实体卷不扣库存</span><span>未知用途和失败层数不猜测</span></section>
  {message?<div className={styles.message}>{message}<button onClick={()=>setMessage("")}>×</button></div>:null}
  <section className={styles.metrics}><div><b>{data.workQueue.length}</b><span>待归集会话</span></div><div><b>{data.workQueue.filter(x=>x.matchState==="unique_exact").length}</b><span>唯一切片建议</span></div><div><b>{data.sessions.filter(x=>x.pendingLines>0).length}</b><span>待结算记录</span></div><div><b>{money(data.sessions.reduce((sum,x)=>sum+x.materialCostCents,0))}</b><span>已归集材料成本</span></div></section>
  <section className={styles.panel}><div className={styles.title}><div><small>STEP 1</small><h2>确认实时打印会话</h2><p>系统只推荐同一打印机、文件名完全一致的切片记录；必须由人员确认。</p></div></div>
   <div className={styles.queue}>{data.workQueue.map(row=>{const chosen=selection(row),candidate=row.candidates.find(item=>item.fingerprint===chosen.fingerprint),feeds=data.feeds.filter(feed=>feed.printerId===row.printerId&&feed.spoolId),jobs=data.jobs.filter(job=>!job.printerId||job.printerId===row.printerId);return <article key={row.sessionId}><div className={styles.sessionHead}><span><b>{row.filename||"未命名打印"}</b><small>{row.printerName} · {new Date(row.startedAt||row.lastObservedAt).toLocaleString("zh-CN")}</small></span><em className={styles[row.matchState]}>{row.matchState==="unique_exact"?"唯一匹配建议":row.matchState==="ambiguous"?"多个同名切片":"无切片建议"}</em></div>
    <div className={styles.form}><label>切片分类记录<select value={chosen.fingerprint||""} onChange={event=>patch(row,{fingerprint:event.target.value,feeds:{}})}><option value="">请选择并确认</option>{row.candidates.map(item=><option key={item.fingerprint} value={item.fingerprint}>{item.filename} · {item.estimatedGrams.toFixed(1)}g · {item.fingerprint.slice(0,8)}</option>)}</select></label><label>生产任务 / 订单<select value={chosen.jobId||""} onChange={event=>patch(row,{jobId:event.target.value})}><option value="">暂不关联任务</option>{jobs.map(job=><option key={job.id} value={job.id}>{job.jobNo} · {job.itemName||job.sku||"未关联产品"} · {job.orderNo||"无订单"}</option>)}</select></label></div>
    {candidate?<div className={styles.feeds}>{candidate.filaments.map(filament=><label key={filament}><span>耗材通道 {filament}</span><select value={chosen.feeds[String(filament)]||""} onChange={event=>patch(row,{feeds:{...chosen.feeds,[String(filament)]:event.target.value}})}><option value="">不猜测，等待绑定</option>{feeds.map(feed=><option key={feed.id} value={feed.id}>{feed.label} · {feed.spoolCode} · {feed.material||"未知材质"} {feed.colorName||""} · {Number(feed.remainingGrams||0).toFixed(0)}g</option>)}</select></label>)}</div>:null}
    {canEdit?<button className={styles.primary} disabled={saving===row.sessionId||!candidate} onClick={()=>void reserve(row)}>{saving===row.sessionId?"正在确认…":"确认关联并建立用量预留"}</button>:null}</article>})}{!data.workQueue.length?<p className={styles.empty}>当前没有等待归集的实时打印会话。</p>:null}</div>
  </section>
  <section className={styles.panel}><div className={styles.title}><div><small>STEP 2</small><h2>失败证据、称重与分类结算</h2><p>完成任务使用完整切片量；失败或取消任务必须填写最后完成层，称重结果可覆盖单项估算。</p></div></div><div className={styles.results}>{data.sessions.map(session=>{const plates=[...new Set(session.lines.map(line=>line.plate).filter((value):value is number=>value!=null))],isFailure=["failed","cancelled"].includes(session.status),needsLayer=plates.filter(plate=>session.lines.some(line=>line.plate===plate&&!line.settledAt&&line.measuredGrams==null)),evidenceComplete=!isFailure||needsLayer.every(plate=>layers[`${session.sessionId}:${plate}`]!==undefined);return <article key={session.sessionId}><div className={styles.resultHead}><span><b>{session.filename}</b><small>{session.jobNo||"未关联任务"} · {session.orderNo||"无订单"} · {session.itemName||"未关联产品"}</small></span><strong>{money(session.materialCostCents)}</strong></div>
   {isFailure?<div className={styles.layers}><b>{session.status==="failed"?"失败打印":"取消打印"}的层数证据</b>{needsLayer.map(plate=>{const total=session.lines.find(line=>line.plate===plate)?.totalLayers||0;return <label key={plate}>打印板 {plate}<input type="number" min="0" max={Math.max(0,total-1)} value={layers[`${session.sessionId}:${plate}`]||""} onChange={event=>setLayers(current=>({...current,[`${session.sessionId}:${plate}`]:event.target.value}))} placeholder={`最后完成层 / 共 ${total} 层`}/></label>})}{!needsLayer.length?<span>所有未结算项目均已有称重证据。</span>:null}</div>:null}
   <div className={styles.usageLines}>{session.lines.map(line=>{const actual=line.measuredGrams??line.settledGrams,variance=actual==null?null:actual-line.estimatedGrams;return <div key={line.id}><span><i style={{background:line.spoolId?"#35bc83":"#e3a638"}}/><b>{purpose[line.purpose]||line.purpose}</b><small>板 {line.plate??"—"} · {line.toolhead} · {line.spoolCode||"未绑定实体卷"}</small></span><span><small>预计 / 实际 / 偏差</small><b>{line.estimatedGrams.toFixed(1)} / {actual==null?"—":actual.toFixed(1)} / {variance==null?"—":`${variance>=0?"+":""}${variance.toFixed(1)}`} g</b></span>{canEdit&&!line.settledAt?<label><input type="number" min="0" step="0.1" value={measurements[line.id]??(line.measuredGrams?.toString()||"")} onChange={event=>setMeasurements(current=>({...current,[line.id]:event.target.value}))} placeholder="称重克数"/><button disabled={saving===line.id} onClick={()=>void measure(session,line)}>保存称重</button></label>:<em className={line.settledAt?styles.done:styles.pending}>{line.settledAt?"已结算":line.pendingReason==="spool_unbound"?"实体卷未绑定":line.pendingReason==="purpose_unknown"?"用途待分类":"待结算"}</em>}</div>})}</div>
   <div className={styles.breakdown}>{session.breakdown.map((line,index)=><div key={`${line.purpose}-${line.toolhead}-${index}`}><span>{purpose[line.purpose]||line.purpose}<small>{line.toolhead}</small></span><b>{line.settledGrams.toFixed(1)} / {line.estimatedGrams.toFixed(1)} g</b><em className={line.pendingLines?styles.pending:styles.done}>{line.pendingLines?`${line.pendingLines} 条待处理`:"已确认"}</em></div>)}</div><footer><span>预计 {session.estimatedGrams.toFixed(1)}g · 已结算 {session.settledGrams.toFixed(1)}g</span>{canEdit&&["completed","failed","cancelled"].includes(session.status)&&session.pendingLines>0?<button disabled={saving===session.sessionId||!evidenceComplete} onClick={()=>void settle(session)}>{!evidenceComplete?"请补齐最后完成层":isFailure?"按失败证据结算":"按完成数据结算"}</button>:null}</footer></article>})}{!data.sessions.length?<p className={styles.empty}>尚无已建立用量分类的打印会话。</p>:null}</div></section>
  <section className={styles.panel}><div className={styles.title}><div><small>STEP 3</small><h2>称重校准样本</h2><p>只统计已结算且有实际称重的记录；少于 3 个样本不生成系数，任何建议都不会自动修改库存或成本。</p></div></div><div className={styles.calibration}>{data.calibration.map(row=><article key={`${row.printerId}-${row.material}-${row.purpose}`}><header><span><b>{row.printerName}</b><small>{row.material} · {purpose[row.purpose]||row.purpose}</small></span><em data-confidence={row.confidence}>{row.confidence==="stable"?"稳定样本":row.confidence==="initial"?"初步建议":"继续采样"}</em></header><strong>{row.recommendedFactor==null?"—":`× ${row.recommendedFactor.toFixed(3)}`}</strong><span>建议估算修正系数</span><footer><small>{row.sampleCount} 个称重样本</small><small>预计 {row.estimatedGrams.toFixed(1)}g / 实际 {row.measuredGrams.toFixed(1)}g</small><small>平均绝对偏差 {row.meanAbsoluteError.toFixed(1)}g</small></footer></article>)}{!data.calibration.length?<p className={styles.empty}>尚无有效称重样本。完成打印后录入实际称重，即会在这里形成校准数据。</p>:null}</div></section>
 </main>
}
