"use client";

import { useCallback, useEffect, useState } from "react";
import styles from "./settlements.module.css";

type Candidate={id:number;printerId:number;fingerprint:string;filename:string;estimatedGrams:number;filaments:number[]};
type QueueRow={sessionId:number;printerId:number;printerName:string;filename:string;status:string;startedAt?:string;lastObservedAt:string;matchState:"unique_exact"|"ambiguous"|"none";suggestedFingerprint?:string|null;candidates:Candidate[]};
type Job={id:number;jobNo:string;printerId:number|null;quantity:number;status:string;orderNo?:string;sku?:string;itemName?:string};
type Feed={id:number;printerId:number;label:string;feedKind:string;toolhead:string;spoolId:number|null;spoolCode?:string;remainingGrams?:number;material?:string;colorName?:string;colorHex?:string};
type Breakdown={purpose:string;toolhead:string;estimatedGrams:number;settledGrams:number;measuredGrams:number;costCents:number;pendingLines:number};
type Session={sessionId:number;filename:string;status:string;printerName?:string;jobNo?:string;orderNo?:string;itemName?:string;estimatedGrams:number;settledGrams:number;materialCostCents:number;pendingLines:number;breakdown:Breakdown[]};
type Payload={workQueue:QueueRow[];jobs:Job[];feeds:Feed[];sessions:Session[]};
type Selection={fingerprint?:string;jobId?:string;feeds:Record<string,string>};
const empty:Payload={workQueue:[],jobs:[],feeds:[],sessions:[]};
const purpose:Record<string,string>={model:"主体",support:"支撑",support_interface:"支撑界面",purge:"冲刷/屎料",wipe_tower:"擦拭塔",brim:"裙边",calibration:"校准",unknown:"待分类"};
const money=(cents:number)=>`RM ${(Number(cents||0)/100).toFixed(2)}`;

export default function SettlementClient({canEdit}:{canEdit:boolean}){
 const[data,setData]=useState<Payload>(empty),[selections,setSelections]=useState<Record<number,Selection>>({}),[message,setMessage]=useState(""),[saving,setSaving]=useState(0);
 const load=useCallback(async()=>{const response=await fetch("/api/cost-settlement",{cache:"no-store"}),body=await response.json() as Payload&{error?:string};if(!response.ok)throw new Error(body.error||"读取归集任务失败");setData(body)},[]);
 useEffect(()=>{void load().catch(error=>setMessage(error.message))},[load]);
 function selection(row:QueueRow){const current=selections[row.sessionId]||{feeds:{}};return {...current,fingerprint:current.fingerprint||row.suggestedFingerprint||undefined}}
 function patch(row:QueueRow,value:Partial<Selection>){setSelections(current=>({...current,[row.sessionId]:{...selection(row),...current[row.sessionId],...value,feeds:value.feeds||current[row.sessionId]?.feeds||{}}}))}
 async function reserve(row:QueueRow){const chosen=selection(row),candidate=row.candidates.find(item=>item.fingerprint===chosen.fingerprint);if(!candidate)return setMessage("请先确认对应的切片记录");const mappings=candidate.filaments.flatMap(filament=>chosen.feeds[String(filament)]?[{filament,feedPositionId:Number(chosen.feeds[String(filament)])}]:[]);setSaving(row.sessionId);const response=await fetch("/api/cost-settlement",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"reserve",sessionId:row.sessionId,fingerprint:candidate.fingerprint,jobId:Number(chosen.jobId||0)||null,feedPositionByFilament:mappings})}),body=await response.json() as{error?:string;pendingBindings?:number};setMessage(response.ok?body.pendingBindings?`已关联，但仍有 ${body.pendingBindings} 条用量未绑定实体卷。`:"打印会话、任务和实体耗材已确认关联。":body.error||"关联失败");setSaving(0);if(response.ok)await load()}
 async function settle(session:Session){setSaving(session.sessionId);const response=await fetch("/api/cost-settlement",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"settle",sessionId:session.sessionId,outcome:"completed",lastLayerByPlate:{}})}),body=await response.json() as{error?:string;pendingLines?:number};setMessage(response.ok?body.pendingLines?`已结算可确认部分，仍有 ${body.pendingLines} 条待处理。`:"耗材扣减与订单材料成本已完成归集。":body.error||"结算失败");setSaving(0);if(response.ok)await load()}
 return <main className={styles.page}><header><a href="/costing">← 成本与定价</a><small>PRINT SESSION · MATERIAL SETTLEMENT</small><h1>打印会话与耗材归集</h1><p>Bambu Studio 继续负责打印；这里仅确认实时会话、切片分类、生产任务和实际供料卷。</p></header>
  <section className={styles.guard}><b>三条防错边界</b><span>文件名只用于推荐，不自动认领</span><span>未绑定实体卷不扣库存</span><span>未知用途和失败层数不猜测</span></section>
  {message?<div className={styles.message}>{message}<button onClick={()=>setMessage("")}>×</button></div>:null}
  <section className={styles.metrics}><div><b>{data.workQueue.length}</b><span>待归集会话</span></div><div><b>{data.workQueue.filter(x=>x.matchState==="unique_exact").length}</b><span>唯一切片建议</span></div><div><b>{data.sessions.filter(x=>x.pendingLines>0).length}</b><span>待结算记录</span></div><div><b>{money(data.sessions.reduce((sum,x)=>sum+x.materialCostCents,0))}</b><span>已归集材料成本</span></div></section>
  <section className={styles.panel}><div className={styles.title}><div><small>STEP 1</small><h2>确认实时打印会话</h2><p>系统只推荐同一打印机、文件名完全一致的切片记录；必须由人员确认。</p></div></div>
   <div className={styles.queue}>{data.workQueue.map(row=>{const chosen=selection(row),candidate=row.candidates.find(item=>item.fingerprint===chosen.fingerprint),feeds=data.feeds.filter(feed=>feed.printerId===row.printerId&&feed.spoolId),jobs=data.jobs.filter(job=>!job.printerId||job.printerId===row.printerId);return <article key={row.sessionId}><div className={styles.sessionHead}><span><b>{row.filename||"未命名打印"}</b><small>{row.printerName} · {new Date(row.startedAt||row.lastObservedAt).toLocaleString("zh-CN")}</small></span><em className={styles[row.matchState]}>{row.matchState==="unique_exact"?"唯一匹配建议":row.matchState==="ambiguous"?"多个同名切片":"无切片建议"}</em></div>
    <div className={styles.form}><label>切片分类记录<select value={chosen.fingerprint||""} onChange={event=>patch(row,{fingerprint:event.target.value,feeds:{}})}><option value="">请选择并确认</option>{row.candidates.map(item=><option key={item.fingerprint} value={item.fingerprint}>{item.filename} · {item.estimatedGrams.toFixed(1)}g · {item.fingerprint.slice(0,8)}</option>)}</select></label><label>生产任务 / 订单<select value={chosen.jobId||""} onChange={event=>patch(row,{jobId:event.target.value})}><option value="">暂不关联任务</option>{jobs.map(job=><option key={job.id} value={job.id}>{job.jobNo} · {job.itemName||job.sku||"未关联产品"} · {job.orderNo||"无订单"}</option>)}</select></label></div>
    {candidate?<div className={styles.feeds}>{candidate.filaments.map(filament=><label key={filament}><span>耗材通道 {filament}</span><select value={chosen.feeds[String(filament)]||""} onChange={event=>patch(row,{feeds:{...chosen.feeds,[String(filament)]:event.target.value}})}><option value="">不猜测，等待绑定</option>{feeds.map(feed=><option key={feed.id} value={feed.id}>{feed.label} · {feed.spoolCode} · {feed.material||"未知材质"} {feed.colorName||""} · {Number(feed.remainingGrams||0).toFixed(0)}g</option>)}</select></label>)}</div>:null}
    {canEdit?<button className={styles.primary} disabled={saving===row.sessionId||!candidate} onClick={()=>void reserve(row)}>{saving===row.sessionId?"正在确认…":"确认关联并建立用量预留"}</button>:null}</article>})}{!data.workQueue.length?<p className={styles.empty}>当前没有等待归集的实时打印会话。</p>:null}</div>
  </section>
  <section className={styles.panel}><div className={styles.title}><div><small>STEP 2</small><h2>分类耗材成本与结算</h2><p>主体、支撑、冲刷和辅助结构分别记录；只有实体卷明确且打印完成才可正式扣减。</p></div></div><div className={styles.results}>{data.sessions.map(session=><article key={session.sessionId}><div className={styles.resultHead}><span><b>{session.filename}</b><small>{session.jobNo||"未关联任务"} · {session.orderNo||"无订单"} · {session.itemName||"未关联产品"}</small></span><strong>{money(session.materialCostCents)}</strong></div><div className={styles.breakdown}>{session.breakdown.map((line,index)=><div key={`${line.purpose}-${line.toolhead}-${index}`}><span>{purpose[line.purpose]||line.purpose}<small>{line.toolhead}</small></span><b>{line.settledGrams.toFixed(1)} / {line.estimatedGrams.toFixed(1)} g</b><em className={line.pendingLines?styles.pending:styles.done}>{line.pendingLines?`${line.pendingLines} 条待处理`:"已确认"}</em></div>)}</div><footer><span>预计 {session.estimatedGrams.toFixed(1)}g · 已结算 {session.settledGrams.toFixed(1)}g</span>{canEdit&&session.status==="completed"&&session.pendingLines>0?<button disabled={saving===session.sessionId} onClick={()=>void settle(session)}>按完成数据结算</button>:null}</footer></article>)}{!data.sessions.length?<p className={styles.empty}>尚无已建立用量分类的打印会话。</p>:null}</div></section>
 </main>
}
