import { env } from "cloudflare:workers";
import { headers } from "next/headers";
import { getD1 } from "../db";
import { getChatGPTUser } from "./chatgpt-auth";
export const ROLES=["owner","manager","orders","operator","warehouse","finance","viewer"] as const; export type Role=typeof ROLES[number]; export type Permission="read"|"write"|"team.manage"|"printers.control"|"inventory.write"|"finance.read";
const grants:Record<Role,Permission[]>={owner:["read","write","team.manage","printers.control","inventory.write","finance.read"],manager:["read","write","printers.control","inventory.write","finance.read"],orders:["read","write"],operator:["read","printers.control"],warehouse:["read","inventory.write"],finance:["read","finance.read"],viewer:["read"]};
export type AccessContext={email:string;displayName:string;organizationId:number;role:Role;printerScope:number[]};
async function ensureSchema(){const d=getD1();await d.batch([d.prepare("CREATE TABLE IF NOT EXISTS organizations (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),d.prepare("CREATE TABLE IF NOT EXISTS organization_members (id INTEGER PRIMARY KEY AUTOINCREMENT,organization_id INTEGER NOT NULL,email TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL DEFAULT '',role TEXT NOT NULL DEFAULT 'operator',status TEXT NOT NULL DEFAULT 'invited',printer_scope TEXT NOT NULL DEFAULT '[]',invited_by TEXT NOT NULL DEFAULT '',last_login_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),d.prepare("CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT,organization_id INTEGER NOT NULL,actor_email TEXT NOT NULL,action TEXT NOT NULL,resource TEXT NOT NULL DEFAULT 'system',resource_id TEXT NOT NULL DEFAULT '',detail TEXT NOT NULL DEFAULT '{}',ip_address TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),d.prepare("CREATE INDEX IF NOT EXISTS audit_logs_org_created_idx ON audit_logs(organization_id,created_at DESC)")]);}
export async function getAccessContext():Promise<AccessContext|null>{const u=await getChatGPTUser();if(!u)return null;await ensureSchema();const d=getD1(),email=u.email.trim().toLowerCase();const owners=((env as unknown as {ADMIN_EMAILS?:string}).ADMIN_EMAILS??"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);let m=await d.prepare("SELECT organization_id,role,status,printer_scope FROM organization_members WHERE lower(email)=?").bind(email).first<{organization_id:number;role:Role;status:string;printer_scope:string}>();if(!m&&owners.includes(email)){await d.prepare("INSERT OR IGNORE INTO organizations(name,slug) VALUES(?,?)").bind("LayerTrace 3D 打印工作室","layertrace").run();const o=await d.prepare("SELECT id FROM organizations WHERE slug='layertrace'").first<{id:number}>();if(o)await d.prepare("INSERT INTO organization_members(organization_id,email,display_name,role,status,invited_by) VALUES(?,?,?,?,?,?)").bind(o.id,email,u.displayName,"owner","active",email).run();m=await d.prepare("SELECT organization_id,role,status,printer_scope FROM organization_members WHERE lower(email)=?").bind(email).first();}if(!m||!["active","invited"].includes(m.status))return null;await d.prepare("UPDATE organization_members SET status='active',display_name=?,last_login_at=CURRENT_TIMESTAMP WHERE lower(email)=?").bind(u.displayName,email).run();let scope:number[]=[];try{scope=JSON.parse(m.printer_scope||"[]")}catch{}return{email,displayName:u.displayName,organizationId:m.organization_id,role:m.role,printerScope:scope};}
export function can(c:AccessContext,p:Permission){return grants[c.role]?.includes(p)??false} export async function recordAudit(c:AccessContext,action:string,resource="system",resourceId="",detail:Record<string,unknown>={}){const h=await headers();await getD1().prepare("INSERT INTO audit_logs(organization_id,actor_email,action,resource,resource_id,detail,ip_address) VALUES(?,?,?,?,?,?,?)").bind(c.organizationId,c.email,action,resource,resourceId,JSON.stringify(detail),h.get("cf-connecting-ip")||"").run()}
