import { and, asc, eq } from "drizzle-orm";
import { getDb, getFilesBucket } from "../../../db";
import { bambuAmsSlots, printFiles, printerCommands, printers, spoolmanSpools } from "../../../db/schema";

async function sha256(value:string){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,"0")).join("");}

async function authenticate(request:Request){const authorization=request.headers.get("authorization")||"";const token=authorization.startsWith("Bearer ")?authorization.slice(7):"";if(!token)return null;const [printer]=await getDb().select().from(printers).where(eq(printers.connectorTokenHash,await sha256(token))).limit(1);return printer||null;}

export async function GET(request:Request){try{const printer=await authenticate(request);if(!printer)return Response.json({error:"代理令牌无效"},{status:401});const url=new URL(request.url);const fileId=Number(url.searchParams.get("file"));const commandId=Number(url.searchParams.get("command"));if(!fileId||!commandId)return Response.json({error:"缺少文件或命令标识"},{status:400});const [command]=await getDb().select().from(printerCommands).where(and(eq(printerCommands.id,commandId),eq(printerCommands.printerId,printer.id),eq(printerCommands.status,"待执行"))).limit(1);if(!command||command.command!=="start"||JSON.parse(command.payload).fileId!==fileId)return Response.json({error:"文件领取权限无效"},{status:403});const [file]=await getDb().select().from(printFiles).where(eq(printFiles.id,fileId)).limit(1);const allowed=printer.connectorType==="bambu_lan"?["3MF","G-code"]:["G-code"];if(!file||!allowed.includes(file.kind))return Response.json({error:"该打印机不支持此文件类型"},{status:404});const object=await getFilesBucket().get(file.objectKey);if(!object)return Response.json({error:"文件内容不存在"},{status:404});return new Response(object.body,{headers:{"Content-Type":"application/octet-stream","Content-Disposition":`attachment; filename*=UTF-8''${encodeURIComponent(file.filename)}`,"Content-Length":String(file.sizeBytes)}});}catch(error){return Response.json({error:error instanceof Error?error.message:"代理下载失败"},{status:500});}}

export async function POST(request:Request){
  try{
    const printer=await authenticate(request);
    if(!printer)return Response.json({error:"代理令牌无效"},{status:401});
    const body=await request.json() as {state?:string;nozzleTemp?:number;bedTemp?:number;filename?:string;progress?:number;totalHours?:number;ack?:{id:number;ok:boolean;result?:string};ams?:Array<{unit:number;tray:number;material?:string;colorHex?:string;remainingPercent?:number|null;tagUid?:string;active?:boolean}>;spools?:Array<{id:number;filamentName?:string;vendor?:string;material?:string;colorHex?:string;initialWeight?:number|null;remainingWeight?:number|null;usedWeight?:number|null;location?:string;lotNr?:string;archived?:boolean;lastUsed?:string|null}>};
    const state=body.state||"在线";
    const mappedStatus=state==="printing"?"打印中":state==="paused"?"已暂停":state==="error"?"故障":printer.status;
    const [row]=await getDb().update(printers).set({connectionState:state,status:mappedStatus,lastSeenAt:new Date().toISOString(),nozzleTemp:Number.isFinite(body.nozzleTemp)?body.nozzleTemp:null,bedTemp:Number.isFinite(body.bedTemp)?body.bedTemp:null,currentFile:body.filename||null,remoteProgress:Number.isFinite(body.progress)?body.progress:null,totalHours:Number.isFinite(body.totalHours)?body.totalHours:printer.totalHours}).where(eq(printers.id,printer.id)).returning();
    if(body.ack?.id){await getDb().update(printerCommands).set({status:body.ack.ok?"已完成":"失败",result:body.ack.result||"",completedAt:new Date().toISOString()}).where(eq(printerCommands.id,body.ack.id));}
    if(Array.isArray(body.spools)){for(const spool of body.spools.slice(0,500)){if(!Number.isInteger(spool.id))continue;await getDb().insert(spoolmanSpools).values({externalId:spool.id,filamentName:spool.filamentName||"",vendor:spool.vendor||"",material:spool.material||"",colorHex:spool.colorHex||"",initialWeight:spool.initialWeight,remainingWeight:spool.remainingWeight,usedWeight:spool.usedWeight,location:spool.location||"",lotNr:spool.lotNr||"",archived:Boolean(spool.archived),lastUsed:spool.lastUsed||null,syncedByPrinterId:printer.id,lastSeenAt:new Date().toISOString()}).onConflictDoUpdate({target:spoolmanSpools.externalId,set:{filamentName:spool.filamentName||"",vendor:spool.vendor||"",material:spool.material||"",colorHex:spool.colorHex||"",initialWeight:spool.initialWeight,remainingWeight:spool.remainingWeight,usedWeight:spool.usedWeight,location:spool.location||"",lotNr:spool.lotNr||"",archived:Boolean(spool.archived),lastUsed:spool.lastUsed||null,syncedByPrinterId:printer.id,lastSeenAt:new Date().toISOString()}});}}
    if(Array.isArray(body.ams)){for(const slot of body.ams.slice(0,32)){const existing=await getDb().select({id:bambuAmsSlots.id}).from(bambuAmsSlots).where(and(eq(bambuAmsSlots.printerId,printer.id),eq(bambuAmsSlots.amsUnit,slot.unit),eq(bambuAmsSlots.trayIndex,slot.tray))).limit(1);const values={material:slot.material||"",colorHex:slot.colorHex||"",remainingPercent:Number.isFinite(slot.remainingPercent)?slot.remainingPercent:null,tagUid:slot.tagUid||"",active:Boolean(slot.active),lastSeenAt:new Date().toISOString()};if(existing[0])await getDb().update(bambuAmsSlots).set(values).where(eq(bambuAmsSlots.id,existing[0].id));else await getDb().insert(bambuAmsSlots).values({printerId:printer.id,amsUnit:slot.unit,trayIndex:slot.tray,...values});}}
    const [command]=await getDb().select().from(printerCommands).where(and(eq(printerCommands.printerId,printer.id),eq(printerCommands.status,"待执行"))).orderBy(asc(printerCommands.createdAt)).limit(1);
    return Response.json({ok:true,printer:{id:row.id,name:row.name,activeSpoolId:row.activeSpoolExternalId},command:command?{id:command.id,name:command.command,payload:JSON.parse(command.payload)}:null});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"代理上报失败"},{status:500});}
}
