import {redirect} from "next/navigation";
import {can,getAccessContext} from "../access-control";
import {getInventoryValueReport} from "../../inventory-value/data";
import "./inventory-value.css";

export const dynamic="force-dynamic";
const money=(cents:number)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:"MYR"}).format(cents/100);
const weight=(grams:number)=>grams>=1000?`${(grams/1000).toFixed(2)} kg`:`${grams.toFixed(1)} g`;
const bucketName:Record<string,string>={sealed:"未拆封库存",open_storage:"已拆封仓储",in_use:"打印机使用中",other:"其他可用状态"};
const purposeName:Record<string,string>={model:"模型本体",support:"支撑",purge:"冲刷／屎料",prime_tower:"擦料塔",unknown:"待分类"};

export default async function InventoryValuePage(){
 const user=await getAccessContext();if(!user)redirect("/");if(!can(user,"finance.read"))redirect("/");
 const report=await getInventoryValueReport(user.organizationId),maximum=Math.max(1,...report.buckets.map(row=>row.valueCents));
 return <main className="value-page"><header><div><small>INVENTORY · COST LAYERS</small><h1>库存价值与成本分析</h1><p>把未拆封、已拆封和打印机使用中的实体耗材卷，按采购批次实际成本统一估值。</p></div><nav><a href="/analytics">经营分析</a><a href="/procurement">采购中心</a></nav></header>
 <section className="value-kpis"><article><span>当前库存价值</span><strong>{money(report.summary.inventoryValueCents)}</strong><small>{report.summary.spools} 卷 · {weight(report.summary.inventoryGrams)}</small></article><article><span>已结算打印材料成本</span><strong>{money(report.summary.settledMaterialCostCents)}</strong><small>来源于不可变结算记录</small></article><article className={report.summary.varianceCents>0?"warn":""}><span>采购实际价差</span><strong>{report.summary.varianceCents>0?"+":""}{money(report.summary.varianceCents)}</strong><small>实际 {money(report.summary.actualTotalCents)} / 审批 {money(report.summary.approvedTotalCents)}</small></article><article className={report.summary.unknownCostSpools?"warn":""}><span>成本数据完整性</span><strong>{report.summary.unknownCostSpools} 卷待补</strong><small>{report.summary.pendingInvoices} 张发票待审核</small></article></section>
 <section className="value-grid"><article className="value-panel"><div className="panel-title"><div><small>STOCK POSITION</small><h2>库存状态价值</h2></div><span>剩余净重 × 批次成本</span></div><div className="bucket-list">{report.buckets.map(row=><div key={row.bucket}><span><b>{bucketName[row.bucket]||row.bucket}</b><small>{row.spools} 卷 · {weight(row.grams)}</small></span><i><em style={{width:`${Math.max(2,row.valueCents/maximum*100)}%`}}/></i><strong>{money(row.valueCents)}</strong></div>)}</div></article><article className="value-panel"><div className="panel-title"><div><small>SETTLED USAGE</small><h2>打印用途成本</h2></div><span>历史保持不变</span></div><div className="usage-list">{report.usage.length?report.usage.map(row=><div key={row.purpose}><span><b>{purposeName[row.purpose]||row.purpose}</b><small>{row.lines} 条结算 · {weight(row.grams)}</small></span><strong>{money(row.costCents)}</strong></div>):<p>暂无已结算耗材使用记录</p>}</div><aside>已校正 {report.summary.adjustedLots} 个未消耗批次；保护 {report.summary.protectedLots} 个已有结算记录的批次。</aside></article></section>
 <section className="value-panel value-table"><div className="panel-title"><div><small>MATERIAL VALUE</small><h2>耗材库存价值明细</h2></div><span>按耗材主数据汇总</span></div><div className="table-scroll"><table><thead><tr><th>耗材</th><th>实体卷</th><th>剩余净重</th><th>平均成本 / kg</th><th>库存价值</th></tr></thead><tbody>{report.materials.map(row=><tr key={row.catalogCode}><td><i style={{background:row.colorHex?`#${row.colorHex}`:"#d7ddda"}}/><b>{row.catalogCode}</b><small>{row.material} · {row.colorName}</small></td><td>{row.spools}</td><td>{weight(row.grams)}</td><td>{money(row.averageCostCentsPerKg)}</td><td><strong>{money(row.valueCents)}</strong></td></tr>)}</tbody></table></div></section>
 <section className="value-panel value-table"><div className="panel-title"><div><small>PURCHASE LOTS</small><h2>采购批次成本层</h2></div><span>最多显示最近 100 个有余额批次</span></div><div className="table-scroll"><table><thead><tr><th>批次</th><th>供应商</th><th>剩余卷数 / 重量</th><th>单位成本</th><th>批次价值</th><th>对账</th></tr></thead><tbody>{report.lots.map(row=><tr key={row.lotNo}><td><b>{row.lotNo}</b><small>{row.receivedAt.slice(0,10)||"日期未登记"}</small></td><td>{row.supplierName}</td><td>{row.spools} 卷 · {weight(row.remainingGrams)}</td><td>{money(row.unitCostCentsPerKg)} / kg</td><td><strong>{money(row.valueCents)}</strong></td><td><span className={row.reconciled?"matched":"pending"}>{row.reconciled?"已按发票校正":"审批成本"}</span></td></tr>)}</tbody></table></div></section>
 </main>;
}
