import {getD1} from "../../../db";
import {getAccessContext,recordAudit} from "../../access-control";
import {requireApiAccess} from "../../api-auth";
import {BAMBU_OFFICIAL_SOURCE,BAMBU_SOURCE_CHECKED_AT,bambuPlaBasicStarter} from "../../../materials/bambu-official";
import {normalizeCatalogImportRow,parseCatalogCsv,validateCatalogImportRow,type CatalogImportRow} from "../../../materials/catalog-import";

const fail=(error:string,status=400)=>Response.json({error},{status});
const normalize=(type:string,value:string)=>type==="color_hex"?value.replace("#","").toUpperCase():value.trim().toUpperCase();
type Existing={id:number;catalogCode:string;brand:string;series:string;material:string;colorName:string;colorNameEn:string;colorCode:string;colorHex:string;densityGcm3:number;defaultNetGrams:number;amsCompatibility:string;sourceUrl:string;sourceCheckedAt:string|null;officialVerified:number};
type ReviewRow=CatalogImportRow&{rowNumber:number;action:"create"|"update"|"unchanged"|"rejected";errors:string[]};
const comparable=(row:CatalogImportRow)=>[row.brand,row.series,row.material,row.colorName,row.colorNameEn,row.colorCode,row.colorHex,Number(row.densityGcm3),Number(row.defaultNetGrams),row.amsCompatibility,row.sourceUrl,row.sourceCheckedAt||null];
const currentComparable=(row:Existing)=>[row.brand,row.series,row.material,row.colorName,row.colorNameEn,row.colorCode,row.colorHex,row.densityGcm3,row.defaultNetGrams,row.amsCompatibility,row.sourceUrl,row.sourceCheckedAt];

async function existingCatalog(organizationId:number){const result=await getD1().prepare("SELECT id,catalog_code catalogCode,brand,series,material,color_name colorName,color_name_en colorNameEn,color_code colorCode,color_hex colorHex,density_g_cm3 densityGcm3,default_net_grams defaultNetGrams,ams_compatibility amsCompatibility,source_url sourceUrl,source_checked_at sourceCheckedAt,official_verified officialVerified FROM material_catalog_items WHERE organization_id=?").bind(organizationId).all<Existing>();return new Map(result.results.map(row=>[row.catalogCode.toUpperCase(),row]))}
function reviewRows(rows:CatalogImportRow[],existing:Map<string,Existing>){const seen=new Set<string>();return rows.map((raw,index)=>{const row=normalizeCatalogImportRow(raw),errors=validateCatalogImportRow(row),current=existing.get(row.catalogCode);if(seen.has(row.catalogCode))errors.push("同一文件中目录编码重复");seen.add(row.catalogCode);if(current?.officialVerified)errors.push("官方核验记录不可由批量导入覆盖");const action=errors.length?"rejected":!current?"create":JSON.stringify(comparable(row))===JSON.stringify(currentComparable(current))?"unchanged":"update";return {...row,rowNumber:index+2,action,errors} as ReviewRow})}
const summarize=(rows:ReviewRow[])=>({total:rows.length,create:rows.filter(row=>row.action==="create").length,update:rows.filter(row=>row.action==="update").length,unchanged:rows.filter(row=>row.action==="unchanged").length,rejected:rows.filter(row=>row.action==="rejected").length});

export async function GET(){const denied=await requireApiAccess();if(denied)return denied;const context=await getAccessContext();if(!context)return fail("请先登录",401);const db=getD1(),org=context.organizationId,[catalog,aliases,batches]=await Promise.all([db.prepare("SELECT id,catalog_code catalogCode,brand,series,material,color_name colorName,color_name_en colorNameEn,color_code colorCode,color_hex colorHex,source_type sourceType,source_url sourceUrl,source_checked_at sourceCheckedAt,official_verified officialVerified,ams_compatibility amsCompatibility,reorder_point_spools reorderPointSpools,target_stock_spools targetStockSpools FROM material_catalog_items WHERE organization_id=? ORDER BY official_verified DESC,series,color_code").bind(org).all(),db.prepare("SELECT a.id,a.catalog_item_id catalogItemId,a.alias_type aliasType,a.alias_value aliasValue,a.source FROM material_catalog_aliases a WHERE a.organization_id=? ORDER BY a.catalog_item_id,a.alias_type,a.alias_value").bind(org).all(),db.prepare("SELECT id,batch_key batchKey,file_name fileName,status,summary_json summaryJson,created_by createdBy,created_at createdAt,applied_by appliedBy,applied_at appliedAt FROM material_catalog_import_batches WHERE organization_id=? ORDER BY id DESC LIMIT 10").bind(org).all()]);return Response.json({catalog:catalog.results,aliases:aliases.results,batches:batches.results.map(row=>({...row,summary:JSON.parse(String(row.summaryJson))})),starter:bambuPlaBasicStarter,source:{url:BAMBU_OFFICIAL_SOURCE,checkedAt:BAMBU_SOURCE_CHECKED_AT}})}

export async function POST(request:Request){const denied=await requireApiAccess(true,"inventory.write");if(denied)return denied;const context=await getAccessContext();if(!context)return fail("请先登录",401);try{const body=await request.json() as{action?:string;catalogItemId?:number;aliasType?:string;aliasValue?:string;csv?:string;fileName?:string;batchId?:number;reorderPointSpools?:number;targetStockSpools?:number},db=getD1(),org=context.organizationId,now=new Date().toISOString();
 if(body.action==="previewImport"){const csv=String(body.csv||"");if(!csv||csv.length>1_000_000)return fail("请选择不超过 1MB 的 CSV 文件");const parsed=parseCatalogCsv(csv);if(!parsed.length||parsed.length>500)return fail("CSV 必须包含 1 至 500 条数据");const rows=reviewRows(parsed,await existingCatalog(org)),summary=summarize(rows),batchKey=crypto.randomUUID();const created=await db.prepare("INSERT INTO material_catalog_import_batches(organization_id,batch_key,file_name,rows_json,summary_json,created_by) VALUES(?,?,?,?,?,?) RETURNING id").bind(org,batchKey,String(body.fileName||"material-master.csv").slice(0,200),JSON.stringify(rows),JSON.stringify(summary),context.email).first<{id:number}>();await recordAudit(context,"material_master.import.previewed","material_catalog_import_batch",String(created!.id),summary);return Response.json({batchId:created!.id,rows,summary},{status:201})}
 if(body.action==="applyImport"){const batchId=Number(body.batchId);if(!Number.isInteger(batchId))return fail("导入批次无效");const batch=await db.prepare("SELECT id,status,rows_json rowsJson FROM material_catalog_import_batches WHERE id=? AND organization_id=?").bind(batchId,org).first<{id:number;status:string;rowsJson:string}>();if(!batch)return fail("导入批次不存在",404);if(batch.status!=="pending")return fail("该批次已处理",409);const stored=JSON.parse(batch.rowsJson) as ReviewRow[],rows=reviewRows(stored,await existingCatalog(org)),summary=summarize(rows);if(summary.rejected)return fail("数据已变化或仍有拒绝项，请重新预览",409);const changed=rows.filter(row=>row.action==="create"||row.action==="update");const statements=changed.map(row=>db.prepare(`INSERT INTO material_catalog_items(organization_id,catalog_code,brand,series,material,color_name,color_name_en,color_code,color_hex,density_g_cm3,default_net_grams,default_tare_grams,ams_compatibility,tags,source_type,source_url,source_checked_at,official_verified,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,0,?,'[]','bulk_import',?,?,0,?) ON CONFLICT(organization_id,catalog_code) DO UPDATE SET brand=excluded.brand,series=excluded.series,material=excluded.material,color_name=excluded.color_name,color_name_en=excluded.color_name_en,color_code=excluded.color_code,color_hex=excluded.color_hex,density_g_cm3=excluded.density_g_cm3,default_net_grams=excluded.default_net_grams,ams_compatibility=excluded.ams_compatibility,source_type='bulk_import',source_url=excluded.source_url,source_checked_at=excluded.source_checked_at,updated_at=excluded.updated_at WHERE material_catalog_items.official_verified=0`).bind(org,row.catalogCode,row.brand,row.series,row.material,row.colorName,row.colorNameEn,row.colorCode,row.colorHex,Number(row.densityGcm3),Number(row.defaultNetGrams),row.amsCompatibility,row.sourceUrl,row.sourceCheckedAt||null,now));statements.push(db.prepare("UPDATE material_catalog_import_batches SET status='applied',summary_json=?,applied_by=?,applied_at=? WHERE id=? AND organization_id=? AND status='pending'").bind(JSON.stringify(summary),context.email,now,batchId,org));await db.batch(statements);await recordAudit(context,"material_master.import.applied","material_catalog_import_batch",String(batchId),summary);return Response.json({batchId,applied:changed.length,summary})}
 if(body.action==="importBambuStarter"){let imported=0;for(const item of bambuPlaBasicStarter){const catalogCode=`BAMBU-PLA-BASIC-${item.code}`,row=await db.prepare(`INSERT INTO material_catalog_items(organization_id,catalog_code,brand,series,material,color_name,color_name_en,color_code,color_hex,density_g_cm3,default_net_grams,default_tare_grams,ams_compatibility,tags,source_type,source_url,source_checked_at,official_verified,updated_at) VALUES(?,?,?,?,?,?,?,?,?,1.24,1000,0,'compatible','["官方"]','bambu_official',?,?,1,?) ON CONFLICT(organization_id,catalog_code) DO UPDATE SET brand=excluded.brand,series=excluded.series,material=excluded.material,color_name=excluded.color_name,color_name_en=excluded.color_name_en,color_code=excluded.color_code,color_hex=excluded.color_hex,ams_compatibility=excluded.ams_compatibility,source_type=excluded.source_type,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at,official_verified=1,updated_at=excluded.updated_at RETURNING id`).bind(org,catalogCode,"Bambu Lab","PLA Basic","PLA",item.nameZh,item.name,item.code,item.hex,BAMBU_OFFICIAL_SOURCE,BAMBU_SOURCE_CHECKED_AT,now).first<{id:number}>();const aliases=[["material","PLA"],["rfid_material","PLA"],["color_name",item.name],["color_code",item.code],["color_hex",item.hex]];await db.batch(aliases.map(([type,value])=>db.prepare("INSERT OR IGNORE INTO material_catalog_aliases(organization_id,catalog_item_id,alias_type,alias_value,source,created_by) VALUES(?,?,?,?,?,?)").bind(org,row!.id,type,normalize(type,value),"bambu_official",context.email)));imported++}await recordAudit(context,"material_master.bambu_starter.imported","material_catalog","bambu-pla-basic",{imported,source:BAMBU_OFFICIAL_SOURCE,checkedAt:BAMBU_SOURCE_CHECKED_AT});return Response.json({imported})}
 if(body.action==="updateStockPolicy"){const catalogItemId=Number(body.catalogItemId),reorder=Math.floor(Number(body.reorderPointSpools)),target=Math.floor(Number(body.targetStockSpools));if(!Number.isInteger(catalogItemId)||!Number.isInteger(reorder)||reorder<0||!Number.isInteger(target)||target<reorder||target>10000)return fail("补货策略无效：目标库存必须大于或等于触发库存");const result=await db.prepare("UPDATE material_catalog_items SET reorder_point_spools=?,target_stock_spools=?,updated_at=? WHERE id=? AND organization_id=?").bind(reorder,target,now,catalogItemId,org).run();if(!result.meta.changes)return fail("耗材目录不存在",404);await recordAudit(context,"material_master.stock_policy.updated","material_catalog_item",String(catalogItemId),{reorderPointSpools:reorder,targetStockSpools:target});return Response.json({catalogItemId,reorderPointSpools:reorder,targetStockSpools:target})}
 if(body.action==="addAlias"){const catalogItemId=Number(body.catalogItemId),type=String(body.aliasType||""),value=normalize(type,String(body.aliasValue||""));if(!Number.isInteger(catalogItemId)||!["material","color_name","color_code","color_hex","rfid_material"].includes(type)||!value)return fail("别名参数无效");const owned=await db.prepare("SELECT id FROM material_catalog_items WHERE id=? AND organization_id=?").bind(catalogItemId,org).first();if(!owned)return fail("耗材目录不存在",404);await db.prepare("INSERT OR IGNORE INTO material_catalog_aliases(organization_id,catalog_item_id,alias_type,alias_value,source,created_by) VALUES(?,?,?,?,?,?)").bind(org,catalogItemId,type,value,"manual",context.email).run();await recordAudit(context,"material_master.alias.added","material_catalog_item",String(catalogItemId),{type,value});return Response.json({catalogItemId,type,value})}return fail("不支持的主数据操作");
 }catch(error){return fail(error instanceof Error?error.message:"主数据操作失败")}}
