import {getD1} from "../../../db";
import {getAccessContext,recordAudit} from "../../access-control";
import {requireApiAccess} from "../../api-auth";
import {BAMBU_OFFICIAL_SOURCE,BAMBU_SOURCE_CHECKED_AT,bambuPlaBasicStarter} from "../../../materials/bambu-official";

const fail=(error:string,status=400)=>Response.json({error},{status});
const normalize=(type:string,value:string)=>type==="color_hex"?value.replace("#","").toUpperCase():value.trim().toUpperCase();

export async function GET(){const denied=await requireApiAccess();if(denied)return denied;const context=await getAccessContext();if(!context)return fail("请先登录",401);const db=getD1(),org=context.organizationId,[catalog,aliases]=await Promise.all([db.prepare("SELECT id,catalog_code catalogCode,brand,series,material,color_name colorName,color_name_en colorNameEn,color_code colorCode,color_hex colorHex,source_type sourceType,source_url sourceUrl,source_checked_at sourceCheckedAt,official_verified officialVerified,ams_compatibility amsCompatibility FROM material_catalog_items WHERE organization_id=? ORDER BY official_verified DESC,series,color_code").bind(org).all(),db.prepare("SELECT a.id,a.catalog_item_id catalogItemId,a.alias_type aliasType,a.alias_value aliasValue,a.source FROM material_catalog_aliases a WHERE a.organization_id=? ORDER BY a.catalog_item_id,a.alias_type,a.alias_value").bind(org).all()]);return Response.json({catalog:catalog.results,aliases:aliases.results,starter:bambuPlaBasicStarter,source:{url:BAMBU_OFFICIAL_SOURCE,checkedAt:BAMBU_SOURCE_CHECKED_AT}})}

export async function POST(request:Request){const denied=await requireApiAccess(true,"inventory.write");if(denied)return denied;const context=await getAccessContext();if(!context)return fail("请先登录",401);try{const body=await request.json() as{action?:string;catalogItemId?:number;aliasType?:string;aliasValue?:string},db=getD1(),org=context.organizationId,now=new Date().toISOString();
 if(body.action==="importBambuStarter"){let imported=0;for(const item of bambuPlaBasicStarter){const catalogCode=`BAMBU-PLA-BASIC-${item.code}`,row=await db.prepare(`INSERT INTO material_catalog_items(organization_id,catalog_code,brand,series,material,color_name,color_name_en,color_code,color_hex,density_g_cm3,default_net_grams,default_tare_grams,ams_compatibility,tags,source_type,source_url,source_checked_at,official_verified,updated_at) VALUES(?,?,?,?,?,?,?,?,?,1.24,1000,0,'compatible','["官方"]','bambu_official',?,?,1,?) ON CONFLICT(organization_id,catalog_code) DO UPDATE SET brand=excluded.brand,series=excluded.series,material=excluded.material,color_name=excluded.color_name,color_name_en=excluded.color_name_en,color_code=excluded.color_code,color_hex=excluded.color_hex,ams_compatibility=excluded.ams_compatibility,source_type=excluded.source_type,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at,official_verified=1,updated_at=excluded.updated_at RETURNING id`).bind(org,catalogCode,"Bambu Lab","PLA Basic","PLA",item.nameZh,item.name,item.code,item.hex,BAMBU_OFFICIAL_SOURCE,BAMBU_SOURCE_CHECKED_AT,now).first<{id:number}>();const aliases=[["material","PLA"],["rfid_material","PLA"],["color_name",item.name],["color_code",item.code],["color_hex",item.hex]];await db.batch(aliases.map(([type,value])=>db.prepare("INSERT OR IGNORE INTO material_catalog_aliases(organization_id,catalog_item_id,alias_type,alias_value,source,created_by) VALUES(?,?,?,?,?,?)").bind(org,row!.id,type,normalize(type,value),"bambu_official",context.email)));imported++}await recordAudit(context,"material_master.bambu_starter.imported","material_catalog","bambu-pla-basic",{imported,source:BAMBU_OFFICIAL_SOURCE,checkedAt:BAMBU_SOURCE_CHECKED_AT});return Response.json({imported})}
 if(body.action==="addAlias"){const catalogItemId=Number(body.catalogItemId),type=String(body.aliasType||""),value=normalize(type,String(body.aliasValue||""));if(!Number.isInteger(catalogItemId)||!["material","color_name","color_code","color_hex","rfid_material"].includes(type)||!value)return fail("别名参数无效");const owned=await db.prepare("SELECT id FROM material_catalog_items WHERE id=? AND organization_id=?").bind(catalogItemId,org).first();if(!owned)return fail("耗材目录不存在",404);await db.prepare("INSERT OR IGNORE INTO material_catalog_aliases(organization_id,catalog_item_id,alias_type,alias_value,source,created_by) VALUES(?,?,?,?,?,?)").bind(org,catalogItemId,type,value,"manual",context.email).run();await recordAudit(context,"material_master.alias.added","material_catalog_item",String(catalogItemId),{type,value});return Response.json({catalogItemId,type,value})}return fail("不支持的主数据操作");
 }catch(error){return fail(error instanceof Error?error.message:"主数据操作失败")}}
