import {getD1} from "../db";
type Target={revenueTargetCents:number;grossMarginTargetBps:number;operatingCashflowTargetCents:number;materialLossTargetBps:number;utilizationTargetBps:number;notes:string};
export async function getBusinessTargets(organizationId:number,month=new Date().toISOString().slice(0,7)){const db=getD1(),start=`${month}-01`,next=new Date(`${start}T00:00:00Z`);next.setUTCMonth(next.getUTCMonth()+1);const end=next.toISOString().slice(0,10),current=month===new Date().toISOString().slice(0,7),capacityEnd=current?new Date().toISOString().slice(0,10):end;
 const [target,revenue,cost,cash,material,utilization]=await Promise.all([
  db.prepare("SELECT revenue_target_cents revenueTargetCents,gross_margin_target_bps grossMarginTargetBps,operating_cashflow_target_cents operatingCashflowTargetCents,material_loss_target_bps materialLossTargetBps,utilization_target_bps utilizationTargetBps,notes FROM monthly_business_targets WHERE organization_id=? AND target_month=?").bind(organizationId,month).first<Target>(),
  db.prepare("SELECT COALESCE(SUM(amount_cents),0) cents FROM invoices WHERE organization_id=? AND status!='void' AND issued_at>=? AND issued_at<?").bind(organizationId,start,end).first<{cents:number}>(),
  db.prepare(`SELECT COALESCE((SELECT SUM(u.cost_cents) FROM print_material_usage_lines u WHERE u.organization_id=? AND u.settled_at>=? AND u.settled_at<?),0)+COALESCE((SELECT SUM(e.amount_cents) FROM profit_cost_entries e WHERE e.organization_id=? AND e.basis='actual' AND e.category!='revenue_adjustment' AND e.occurred_at>=? AND e.occurred_at<?),0) cents`).bind(organizationId,start,end,organizationId,start,end).first<{cents:number}>(),
  db.prepare(`SELECT COALESCE((SELECT SUM(amount_cents) FROM invoice_payments WHERE organization_id=? AND paid_at>=? AND paid_at<?),0)-COALESCE((SELECT SUM(amount_cents) FROM supplier_payments WHERE organization_id=? AND paid_at>=? AND paid_at<?),0) cents`).bind(organizationId,start,end,organizationId,start,end).first<{cents:number}>(),
  db.prepare(`SELECT COALESCE(SUM(CASE WHEN lower(purpose) IN ('purge','waste','scrap','failed') THEN COALESCE(settled_grams,0) ELSE 0 END),0) lossGrams,COALESCE(SUM(COALESCE(settled_grams,0)),0) totalGrams FROM print_material_usage_lines WHERE organization_id=? AND settled_at>=? AND settled_at<?`).bind(organizationId,start,end).first<{lossGrams:number;totalGrams:number}>(),
  db.prepare(`SELECT COALESCE((SELECT SUM(MAX(0,(julianday(completed_at)-julianday(started_at))*24)) FROM print_jobs WHERE organization_id=? AND completed_at>=? AND completed_at<?),0) productiveHours,COALESCE((SELECT COUNT(*) FROM printer_bindings WHERE organization_id=? AND status!='disabled'),0) printers`).bind(organizationId,start,end,organizationId).first<{productiveHours:number;printers:number}>(),
 ]);const actualRevenueCents=Number(revenue?.cents??0),actualCostCents=Number(cost?.cents??0),actualGrossMarginBps=actualRevenueCents?Math.round((actualRevenueCents-actualCostCents)*10000/actualRevenueCents):0,actualCashflowCents=Number(cash?.cents??0),materialLossBps=Number(material?.totalGrams)?Math.round(Number(material?.lossGrams)*10000/Number(material?.totalGrams)):0,elapsedHours=Math.max(24,(new Date(`${capacityEnd}T00:00:00Z`).getTime()-new Date(`${start}T00:00:00Z`).getTime())/3600000),utilizationBps=Number(utilization?.printers)?Math.round(Number(utilization?.productiveHours)*10000/(Number(utilization?.printers)*elapsedHours)):0,targets:Target=target??{revenueTargetCents:0,grossMarginTargetBps:0,operatingCashflowTargetCents:0,materialLossTargetBps:0,utilizationTargetBps:0,notes:""};
 const metrics=[{key:"revenue",label:"营业收入",actual:actualRevenueCents,target:targets.revenueTargetCents,unit:"money",higherBetter:true},{key:"margin",label:"毛利率",actual:actualGrossMarginBps,target:targets.grossMarginTargetBps,unit:"bps",higherBetter:true},{key:"cashflow",label:"经营现金流",actual:actualCashflowCents,target:targets.operatingCashflowTargetCents,unit:"money",higherBetter:true},{key:"loss",label:"材料损耗率",actual:materialLossBps,target:targets.materialLossTargetBps,unit:"bps",higherBetter:false},{key:"utilization",label:"设备利用率",actual:utilizationBps,target:targets.utilizationTargetBps,unit:"bps",higherBetter:true}].map(row=>({...row,variance:row.actual-row.target,onTrack:row.target===0?null:row.higherBetter?row.actual>=row.target:row.actual<=row.target,completionBps:row.target===0?0:Math.round(row.actual*10000/row.target)}));return {month,start,end,configured:Boolean(target),targets,actuals:{revenueCents:actualRevenueCents,costCents:actualCostCents,grossMarginBps:actualGrossMarginBps,operatingCashflowCents:actualCashflowCents,materialLossBps,utilizationBps},metrics,offTrack:metrics.filter(row=>row.onTrack===false).length}}
