"use client";
import {useState} from "react";
import readXlsxFile from "read-excel-file";
import {normalizeBulkReceiptRows,parseCsv,receiptTemplate,type BulkReceiptRow} from "../../inventory/bulk-receipt";

type Catalog={catalogCode:string;material:string;colorName:string;defaultNetGrams:number;defaultTareGrams:number};
export default function BulkReceiptModal({catalog,locations,onClose,onImported}:{catalog:Catalog[];locations:{code:string;name:string}[];onClose:()=>void;onImported:()=>Promise<void>}){
 const [rows,setRows]=useState<BulkReceiptRow[]>([]),[fileName,setFileName]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const errors=rows.reduce((sum,row)=>sum+row.errors.length,0);
 function download(){const sample=catalog[0]||{catalogCode:"BAMBU-PLA-BASIC-10101",defaultNetGrams:1000,defaultTareGrams:250},blob=new Blob([receiptTemplate({catalogCode:sample.catalogCode,netGrams:sample.defaultNetGrams,tareGrams:sample.defaultTareGrams})],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="采购入库批量导入模板.csv";a.click();URL.revokeObjectURL(url)}
 async function choose(file:File){setBusy(true);setMessage("");try{const matrix=file.name.toLowerCase().endsWith(".csv")?parseCsv(await file.text()):await readXlsxFile(file),parsed=normalizeBulkReceiptRows(matrix,new Set(catalog.map(item=>item.catalogCode.toUpperCase())),new Set(locations.map(item=>item.code.toUpperCase())));setRows(parsed);setFileName(file.name);if(!parsed.length)setMessage("文件中没有可导入的数据行。")}catch(error){setMessage(error instanceof Error?error.message:"文件读取失败")}finally{setBusy(false)}}
 async function apply(){if(!rows.length||errors)return;setBusy(true);setMessage("");try{const response=await fetch("/api/inventory-v2",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"bulkReceiveSpools",rows})}),result=await response.json();if(!response.ok)throw new Error(result.error||"批量导入失败");setMessage(`成功入库 ${result.imported} 卷，库存明细与采购成本已同步。`);await onImported();setTimeout(onClose,700)}catch(error){setMessage(error instanceof Error?error.message:"批量导入失败")}finally{setBusy(false)}}
 return <div className="bulk-receipt-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="bulk-receipt-modal" role="dialog" aria-modal="true" aria-label="批量采购入库"><header><div><h2>批量采购入库</h2><p>每一行对应一卷实体耗材，导入后同步生成采购批次、实体卷和库存流水。</p></div><button onClick={onClose}>×</button></header><div className="bulk-guide"><span><b>1</b> 下载模板</span><i>→</i><span><b>2</b> Excel 填写</span><i>→</i><span><b>3</b> 上传校验</span><i>→</i><span><b>4</b> 确认入库</span></div><div className="bulk-toolbar"><button onClick={download}>⇩ 下载标准模板</button><label>选择 CSV / Excel<input type="file" accept=".csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void choose(file);event.currentTarget.value=""}}/></label><small>{fileName||"支持 CSV、XLSX；最多 500 卷"}</small></div>{message?<p className="bulk-message">{message}</p>:null}<div className="bulk-preview"><table><thead><tr><th>行</th><th>耗材目录编码</th><th>实体卷编号</th><th>采购批次</th><th>单价</th><th>净重</th><th>空盘</th><th>仓位</th><th>入库日期</th><th>校验</th></tr></thead><tbody>{rows.slice(0,100).map(row=><tr key={row.rowNumber} className={row.errors.length?"invalid":""}><td>{row.rowNumber}</td><td>{row.catalogCode}</td><td>{row.spoolCode}</td><td>{row.lotNo}</td><td>RM {row.costPerKg.toFixed(2)}</td><td>{row.netGrams}g</td><td>{row.tareGrams}g</td><td>{row.locationCode}</td><td>{row.receivedAt}</td><td>{row.errors.length?<span>{row.errors.join("；")}</span>:<b>可导入</b>}</td></tr>)}{!rows.length?<tr><td colSpan={10}>请下载模板填写，然后选择文件生成导入预览。</td></tr>:null}</tbody></table></div><footer><span>{rows.length?`共 ${rows.length} 行 · ${rows.length-errors} 行可导入 · ${errors} 个错误`:"尚未选择文件"}</span><div><button onClick={onClose}>取消</button><button className="primary" disabled={busy||!rows.length||errors>0} onClick={()=>void apply()}>{busy?"处理中…":"确认批量入库"}</button></div></footer></section></div>
}
