"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import SpoolLabel,{type LabelSpool} from "./spool-label";

type Catalog={id:number;catalogCode:string;brand:string;series:string;material:string;colorName:string;colorNameEn:string;colorCode:string;colorHex:string;densityGcm3:number;defaultNetGrams:number;defaultTareGrams:number;amsCompatibility:string;tags:string;sealedCount:number;sealedGrams:number;openedGrams:number;lowStockGrams:number};
type Spool={id:number;spoolCode:string;state:string;initialNetGrams:number;remainingNetGrams:number;tareGrams:number;lastGrossGrams:number|null;lastWeighedAt:string|null;rfidUid:string;catalogCode:string;material:string;brand:string;colorName:string;colorCode:string;colorHex:string;locationName:string;locationKind:string};
type Position={id:number;printerId:number;printerName:string;model:string;feedKind:string;amsUnit:number|null;slotIndex:number|null;toolhead:string;label:string};
type Binding={id:number;spoolId:number;feedPositionId:number;spoolCode:string;remainingNetGrams:number;material:string;colorName:string;colorHex:string;printerName:string;model:string;feedKind:string;amsUnit:number|null;slotIndex:number|null;toolhead:string};
type Movement={id:number;movementType:string;netGramsDelta:number;note:string;operatorEmail:string;occurredAt:string;spoolCode:string;material:string;colorName:string;fromLocation:string|null;toLocation:string|null};
type Usage={id:number;printSessionId:number;spoolId:number|null;toolhead:string;purpose:string;estimatedGrams:number;settledGrams:number|null;measuredGrams:number|null;estimateSource:string;settledAt:string|null;filename:string;sessionStatus:string;printerName:string;spoolCode:string|null};
type Slot={id:number;printerId:number;printerName:string;amsUnit:number|null;slotIndex:number|null;feedKind:string;toolhead:string;telemetrySlotId:number|null;material:string;colorHex:string;remainingPercent:number|null;tagUid:string;active:boolean;lastSeenAt:string};
type Data={canWrite:boolean;summary:{sealedSpools:number;sealedGrams:number;inUseSpools:number;openSpools:number;assetGrams:number;needsCount:number};catalog:Catalog[];spools:Spool[];printers:{id:number;name:string;model:string}[];positions:Position[];bindings:Binding[];movements:Movement[];usage:Usage[];unboundSlots:Slot[];transit:{id:number;purchaseNo:string;supplierName:string;status:string;incomingGrams:number}[]};
const stateName:Record<string,string>={sealed:"未拆封",open_storage:"已开封周转",in_use:"使用中",empty:"已用完",scrapped:"已报废",needs_count:"待盘点迁移"};
const amsName:Record<string,string>={compatible:"AMS兼容",conditional:"有条件兼容",incompatible:"不兼容AMS",unknown:"待确认"};
const purposeName:Record<string,string>={model:"模型主体",support:"普通支撑",support_interface:"支撑界面",purge:"冲刷废料",wipe_tower:"擦拭塔",brim:"裙边",calibration:"校准/预挤出",unknown:"待分类"};
const feedName=(p:Pick<Position,"feedKind"|"amsUnit"|"slotIndex"|"toolhead">)=>`${p.feedKind==="external"?"外置料盘":`${p.feedKind.toUpperCase()} ${Number(p.amsUnit??0)+1}-${Number(p.slotIndex??0)+1}`} · ${p.toolhead==="auxiliary"?"辅助工具头":p.toolhead==="main"?"主工具头":p.toolhead}`;
const color=(value:unknown)=>{const v=String(value||"").replace("#","").slice(0,6);return /^[0-9a-f]{6}$/i.test(v)?`#${v}`:"#cbd2cd"};
const tagText=(value:string)=>{try{const tags=JSON.parse(value);return Array.isArray(tags)?tags.join(", "):""}catch{return ""}};

export default function InventoryV2Client(){
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState<"stock"|"active">("stock"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[dialog,setDialog]=useState<"receive"|"issue"|"feed"|"adjust"|"migrate"|"catalog"|null>(null),[actionSpool,setActionSpool]=useState<number|null>(null),[catalogItem,setCatalogItem]=useState<Catalog|null>(null),[labelSpool,setLabelSpool]=useState<LabelSpool|null>(null),[scanCode,setScanCode]=useState(""),[issueSpoolId,setIssueSpoolId]=useState(""),[issuePositionId,setIssuePositionId]=useState(""),[detectedSlot,setDetectedSlot]=useState<Slot|null>(null);
 const load=useCallback(async()=>{const response=await fetch("/api/inventory-v2",{cache:"no-store"}),value=await response.json();if(!response.ok)throw new Error(value.error);setData(value)},[]);useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 async function mutate(body:Record<string,unknown>){setBusy(true);setError("");try{const response=await fetch("/api/inventory-v2",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),value=await response.json();if(!response.ok)throw new Error(value.error);setDialog(null);setActionSpool(null);await load()}catch(e){setError(e instanceof Error?e.message:"操作失败")}finally{setBusy(false)}}
 const sealed=useMemo(()=>data?.spools.filter(s=>s.state==="sealed")??[],[data]),legacy=useMemo(()=>data?.spools.filter(s=>s.state==="needs_count")??[],[data]),open=useMemo(()=>data?.spools.filter(s=>s.state==="open_storage")??[],[data]);
 const eligible=useMemo(()=>[...open,...sealed],[open,sealed]);
 function scan(value:string){setScanCode(value);const code=value.trim().toUpperCase().replace(/^LT:SPOOL:/,"");const match=eligible.find(spool=>spool.spoolCode.toUpperCase()===code);setIssueSpoolId(match?String(match.id):"")}
 function slotSuggestion(slot:Slot){const material=slot.material.trim().toUpperCase(),hex=slot.colorHex.replace("#","").slice(0,6).toUpperCase(),rfid=eligible.find(spool=>slot.tagUid&&spool.rfidUid===slot.tagUid),catalog=data?.catalog??[];if(rfid)return{label:`RFID已识别 ${rfid.spoolCode}`,confidence:"高",catalog:rfid.catalogCode};const exact=catalog.find(item=>item.material.toUpperCase()===material&&hex&&item.colorHex.slice(0,6).toUpperCase()===hex);if(exact)return{label:`${exact.brand} ${exact.material} · ${exact.colorName}`,confidence:"高",catalog:exact.catalogCode};const sameMaterial=catalog.filter(item=>material&&item.material.toUpperCase()===material);if(sameMaterial.length===1)return{label:`可能是 ${sameMaterial[0].brand} ${sameMaterial[0].colorName}`,confidence:"中",catalog:sameMaterial[0].catalogCode};return{label:material?`${material} · 需要扫码确认实体卷`:"未识别材质 · 需要人工确认",confidence:"低",catalog:""}}
 function openIssue(slot?:Slot){setScanCode("");setDetectedSlot(slot||null);setIssuePositionId(slot?String(slot.id):"");const rfid=slot?.tagUid?eligible.find(spool=>spool.rfidUid===slot.tagUid):null;setIssueSpoolId(rfid?String(rfid.id):"");if(rfid)setScanCode(rfid.spoolCode);setDialog("issue")}
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);if(dialog==="catalog")void mutate({action:"saveCatalog",catalogId:catalogItem?.id,catalogCode:f.get("catalogCode"),brand:f.get("brand"),series:f.get("series"),material:f.get("material"),colorName:f.get("colorName"),colorNameEn:f.get("colorNameEn"),colorCode:f.get("colorCode"),colorHex:f.get("colorHex"),densityGcm3:Number(f.get("densityGcm3")),defaultNetGrams:Number(f.get("defaultNetGrams")),defaultTareGrams:Number(f.get("defaultTareGrams")),amsCompatibility:f.get("amsCompatibility"),tags:f.get("tags")});if(dialog==="receive")void mutate({action:"receiveSpool",catalogItemId:Number(f.get("catalogItemId")),spoolCode:f.get("spoolCode"),lotNo:f.get("lotNo"),costPerKg:Number(f.get("costPerKg")),netGrams:Number(f.get("netGrams")),tareGrams:Number(f.get("tareGrams")),note:f.get("note")});if(dialog==="issue")void mutate({action:"issue",spoolId:Number(issueSpoolId),feedPositionId:Number(issuePositionId)});if(dialog==="feed")void mutate({action:"createFeed",printerId:Number(f.get("printerId")),feedKind:f.get("feedKind"),amsUnit:f.get("amsUnit")===""?null:Number(f.get("amsUnit")),slotIndex:f.get("slotIndex")===""?null:Number(f.get("slotIndex")),toolhead:f.get("toolhead"),label:f.get("label")});if(dialog==="adjust")void mutate({action:f.get("action"),spoolId:actionSpool,grossGrams:Number(f.get("grossGrams")),tareGrams:Number(f.get("tareGrams")),grams:Number(f.get("grams")),note:f.get("note")});if(dialog==="migrate")void mutate({action:"confirmLegacySpool",spoolId:actionSpool,spoolCode:f.get("spoolCode"),physicalState:f.get("physicalState"),netGrams:Number(f.get("netGrams")),tareGrams:Number(f.get("tareGrams"))})}
 if(!data)return <main className="inventory-v2-page"><p className="loading">{error||"正在加载耗材库存…"}</p></main>;
 const low=data.catalog.filter(c=>c.lowStockGrams>0&&c.sealedGrams<=c.lowStockGrams),printerIds=data.printers;
 return <main className="inventory-v2-page">
  <header className="inventory-header"><div><h1>耗材库存</h1><p>未拆封仓库账与在机实体卷分开管理，每次领用、退回、消耗和称重均可追溯。</p></div><a href="/">返回工作台</a></header>
  {error&&<div className="inventory-error">{error}</div>}
  <nav className="inventory-tabs" aria-label="耗材库存主区"><button className={tab==="stock"?"active":""} onClick={()=>setTab("stock")}><span>库存管理</span><small>未拆封 · 采购 · 流水</small></button><button className={tab==="active"?"active":""} onClick={()=>setTab("active")}><span>使用中</span><small>在机 · 周转 · 实时结算</small></button></nav>
  <section className="inventory-kpis"><article><span>未拆封</span><b>{data.summary.sealedSpools}</b><small>{Number(data.summary.sealedGrams).toFixed(0)} g</small></article><article><span>使用中</span><b>{data.summary.inUseSpools}</b><small>实体卷</small></article><article><span>开封周转</span><b>{data.summary.openSpools}</b><small>实体卷</small></article><article><span>组织耗材资产</span><b>{(Number(data.summary.assetGrams)/1000).toFixed(2)}</b><small>kg</small></article><article className={data.summary.needsCount?"warn":""}><span>待盘点迁移</span><b>{data.summary.needsCount}</b><small>旧聚合库存</small></article></section>
  {tab==="stock"?<>
   <div className="inventory-actions"><div><h2>库存管理</h2><p>仓库只统计未拆封实体卷；领用后转入“使用中”，不减少组织总资产。</p></div>{data.canWrite&&<div><button className="secondary" onClick={()=>{setCatalogItem(null);setDialog("catalog")}}>新增耗材目录</button><button onClick={()=>setDialog("receive")}>采购入库 / 新卷</button><a href="/procurement">采购与在途</a></div>}</div>
   <section className="inventory-grid"><article className="inventory-panel span-two"><div className="panel-title"><div><h3>未拆封库存</h3><p>{sealed.length} 个已确认实体卷，可扫码领用到打印机</p></div>{data.canWrite&&<button className="quiet" onClick={()=>openIssue()}>领用 / 调拨</button>}</div><div className="spool-table"><div className="table-head"><span>耗材卷</span><span>材质与颜色</span><span>净重</span><span>仓位</span><span>状态</span></div>{sealed.map(s=><div className="table-row" key={s.id}><span><b>{s.spoolCode}</b><small>{s.catalogCode}</small></span><span className="material-cell"><i style={{background:color(s.colorHex)}}/><b>{s.material} · {s.colorName||"未命名颜色"}</b><small>{s.brand} {s.colorCode}</small></span><span><b>{Number(s.remainingNetGrams).toFixed(0)} g</b><small>初始 {Number(s.initialNetGrams).toFixed(0)} g</small></span><span>{s.locationName}</span><span><span className={`state ${s.state}`}>{stateName[s.state]}</span><button className="label-button" onClick={()=>setLabelSpool(s)}>打印标签</button></span></div>)}{!sealed.length&&<p className="empty">暂无已确认的未拆封实体卷，请登记采购入库。</p>}</div></article>
    {legacy.length>0&&<article className="inventory-panel span-two"><div className="panel-title"><div><h3>待盘点迁移</h3><p>{legacy.length} 条旧聚合库存仅供核对；逐卷称重并登记真实卷码后才可领用。</p></div></div><div className="spool-table"><div className="table-head"><span>历史记录</span><span>材质与颜色</span><span>账面余量</span><span>仓位</span><span>盘点操作</span></div>{legacy.map(s=><div className="table-row" key={s.id}><span><b>{s.spoolCode}</b><small>{s.catalogCode}</small></span><span className="material-cell"><i style={{background:color(s.colorHex)}}/><b>{s.material} · {s.colorName||"未命名颜色"}</b><small>{s.brand} {s.colorCode}</small></span><span><b>{Number(s.remainingNetGrams).toFixed(0)} g</b><small>盘点前不计入未拆封</small></span><span>{s.locationName}</span><span><span className={`state ${s.state}`}>{stateName[s.state]}</span>{data.canWrite&&<button className="quiet" onClick={()=>{setActionSpool(s.id);setDialog("migrate")}}>盘点确认</button>}</span></div>)}</div></article>}
    <article className="inventory-panel"><div className="panel-title"><div><h3>低库存与补货</h3><p>按未拆封净重判断</p></div><a href="/procurement">进入采购</a></div>{low.map(c=><div className="low-row" key={c.id}><i style={{background:color(c.colorHex)}}/><span><b>{c.material} · {c.colorName}</b><small>{c.catalogCode} · 未拆封 {Number(c.sealedGrams).toFixed(0)}g</small></span><strong>建议补货</strong></div>)}{!low.length&&<p className="empty compact">所有耗材均高于安全库存。</p>}</article>
    <article className="inventory-panel"><div className="panel-title"><div><h3>采购在途</h3><p>采购订单未收数量</p></div></div>{data.transit.map(t=><div className="transit-row" key={t.id}><span><b>{t.purchaseNo}</b><small>{t.supplierName}</small></span><strong>{Number(t.incomingGrams).toFixed(0)} g</strong></div>)}{!data.transit.length&&<p className="empty compact">当前没有在途订单。</p>}</article>
   </section>
   <section className="inventory-panel ledger"><div className="panel-title"><div><h3>耗材目录与颜色主数据</h3><p>采购入库、实体卷标签、AMS匹配和成本核算共用同一份品牌、材质、色号与真实色值。</p></div></div><div className="catalog-master-list">{data.catalog.map(item=><div key={item.id}><i style={{background:color(item.colorHex)}}/><span><b>{item.material} · {item.colorName}</b><small>{item.brand} {item.series} · {item.colorCode||"未设置色号"}</small></span><span><b>{item.catalogCode}</b><small>{item.colorHex?`#${item.colorHex}`:"未设置色值"} · {item.defaultNetGrams}g</small></span><em>{amsName[item.amsCompatibility]||"待确认"}</em>{data.canWrite&&<button onClick={()=>{setCatalogItem(item);setDialog("catalog")}}>编辑</button>}</div>)}</div></section>
   <section className="inventory-panel ledger"><div className="panel-title"><div><h3>库存流水</h3><p>领用与退回只转移位置；打印消耗、损耗和报废才改变剩余克重</p></div></div><div className="ledger-list">{data.movements.map(m=><div key={m.id}><span className={`movement ${m.movementType}`}>{m.movementType}</span><span><b>{m.spoolCode} · {m.material} {m.colorName}</b><small>{m.fromLocation||"—"} → {m.toLocation||"—"} · {m.note||"无备注"}</small></span><strong className={m.netGramsDelta<0?"negative":m.netGramsDelta>0?"positive":""}>{m.netGramsDelta>0?"+":""}{Number(m.netGramsDelta).toFixed(1)}g</strong><time>{new Date(m.occurredAt).toLocaleString("zh-CN")}</time></div>)}{!data.movements.length&&<p className="empty compact">暂无 v2 库存流水。</p>}</div></section>
  </>:<>
   <div className="inventory-actions"><div><h2>使用中</h2><p>按打印机、供料位置和工具头查看实体卷；检测到未绑定槽位时只告警，不猜测扣库。</p></div>{data.canWrite&&<div><button onClick={()=>openIssue()}>扫码领用 / 绑定</button><button className="secondary" onClick={()=>setDialog("feed")}>配置供料位</button></div>}</div>
   {data.unboundSlots.length>0&&<section className="binding-alert"><strong>{data.unboundSlots.length} 个供料槽位尚未绑定实体卷</strong><p>系统根据RFID、材质和颜色给出候选，但不会自动选择库存卷或扣减；最终必须扫码确认。</p><div className="ams-detection-list">{data.unboundSlots.map(slot=>{const suggestion=slotSuggestion(slot);return <article key={slot.id}><i style={{background:color(slot.colorHex)}}/><span><b>{slot.printerName} · {slot.feedKind==="external"?(slot.toolhead==="auxiliary"?"辅助工具头外置料盘":"外置料盘"):`AMS ${Number(slot.amsUnit??0)+1}-${Number(slot.slotIndex??0)+1}`}</b><small>{slot.material||"未知材质"} · {slot.remainingPercent==null?"余量未知":`${slot.remainingPercent}%`} · {slot.telemetrySlotId?"实时数据":"等待打印机上报"}</small></span><span><b>{suggestion.label}</b><small>{suggestion.confidence}置信度{suggestion.catalog?` · ${suggestion.catalog}`:""}</small></span>{data.canWrite&&<button onClick={()=>openIssue(slot)}>扫码确认绑定</button>}</article>})}</div></section>}
   <section className="printer-grid">{printerIds.map(printer=><article className="printer-panel" key={printer.id}><header><div><span className="online-dot"/><div><h3>{printer.name}</h3><p>{data.bindings.filter(b=>b.printerName===printer.name).length} 卷已绑定</p></div></div></header><div className="feed-list">{data.positions.filter(p=>p.printerId===printer.id).map(p=>{const b=data.bindings.find(x=>x.feedPositionId===p.id);return <div className={`feed-row ${b?"bound":""}`} key={p.id}><div className="feed-icon"><i style={{background:b?color(b.colorHex):"#e5e9e6"}}/></div><span><b>{feedName(p)}</b><small>{p.label||"供料位置"}</small></span>{b?<><span><b>{b.material} · {b.colorName}</b><small>{b.spoolCode}</small></span><strong>{Number(b.remainingNetGrams).toFixed(0)}g</strong>{data.canWrite&&<button onClick={()=>mutate({action:"return",bindingId:b.id})}>退回</button>}</>:<em>未绑定</em>}</div>})}{!data.positions.some(p=>p.printerId===printer.id)&&<p className="empty compact">尚未配置供料位置。</p>}</div></article>)}{!printerIds.length&&<article className="inventory-panel"><p className="empty">尚无组织供料位置。请先配置打印机 AMS 或外置料盘。</p></article>}</section>
   <section className="inventory-grid active-lower"><article className="inventory-panel"><div className="panel-title"><div><h3>已开封周转</h3><p>退回后不重新计入未拆封库存</p></div></div>{open.map(s=><div className="open-row" key={s.id}><i style={{background:color(s.colorHex)}}/><span><b>{s.spoolCode} · {s.material} {s.colorName}</b><small>最近称重 {s.lastWeighedAt?new Date(s.lastWeighedAt).toLocaleDateString("zh-CN"):"未校准"}</small></span><strong>{Number(s.remainingNetGrams).toFixed(0)}g</strong><button onClick={()=>setLabelSpool(s)}>标签</button>{data.canWrite&&<button onClick={()=>{setActionSpool(s.id);setDialog("adjust")}}>盘点 / 损耗</button>}</div>)}{!open.length&&<p className="empty compact">暂无开封周转卷。</p>}</article>
    <article className="inventory-panel span-two"><div className="panel-title"><div><h3>实时预留与任务结算</h3><p>切片预计只作预留；绑定实体卷后才允许形成正式结算</p></div></div><div className="usage-list">{data.usage.map(u=><div key={u.id}><span><b>{u.filename||`打印会话 #${u.printSessionId}`}</b><small>{u.printerName} · {purposeName[u.purpose]||u.purpose} · {u.toolhead}</small></span><span><b>{u.spoolCode||"未绑定实体卷"}</b><small>{u.estimateSource} 数据源</small></span><span><small>预计 / 结算 / 称重</small><b>{Number(u.estimatedGrams).toFixed(1)} / {u.settledGrams==null?"—":Number(u.settledGrams).toFixed(1)} / {u.measuredGrams==null?"—":Number(u.measuredGrams).toFixed(1)} g</b></span><strong className={u.spoolId?"ok":"warning"}>{u.spoolId?u.settledAt?"已结算":"已预留":"待绑定"}</strong></div>)}{!data.usage.length&&<p className="empty compact">尚无打印材料用量记录。</p>}</div></article>
   </section>
  </>}
  {dialog&&<div className="inventory-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDialog(null)}><form className="inventory-modal" onSubmit={submit}><header><div><h2>{{receive:"采购入库 / 新增实体卷",issue:"领用并绑定打印机",feed:"配置供料位置",adjust:"盘点、损耗与报废",migrate:"历史库存实物盘点",catalog:catalogItem?"编辑耗材目录":"新增耗材目录"}[dialog]}</h2><p>{dialog==="issue"?"领用减少未拆封卷数，但不减少组织耗材资产。":dialog==="migrate"?"本次确认仅适用于一条历史记录对应一个实体卷；重量差异会自动形成盘点流水。":dialog==="catalog"?"色号与真实色值将同步用于库存卡片、实体卷标签和AMS匹配。":"所有重量调整都会留下不可变流水。"}</p></div><button type="button" onClick={()=>setDialog(null)}>×</button></header><div className="modal-fields">
   {dialog==="catalog"&&<><label>目录编码<input name="catalogCode" required defaultValue={catalogItem?.catalogCode} placeholder="BAMBU-PLA-BASIC-10100"/></label><label>品牌<input name="brand" required defaultValue={catalogItem?.brand||"Bambu Lab"}/></label><label>系列<input name="series" defaultValue={catalogItem?.series} placeholder="PLA Basic"/></label><label>材质<input name="material" required defaultValue={catalogItem?.material||"PLA"}/></label><label>颜色名称<input name="colorName" required defaultValue={catalogItem?.colorName} placeholder="玉石白"/></label><label>英文颜色名<input name="colorNameEn" defaultValue={catalogItem?.colorNameEn} placeholder="Jade White"/></label><label>官方色号<input name="colorCode" defaultValue={catalogItem?.colorCode} placeholder="10100"/></label><label>真实色值 HEX<input name="colorHex" required pattern="^#?[0-9A-Fa-f]{6}$" defaultValue={catalogItem?.colorHex?`#${catalogItem.colorHex}`:"#FFFFFF"}/></label><label>密度（g/cm³）<input name="densityGcm3" type="number" min="0.1" max="5" step="0.001" required defaultValue={catalogItem?.densityGcm3||1.24}/></label><label>默认净重（g）<input name="defaultNetGrams" type="number" min="1" step="0.1" required defaultValue={catalogItem?.defaultNetGrams||1000}/></label><label>默认空盘重量（g）<input name="defaultTareGrams" type="number" min="0" step="0.1" required defaultValue={catalogItem?.defaultTareGrams||0}/></label><label>AMS兼容性<select name="amsCompatibility" defaultValue={catalogItem?.amsCompatibility||"unknown"}><option value="compatible">兼容</option><option value="conditional">有条件兼容</option><option value="incompatible">不兼容</option><option value="unknown">待确认</option></select></label><label className="wide">标签<input name="tags" defaultValue={catalogItem?tagText(catalogItem.tags):""} placeholder="官方, 常用, 哑光"/></label></>}
   {dialog==="receive"&&<><label>耗材目录<select name="catalogItemId" required><option value="">请选择</option>{data.catalog.map(c=><option value={c.id} key={c.id}>{c.catalogCode} · {c.material} {c.colorName}</option>)}</select></label><label>实体卷编号<input name="spoolCode" required placeholder="FIL-202607-001"/></label><label>采购批次<input name="lotNo" placeholder="LOT-202607-01"/></label><label>采购成本（RM/kg）<input name="costPerKg" type="number" min="0" step="0.01"/></label><label>净重（g）<input name="netGrams" type="number" min="1" defaultValue="1000" required/></label><label>空盘重量（g）<input name="tareGrams" type="number" min="0" defaultValue="0" required/></label><label className="wide">备注<input name="note" placeholder="采购单、批次或验收备注"/></label></>}
   {dialog==="issue"&&<>{detectedSlot&&<div className="detected-slot wide"><i style={{background:color(detectedSlot.colorHex)}}/><span><b>打印机检测：{detectedSlot.material||"未知材质"}</b><small>{slotSuggestion(detectedSlot).label} · {slotSuggestion(detectedSlot).confidence}置信度，仅供核对</small></span></div>}<label className="wide">扫码或输入实体卷码<input value={scanCode} onChange={event=>scan(event.target.value)} autoFocus placeholder="扫描 LT:SPOOL:FIL-... 或直接输入卷码"/><small className={scanCode&&!issueSpoolId?"scan-miss":"scan-hint"}>{scanCode&&!issueSpoolId?"未找到可领用实体卷，请检查卷码或盘点状态。":"扫码后系统会自动选中实体卷。"}</small></label><label>实体耗材卷<select name="spoolId" required value={issueSpoolId} onChange={event=>{setIssueSpoolId(event.target.value);const selected=eligible.find(s=>String(s.id)===event.target.value);setScanCode(selected?.spoolCode||"")}}><option value="">请选择</option>{eligible.map(s=><option key={s.id} value={s.id}>{s.spoolCode} · {s.material} {s.colorName} · {s.remainingNetGrams}g</option>)}</select></label><label>打印机供料位置<select name="feedPositionId" required value={issuePositionId} onChange={event=>setIssuePositionId(event.target.value)}><option value="">请选择</option>{data.positions.map(p=><option key={p.id} value={p.id}>{p.printerName} · {feedName(p)}</option>)}</select></label></>}
   {dialog==="feed"&&<><label>组织打印机<select name="printerId" required><option value="">请选择</option>{printerIds.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>供料方式<select name="feedKind"><option value="ams">AMS</option><option value="ams_lite">AMS Lite</option><option value="ams_ht">AMS HT</option><option value="external">外置料盘</option></select></label><label>AMS 单元（从0开始）<input name="amsUnit" type="number" min="0"/></label><label>槽位（从0开始）<input name="slotIndex" type="number" min="0"/></label><label>工具头<select name="toolhead"><option value="main">主工具头</option><option value="auxiliary">辅助工具头</option><option value="left">左工具头</option><option value="right">右工具头</option></select></label><label>位置名称<input name="label" placeholder="辅助挤出机外置料盘"/></label></>}
   {dialog==="adjust"&&<><label>操作<select name="action"><option value="weigh">称重盘点</option><option value="loss">登记损耗</option><option value="scrap">报废耗材</option></select></label><label>毛重（g）<input name="grossGrams" type="number" min="0"/></label><label>空盘重量（g）<input name="tareGrams" type="number" min="0"/></label><label>损耗/报废重量（g）<input name="grams" type="number" min="0"/></label><label className="wide">原因<input name="note" placeholder="受潮、缠料、污染、盘点差异…"/></label></>}
   {dialog==="migrate"&&<><label>真实实体卷码<input name="spoolCode" required placeholder="FIL-202607-001"/></label><label>实物状态<select name="physicalState" defaultValue="open_storage"><option value="open_storage">已开封周转</option><option value="sealed">未拆封</option></select></label><label>实际净重（g）<input name="netGrams" type="number" min="0" step="0.1" required/></label><label>空盘重量（g）<input name="tareGrams" type="number" min="0" step="0.1" defaultValue="0" required/></label></>}
  </div><footer><button type="button" onClick={()=>setDialog(null)}>取消</button><button className="primary" disabled={busy}>{busy?"保存中…":dialog==="catalog"?"保存耗材目录":"确认并保存流水"}</button></footer></form></div>}
  {labelSpool?<SpoolLabel spool={labelSpool} onClose={()=>setLabelSpool(null)}/>:null}
 </main>
}
