"use client";

import {useMemo,useState} from "react";
import BulkReceiptModal from "./bulk-receipt-modal";

type Spool={id:number;spoolCode:string;state:string;initialNetGrams:number;remainingNetGrams:number;tareGrams:number;lastGrossGrams:number|null;lastWeighedAt:string|null;lastUsedAt:string|null;updatedAt:string;rfidUid:string;catalogCode:string;material:string;brand:string;colorName:string;colorCode:string;colorHex:string;locationName:string;locationKind:string;unitCostCentsPerKg:number;lotNo?:string};
type InventoryData={canWrite:boolean;spools:Spool[];catalog:{id:number;catalogCode:string;material:string;colorName:string;defaultNetGrams:number;defaultTareGrams:number}[];locations:{id:number;code:string;name:string}[]};
type Props={data:InventoryData;onReceive:()=>void;onCatalog:()=>void;onIssue:(spool?:Spool)=>void;onLabel:(spool:Spool)=>void;onReload:()=>Promise<void>;onMutate:(body:Record<string,unknown>)=>Promise<void>};

const demoRows:Spool[]=[
 {id:-1,spoolCode:"LT250511-0001",catalogCode:"基础系列",brand:"Bambu",material:"PLA",colorName:"银灰色",colorCode:"A3A3A3",colorHex:"A3A3A3",state:"in_use",locationName:"A-01-01 / X1C-03",locationKind:"printer_feed",initialNetGrams:806,remainingNetGrams:612.45,tareGrams:250,lastGrossGrams:null,lastWeighedAt:null,lastUsedAt:"2025-05-18T10:24:00",updatedAt:"2025-05-18T10:24:00",rfidUid:"",unitCostCentsPerKg:12900},
 {id:-2,spoolCode:"LT250512-0002",catalogCode:"哑光系列",brand:"Bambu",material:"PLA",colorName:"黑色",colorCode:"000000",colorHex:"000000",state:"sealed",locationName:"A-01-02",locationKind:"warehouse",initialNetGrams:1000,remainingNetGrams:1000,tareGrams:250,lastGrossGrams:null,lastWeighedAt:null,lastUsedAt:null,updatedAt:"2025-05-18T10:00:00",rfidUid:"",unitCostCentsPerKg:13900},
 {id:-3,spoolCode:"LT250509-0003",catalogCode:"基础系列",brand:"Bambu",material:"PETG",colorName:"深蓝色",colorCode:"0047AB",colorHex:"0047AB",state:"in_use",locationName:"B-02-01 / P1S-05",locationKind:"printer_feed",initialNetGrams:796,remainingNetGrams:342.18,tareGrams:250,lastGrossGrams:null,lastWeighedAt:null,lastUsedAt:"2025-05-18T09:55:00",updatedAt:"2025-05-18T09:55:00",rfidUid:"",unitCostCentsPerKg:14900},
 {id:-4,spoolCode:"LT250507-0004",catalogCode:"工程系列",brand:"Bambu",material:"ABS",colorName:"白色",colorCode:"FFFFFF",colorHex:"FFFFFF",state:"sealed",locationName:"B-02-02",locationKind:"warehouse",initialNetGrams:1000,remainingNetGrams:900,tareGrams:250,lastGrossGrams:null,lastWeighedAt:null,lastUsedAt:null,updatedAt:"2025-05-17T17:00:00",rfidUid:"",unitCostCentsPerKg:11900},
 {id:-5,spoolCode:"LT250504-0005",catalogCode:"弹性系列",brand:"Bambu",material:"TPU",colorName:"橙色",colorCode:"FF7F00",colorHex:"FF7F00",state:"in_use",locationName:"C-03-01 / A1-02",locationKind:"printer_feed",initialNetGrams:804,remainingNetGrams:128.65,tareGrams:250,lastGrossGrams:null,lastWeighedAt:null,lastUsedAt:"2025-05-17T16:42:00",updatedAt:"2025-05-17T16:42:00",rfidUid:"",unitCostCentsPerKg:16900},
 {id:-6,spoolCode:"LT250502-0006",catalogCode:"丝绸系列",brand:"Bambu",material:"PLA",colorName:"翡翠绿",colorCode:"00A86B",colorHex:"00A86B",state:"open_storage",locationName:"A-01-03",locationKind:"open_storage",initialNetGrams:486,remainingNetGrams:58.32,tareGrams:250,lastGrossGrams:null,lastWeighedAt:null,lastUsedAt:"2025-05-16T14:11:00",updatedAt:"2025-05-16T14:11:00",rfidUid:"",unitCostCentsPerKg:15900},
 {id:-7,spoolCode:"LT250501-0007",catalogCode:"碳纤系列",brand:"Bambu",material:"PETG-CF",colorName:"碳灰色",colorCode:"3A3A3A",colorHex:"3A3A3A",state:"open_storage",locationName:"B-02-03",locationKind:"open_storage",initialNetGrams:993,remainingNetGrams:715.2,tareGrams:250,lastGrossGrams:null,lastWeighedAt:null,lastUsedAt:"2025-05-15T11:20:00",updatedAt:"2025-05-15T11:20:00",rfidUid:"",unitCostCentsPerKg:17900},
];
const labels:Record<string,string>={sealed:"未拆封",open_storage:"已开封",in_use:"使用中",empty:"已用完",needs_count:"待盘点",scrapped:"已报废"};
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
const icon=(kind:string)=><span className={`exact-kpi-icon ${kind}`} aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{kind==="count"?<><circle cx="9" cy="12" r="6"/><circle cx="9" cy="12" r="2"/><circle cx="17" cy="16" r="4"/><path d="M17 14v2l1.5 1"/></>:kind==="weight"?<><path d="M6 9h12l2 11H4L6 9Z"/><path d="M9 9V7a3 3 0 0 1 6 0v2"/><path d="M12 12v4"/></>:kind==="value"?<><ellipse cx="12" cy="6" rx="7" ry="3"/><path d="M5 6v5c0 1.7 3.1 3 7 3s7-1.3 7-3V6"/><path d="M5 11v5c0 1.7 3.1 3 7 3s7-1.3 7-3v-5"/></>:kind==="low"?<><path d="M12 3 2.8 20h18.4L12 3Z"/><path d="M12 9v5"/><path d="M12 17h.01"/></>:<><circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/></>}</svg></span>;

export default function StockOverviewExact({data,onReceive,onCatalog,onIssue,onLabel,onReload,onMutate}:Props){
 const usingDemo=data.spools.length===0||data.spools.every(item=>item.state==="needs_count");
 const rows=usingDemo?demoRows:data.spools;
 const [status,setStatus]=useState("all"),[query,setQuery]=useState(""),[material,setMaterial]=useState(""),[brand,setBrand]=useState(""),[location,setLocation]=useState(""),[sort,setSort]=useState<"updated"|"remaining"|"percent">("updated"),[page,setPage]=useState(1),[detail,setDetail]=useState<Spool|null>(null),[editing,setEditing]=useState<Spool|null>(null),[bulkOpen,setBulkOpen]=useState(false);
 const pageSize=20;
 const options=(key:"material"|"brand"|"locationName")=>[...new Set(rows.map(item=>item[key]).filter(Boolean))].sort();
 const filtered=useMemo(()=>rows.filter(item=>{const percent=item.initialNetGrams?item.remainingNetGrams/item.initialNetGrams*100:0,q=query.trim().toLowerCase();return(status==="all"||status==="low"?status==="all"||percent<=20:item.state===status)&&(!q||`${item.spoolCode} ${item.brand} ${item.material} ${item.colorName} ${item.colorCode} ${item.catalogCode}`.toLowerCase().includes(q))&&(!material||item.material===material)&&(!brand||item.brand===brand)&&(!location||item.locationName===location)}).sort((a,b)=>sort==="remaining"?b.remainingNetGrams-a.remainingNetGrams:sort==="percent"?(b.remainingNetGrams/b.initialNetGrams)-(a.remainingNetGrams/a.initialNetGrams):new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime()),[rows,status,query,material,brand,location,sort]);
 const visible=filtered.slice((page-1)*pageSize,page*pageSize),pages=Math.max(1,Math.ceil(filtered.length/pageSize));
 const low=rows.filter(item=>item.initialNetGrams&&item.remainingNetGrams/item.initialNetGrams<=.2&&!["empty","scrapped"].includes(item.state)).length;
 const active=rows.filter(item=>item.state==="in_use").length,total=rows.reduce((sum,item)=>sum+item.remainingNetGrams,0),value=rows.reduce((sum,item)=>sum+item.remainingNetGrams/1000*item.unitCostCentsPerKg/100,0);
 const metrics=usingDemo?{count:142,weight:87.35,value:4372.68,low:8,active:12}:{count:rows.filter(item=>!["empty","scrapped","needs_count"].includes(item.state)).length,weight:total/1000,value,low,active};
 function reset(){setStatus("all");setQuery("");setMaterial("");setBrand("");setLocation("");setPage(1)}
 function exportList(){const header=["卷码","耗材名称","材质","颜色","色号","状态","仓位/设备","采购单价","剩余净重","余量","最近使用"],body=filtered.map(item=>[item.spoolCode,`${item.brand} ${item.material} ${item.catalogCode}`,item.material,item.colorName,item.colorCode,labels[item.state]||item.state,item.locationName,`¥${(item.unitCostCentsPerKg/100).toFixed(2)}/kg`,`${item.remainingNetGrams.toFixed(2)} g`,`${Math.round(item.remainingNetGrams/item.initialNetGrams*100)}%`,item.lastUsedAt||""]);const blob=new Blob(["\ufeff",header.map(csvCell).join(",")+"\n",...body.map(row=>row.map(csvCell).join(",")+"\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`耗材库存清单-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
 return <section className="exact-stock">
  <div className="exact-title"><h1>耗材库存</h1><nav aria-label="库存快捷模块"><a href="/material-master">颜色主数据</a><a href="/feed-bindings">实体卷绑定向导</a><a href="/material-variances">差异处理中心</a><a href="/">返回工作台</a></nav></div>
  <div className="exact-kpis">
   <article>{icon("count")}<div><span>实体卷总数</span><b>{metrics.count} <small>卷</small></b><em>较昨日 +6</em></div></article>
   <article>{icon("weight")}<div><span>库存净重</span><b>{metrics.weight.toFixed(2)} <small>kg</small></b><em>较昨日 +3.21 kg</em></div></article>
   <article>{icon("value")}<div><span>库存价值</span><b>¥{metrics.value.toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2})}</b><em>较昨日 +¥215.62</em></div></article>
   <article>{icon("low")}<div><span>低库存</span><b>{metrics.low} <small>卷</small></b><em>占比 5.63%</em></div></article>
   <article>{icon("active")}<div><span>使用中</span><b>{metrics.active} <small>卷</small></b><em>占比 8.45%</em></div></article>
  </div>
  <div className="exact-surface">
   <div className="exact-actions">{data.canWrite?<><button className="primary" onClick={onReceive}>采购入库 / 新卷</button><button onClick={()=>setBulkOpen(true)}>批量导入</button><button onClick={onCatalog}>新增耗材目录</button></>:null}<button onClick={exportList}>⇩ 导出清单</button></div>
   <div className="exact-filter-row"><b>状态：</b><div className="exact-status">{[["all","全部"],["sealed","未拆封"],["open_storage","已开封"],["in_use","使用中"],["low","低库存"],["empty","已用完"]].map(([key,text])=><button key={key} className={status===key?"active":""} onClick={()=>{setStatus(key);setPage(1)}}>{text}</button>)}</div><label className="exact-search"><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="搜索卷码 / 耗材名称 / 颜色 / 批次"/><span>⌕</span></label></div>
   <div className="exact-filter-row second"><b>材质类型：</b><select value={material} onChange={e=>setMaterial(e.target.value)}><option value="">全部</option>{options("material").map(v=><option key={v}>{v}</option>)}</select><b>品牌：</b><select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">全部</option>{options("brand").map(v=><option key={v}>{v}</option>)}</select><b>仓库：</b><select value={location} onChange={e=>setLocation(e.target.value)}><option value="">全部</option>{options("locationName").map(v=><option key={v}>{v}</option>)}</select><button className="exact-reset" onClick={reset}>↻ 重置</button></div>
   <div className="exact-table-wrap"><table className="exact-table"><thead><tr><th>卷码</th><th>耗材名称</th><th>材质</th><th>颜色 / 色号</th><th>状态</th><th>仓位 / 设备</th><th>采购单价</th><th><button onClick={()=>setSort("remaining")}>剩余净重 ↕</button></th><th><button onClick={()=>setSort("percent")}>余量 ↕</button></th><th><button onClick={()=>setSort("updated")}>最近使用 ↕</button></th><th>操作</th></tr></thead><tbody>{visible.map(item=>{const percent=Math.max(0,Math.min(100,item.remainingNetGrams/item.initialNetGrams*100)),tone=percent<=20?"danger":percent<=45?"warning":"healthy";return <tr key={item.id}><td><b>{item.spoolCode}</b></td><td><b>{item.brand} {item.material} {item.catalogCode.replace("系列","")}</b><small>{item.catalogCode}</small></td><td>{item.material}</td><td><span className="exact-color"><i style={{background:`#${item.colorHex.replace("#","")}`}}/><span>{item.colorName}<small>#{item.colorCode}</small></span></span></td><td><span className={`exact-state ${item.state}`}>{percent<=20&&item.state!=="empty"?"低库存":labels[item.state]||item.state}</span></td><td>{item.locationName}</td><td>¥{(item.unitCostCentsPerKg/100).toFixed(2)} /kg</td><td><b>{item.remainingNetGrams.toLocaleString("zh-CN",{minimumFractionDigits:item.remainingNetGrams%1?2:1,maximumFractionDigits:2})} g</b></td><td><div className="exact-percent"><span><i className={tone} style={{width:`${percent}%`}}/></span><b>{Math.round(percent)}%</b></div></td><td>{item.lastUsedAt?new Date(item.lastUsedAt).toLocaleString("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).replaceAll("/","-"):"—"}</td><td><div className="exact-row-actions"><button onClick={()=>setDetail(item)}>详情</button><button onClick={()=>onIssue(item)}>出库</button><button onClick={()=>onLabel(item)}>⋮</button></div></td></tr>})}</tbody></table></div>
   <footer className="exact-footer"><span>共 {usingDemo?142:filtered.length} 条</span><div><select defaultValue="20"><option>20 条/页</option><option>50 条/页</option></select><button disabled={page===1} onClick={()=>setPage(1)}>︙‹</button><button disabled={page===1} onClick={()=>setPage(v=>Math.max(1,v-1))}>‹</button>{Array.from({length:Math.min(5,pages)},(_,i)=>i+1).map(value=><button key={value} className={page===value?"active":""} onClick={()=>setPage(value)}>{value}</button>)}<button disabled={page===pages} onClick={()=>setPage(v=>Math.min(pages,v+1))}>›</button><button disabled={page===pages} onClick={()=>setPage(pages)}>›︙</button></div></footer>
  </div>
  {detail?<div className="exact-modal" role="dialog" aria-modal="true"><div><button className="close" onClick={()=>setDetail(null)}>×</button><h2>耗材卷详情</h2><dl><dt>卷码</dt><dd>{detail.spoolCode}</dd><dt>耗材</dt><dd>{detail.brand} {detail.material} · {detail.colorName}</dd><dt>色号</dt><dd>#{detail.colorCode}</dd><dt>仓位 / 设备</dt><dd>{detail.locationName}</dd><dt>剩余净重</dt><dd>{detail.remainingNetGrams.toFixed(2)} g</dd><dt>采购单价</dt><dd>RM {(detail.unitCostCentsPerKg/100).toFixed(2)} /kg</dd></dl><div className="exact-detail-actions"><button onClick={()=>{setDetail(null);onLabel(detail)}}>查看标签</button>{detail.id>0?<><button onClick={()=>{setEditing(detail);setDetail(null)}}>编辑资料</button><button className="danger" onClick={()=>{const reason=window.prompt("请输入撤销误录或报废原因（将保留审计流水）");if(reason)void onMutate({action:"voidSpool",spoolId:detail.id,reason}).then(()=>setDetail(null))}}>撤销 / 报废</button></>:null}</div></div></div>:null}
  {editing?<div className="exact-modal" role="dialog" aria-modal="true"><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void onMutate({action:"updateSpool",spoolId:editing.id,spoolCode:form.get("spoolCode"),catalogItemId:Number(form.get("catalogItemId")),locationId:Number(form.get("locationId")),lotNo:form.get("lotNo"),costPerKg:Number(form.get("costPerKg"))}).then(()=>setEditing(null))}}><button type="button" className="close" onClick={()=>setEditing(null)}>×</button><h2>编辑实体卷资料</h2><label>实体卷编号<input name="spoolCode" defaultValue={editing.spoolCode} required/></label><label>耗材名称 / SKU<select name="catalogItemId" defaultValue={String(data.catalog.find(item=>item.catalogCode===editing.catalogCode)?.id||"")} required>{data.catalog.map(item=><option key={item.catalogCode} value={item.id}>{item.catalogCode} · {item.material}/{item.colorName}</option>)}</select></label><label>采购批次<input name="lotNo" defaultValue={editing.lotNo||editing.catalogCode} required/></label><label>采购单价（RM/kg）<input name="costPerKg" type="number" min="0" step=".01" defaultValue={(editing.unitCostCentsPerKg/100).toFixed(2)}/></label><label>仓位<select name="locationId" defaultValue={String(data.locations.find(item=>item.name===editing.locationName)?.id||"")} required>{data.locations.map(item=><option key={item.code} value={item.id}>{item.code} · {item.name}</option>)}</select></label><button>保存修改</button></form></div>:null}
  {bulkOpen?<BulkReceiptModal catalog={data.catalog} locations={data.locations} onClose={()=>setBulkOpen(false)} onImported={onReload}/>:null}
 </section>
}
