import {getD1} from "../db";type Check={key:string;label:string;count:number;severity:"critical"|"warning"|"info";deduction:number;detail:string;href:string};
export async function getDataQualityReport(organizationId:number){const db=getD1(),[settlements,feeds,costs,reconciliation,variances,offers,devices,unknownCosts]=await Promise.all([
 db.prepare(`SELECT COUNT(DISTINCT ps.id) count FROM print_sessions ps JOIN print_material_usage_lines u ON u.print_session_id=ps.id AND u.organization_id=ps.organization_id WHERE ps.organization_id=? AND ps.status IN ('completed','failed','cancelled') AND u.settled_at IS NULL`).bind(organizationId).first<{count:number}>(),
 db.prepare(`SELECT COUNT(*) count FROM printer_feed_positions f JOIN bambu_ams_slots a ON a.printer_id=f.printer_id AND a.active=1 AND ((f.feed_kind<>'external' AND a.ams_unit=COALESCE(f.ams_unit,0) AND a.tray_index=COALESCE(f.slot_index,0)) OR (f.feed_kind='external' AND a.ams_unit=CASE WHEN f.toolhead='auxiliary' THEN 254 ELSE 255 END)) WHERE f.organization_id=? AND f.active=1 AND NOT EXISTS(SELECT 1 FROM spool_bindings b WHERE b.organization_id=f.organization_id AND b.feed_position_id=f.id AND b.status='active')`).bind(organizationId).first<{count:number}>(),
 db.prepare("SELECT COUNT(*) count FROM purchase_orders WHERE organization_id=? AND status IN ('ordered','partially_received') AND cost_status='pending'").bind(organizationId).first<{count:number}>(),
 db.prepare("SELECT COUNT(*) count FROM purchase_orders WHERE organization_id=? AND status='completed' AND reconciliation_status NOT IN ('matched','approved')").bind(organizationId).first<{count:number}>(),
 db.prepare("SELECT COUNT(*) count FROM material_variance_cases WHERE organization_id=? AND status='open'").bind(organizationId).first<{count:number}>(),
 db.prepare(`SELECT COUNT(*) count FROM material_catalog_items c WHERE c.organization_id=? AND c.status='active' AND NOT EXISTS(SELECT 1 FROM supplier_material_offers o WHERE o.organization_id=c.organization_id AND o.catalog_item_id=c.id AND o.status='active' AND o.valid_from<=date('now') AND (o.valid_until IS NULL OR o.valid_until>=date('now')))`).bind(organizationId).first<{count:number}>(),
 db.prepare(`SELECT COUNT(*) count FROM printers p JOIN printer_bindings b ON b.printer_id=p.id WHERE b.organization_id=? AND b.status!='disabled' AND p.connector_type!='manual' AND (p.last_seen_at IS NULL OR datetime(p.last_seen_at)<datetime('now','-2 minutes'))`).bind(organizationId).first<{count:number}>(),
 db.prepare(`SELECT COUNT(*) count FROM material_spools s LEFT JOIN material_purchase_lots l ON l.id=s.purchase_lot_id AND l.organization_id=s.organization_id WHERE s.organization_id=? AND s.remaining_net_grams>0 AND COALESCE(l.unit_cost_cents_per_kg,0)=0`).bind(organizationId).first<{count:number}>(),
]);const raw:Array<Omit<Check,"count"|"deduction">&{count:number;weight:number}>=[
 {key:"unsettled",label:"打印耗材未结算",count:Number(settlements?.count??0),severity:"critical",weight:12,detail:"成品成本、耗材余量和利润仍不完整",href:"/settlements"},{key:"unbound",label:"供料位未绑定实体卷",count:Number(feeds?.count??0),severity:"critical",weight:12,detail:"系统不能安全扣减对应实体卷库存",href:"/feed-bindings"},{key:"cost",label:"采购成本待审批",count:Number(costs?.count??0),severity:"warning",weight:6,detail:"到岸成本尚未成为可收货的确认成本",href:"/procurement"},{key:"reconciliation",label:"收货发票未对账",count:Number(reconciliation?.count??0),severity:"warning",weight:6,detail:"库存成本与应付账款可能仍有差异",href:"/procurement"},{key:"variance",label:"库存线下核对待更新",count:Number(variances?.count??0),severity:"critical",weight:10,detail:"请在线下核对后到库存总览编辑实体卷余量",href:"/inventory"},{key:"offers",label:"耗材缺少有效报价",count:Number(offers?.count??0),severity:"info",weight:3,detail:"补货预测无法形成可靠资金估算",href:"/procurement"},{key:"devices",label:"设备数据中断",count:Number(devices?.count??0),severity:"critical",weight:12,detail:"实时打印状态、AMS和用量数据可能过期",href:"/monitor"},{key:"unknown-cost",label:"库存卷缺少采购成本",count:Number(unknownCosts?.count??0),severity:"warning",weight:5,detail:"库存价值与产品成本会被低估",href:"/inventory-value"}];const checks:Check[]=raw.map(({weight,...row})=>({...row,deduction:Math.min(weight*3,row.count*weight)})),deduction=checks.reduce((sum,row)=>sum+row.deduction,0),score=Math.max(0,100-deduction);return {generatedAt:new Date().toISOString(),score,grade:score>=90?"可信":score>=75?"需关注":score>=50?"不完整":"高风险",openIssues:checks.reduce((sum,row)=>sum+row.count,0),critical:checks.filter(row=>row.severity==="critical"&&row.count>0).length,checks,method:"每类问题按影响扣分，并设置单类扣分上限；0条问题不扣分。评分只反映数据完整性，不代表经营业绩。"}}
