"use client";
import {useCallback,useEffect,useState} from "react";
type Outcome={id:number;jobNo:string;successfulQuantity:number};type Lot={id:number;lotNo:string;totalQuantity:number;availableQuantity:number};type Shipment={id:number;shipmentNo:string;status:string;recipientName:string};type Item={id:number;shipmentId:number;lotId:number;lotNo:string;requestedQuantity:number;pickedQuantity:number;shippedQuantity:number};
type Data={canOperate:boolean;outcomes:Outcome[];lots:Lot[];shipments:Shipment[];items:Item[]};
const labels:Record<string,string>={draft:"待拣货",picking:"拣货中",partially_shipped:"部分发货",shipped:"已发货",delivered:"已签收",cancelled:"已取消"};
export default function FulfillmentClient(){const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);const load=useCallback(async()=>{const response=await fetch("/api/fulfillment",{cache:"no-store"}),value=await response.json();if(!response.ok)throw new Error(value.error);setData(value)},[]);useEffect(()=>{load().catch(e=>setError(e.message))},[load]);async function mutate(method:"POST"|"PATCH",body:Record<string,unknown>){setBusy(true);setError("");try{const response=await fetch("/api/fulfillment",{method,headers:{"content-type":"application/json"},body:JSON.stringify({...body,idempotencyKey:crypto.randomUUID()})}),value=await response.json();if(!response.ok)throw new Error(value.error);await load()}catch(e){setError(e instanceof Error?e.message:"操作失败")}finally{setBusy(false)}}if(!data)return <main className="fulfillment"><p>{error||"正在加载交付中心…"}</p></main>;
return <main className="fulfillment"><header><div><small>FULFILLMENT · TRACEABLE DELIVERY</small><h1>成品库存与交付中心</h1><p>质量结算、良品入库、分批拣货、发货和签收全程可追溯。</p></div><a href="/">返回工作台</a></header>{error&&<div className="error">{error}</div>}<section className="stats"><article><span>待入库良品</span><b>{data.outcomes.length}</b></article><article><span>可用成品</span><b>{data.lots.reduce((s,x)=>s+x.availableQuantity,0)}</b></article><article><span>进行中发货</span><b>{data.shipments.filter(x=>!["delivered","cancelled"].includes(x.status)).length}</b></article></section>
<div className="grid"><section className="panel"><small>QUALITY RELEASE</small><h2>良品入库</h2>{data.outcomes.length===0?<p className="empty">暂无待入库的质量结算良品</p>:data.outcomes.map(o=><article className="row" key={o.id}><div><b>{o.jobNo}</b><span>良品 {o.successfulQuantity} 件</span></div>{data.canOperate&&<button disabled={busy} onClick={()=>mutate("POST",{action:"receive",outcomeId:o.id,lotNo:`FG-${o.id}`})}>确认入库</button>}</article>)}</section><section className="panel"><small>CREATE SHIPMENT</small><h2>新建发货单</h2>{data.canOperate&&data.lots.some(x=>x.availableQuantity>0)?<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate("POST",{action:"create_shipment",shipmentNo:f.get("shipmentNo"),recipientName:f.get("recipientName"),address:f.get("address"),items:[{lotId:Number(f.get("lotId")),quantity:Number(f.get("quantity"))}]})}}><input name="shipmentNo" required placeholder="发货单号"/><input name="recipientName" required placeholder="收件人"/><select name="lotId" required>{data.lots.filter(x=>x.availableQuantity>0).map(x=><option key={x.id} value={x.id}>{x.lotNo} · 可用 {x.availableQuantity}</option>)}</select><input name="quantity" type="number" min="1" required placeholder="数量"/><input name="address" placeholder="收货地址"/><button disabled={busy}>创建发货单</button></form>:<p className="empty">暂无可发成品</p>}</section></div>
<section className="panel"><small>SHIPMENT BOARD</small><h2>交付进度</h2>{data.shipments.map(s=><article className="shipment" key={s.id}><div className="shipment-head"><div><b>{s.shipmentNo} · {s.recipientName}</b><span>{labels[s.status]||s.status}</span></div>{data.canOperate&&!['shipped','delivered','cancelled'].includes(s.status)&&<button className="quiet" disabled={busy} onClick={()=>mutate("PATCH",{action:"cancel",shipmentId:s.id})}>取消并释放</button>}{data.canOperate&&s.status==='shipped'&&<button disabled={busy} onClick={()=>mutate("PATCH",{action:"deliver",shipmentId:s.id})}>确认签收</button>}</div>{data.items.filter(i=>i.shipmentId===s.id).map(i=><div className="item" key={i.id}><span>{i.lotNo} · 已拣 {i.pickedQuantity}/{i.requestedQuantity} · 已发 {i.shippedQuantity}</span><div>{data.canOperate&&!['shipped','delivered','cancelled'].includes(s.status)&&i.pickedQuantity<i.requestedQuantity&&<button disabled={busy} onClick={()=>mutate("PATCH",{action:"pick",shipmentId:s.id,itemId:i.id,quantity:i.requestedQuantity-i.pickedQuantity})}>拣货</button>}{data.canOperate&&!['shipped','delivered','cancelled'].includes(s.status)&&i.shippedQuantity<i.pickedQuantity&&<button disabled={busy} onClick={()=>mutate("PATCH",{action:"ship",shipmentId:s.id,itemId:i.id,quantity:i.pickedQuantity-i.shippedQuantity})}>发货</button>}</div></div>)}</article>)}</section></main>}
