"use client";
import {useCallback,useEffect,useState} from "react";
import styles from "./variance.module.css";

type Case={id:number;status:string;reason:string|null;bookNetGrams:number;measuredNetGrams:number;varianceGrams:number;resolutionNote:string;createdBy:string;resolvedBy:string|null;resolvedAt:string|null;createdAt:string;spoolId:number;spoolCode:string;currentNetGrams:number;state:string;material:string;colorName:string;colorHex:string;locationName:string};
type Data={canWrite:boolean;cases:Case[]};
const reasonNames:Record<string,string>={print_consumption:"遗漏的打印消耗",loss:"破损或遗失",moisture:"受潮/烘干重量变化",scale_error:"称重误差",stocktake_adjustment:"盘点调整",other:"其他"};
const statusNames:Record<string,string>={open:"待处理",resolved:"已调整",rejected:"已驳回"};

export default function VarianceClient(){
 const[data,setData]=useState<Data>({canWrite:false,cases:[]}),[drafts,setDrafts]=useState<Record<number,{reason:string;note:string}>>({}),[message,setMessage]=useState(""),[saving,setSaving]=useState(0);
 const load=useCallback(async()=>{const response=await fetch("/api/material-variances",{cache:"no-store"}),body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error||"读取差异单失败");setData(body)},[]);useEffect(()=>{void load().catch(error=>setMessage(error.message))},[load]);
 function patch(id:number,value:Partial<{reason:string;note:string}>){setDrafts(current=>({...current,[id]:{reason:"",note:"",...current[id],...value}}))}
 async function resolve(item:Case,decision:"accept"|"reject"){const draft=drafts[item.id]||{reason:"",note:""};setSaving(item.id);const response=await fetch("/api/material-variances",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({caseId:item.id,decision,...draft})}),body=await response.json() as{error?:string};setMessage(response.ok?decision==="accept"?"差异已形成不可变库存调整流水。":"本次称重已驳回，库存未调整。":body.error||"处理失败");setSaving(0);if(response.ok)await load()}
 const open=data.cases.filter(item=>item.status==="open"),history=data.cases.filter(item=>item.status!=="open");
 return <main className={styles.page}><header><div><a href="/inventory">← 返回耗材库存</a><small>INVENTORY VARIANCE CONTROL</small><h1>耗材差异处理中心</h1><p>超过 ±2g 容差的称重不会直接修改库存，必须判定原因并留下处理记录。</p></div><strong>{open.length}<small>待处理差异</small></strong></header>{message?<div className={styles.message}>{message}<button onClick={()=>setMessage("")}>×</button></div>:null}
  <section className={styles.rules}><span>账面余量变化后，旧差异单禁止调整</span><span>称重误差只能驳回，不生成库存流水</span><span>接受差异会生成不可变调整或损耗流水</span></section>
  <section className={styles.panel}><h2>待处理</h2><div className={styles.list}>{open.map(item=>{const draft=drafts[item.id]||{reason:"",note:""},stale=Math.abs(Number(item.currentNetGrams)-Number(item.bookNetGrams))>.001;return <article key={item.id}><header><span style={{background:`#${String(item.colorHex||"").replace("#","")}`}}/><div><b>{item.spoolCode} · {item.material} {item.colorName}</b><small>{item.locationName} · {new Date(item.createdAt).toLocaleString("zh-CN")}</small></div><strong className={item.varianceGrams<0?styles.negative:styles.positive}>{item.varianceGrams>0?"+":""}{Number(item.varianceGrams).toFixed(1)}g</strong></header><div className={styles.weights}><span>称重时账面<b>{Number(item.bookNetGrams).toFixed(1)}g</b></span><span>实体称重<b>{Number(item.measuredNetGrams).toFixed(1)}g</b></span><span>当前账面<b>{Number(item.currentNetGrams).toFixed(1)}g</b></span></div>{stale?<p className={styles.stale}>库存已发生变化，必须重新称重，不能使用旧差异调整。</p>:null}{data.canWrite?<div className={styles.form}><select value={draft.reason} onChange={event=>patch(item.id,{reason:event.target.value})}><option value="">选择差异原因</option>{Object.entries(reasonNames).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input value={draft.note} onChange={event=>patch(item.id,{note:event.target.value})} placeholder="填写核查过程和处理依据"/><button disabled={stale||saving===item.id||!draft.reason||!draft.note} onClick={()=>void resolve(item,"accept")}>接受并调整</button><button className={styles.ghost} disabled={saving===item.id||draft.reason!=="scale_error"||!draft.note} onClick={()=>void resolve(item,"reject")}>驳回称重</button></div>:null}</article>})}{!open.length?<p className={styles.empty}>当前没有待处理的耗材差异。</p>:null}</div></section>
  <section className={styles.panel}><h2>处理记录</h2><div className={styles.history}>{history.map(item=><div key={item.id}><span><b>{item.spoolCode}</b><small>{item.material} {item.colorName}</small></span><span><b>{item.varianceGrams>0?"+":""}{Number(item.varianceGrams).toFixed(1)}g</b><small>{reasonNames[item.reason||""]||item.reason}</small></span><em data-status={item.status}>{statusNames[item.status]}</em><span><small>{item.resolutionNote}</small><small>{item.resolvedBy} · {item.resolvedAt?new Date(item.resolvedAt).toLocaleString("zh-CN"):"—"}</small></span></div>)}{!history.length?<p className={styles.empty}>暂无历史处理记录。</p>:null}</div></section>
 </main>
}
