import {getAccessContext,recordAudit} from "../../access-control";
import {requireApiAccess} from "../../api-auth";
import {getD1} from "../../../db";

const fail=(error:string,status:number)=>Response.json({error},{status});
const reasons=new Set(["print_consumption","loss","moisture","scale_error","stocktake_adjustment","other"]);

export async function GET(){
 const denied=await requireApiAccess();if(denied)return denied;const context=await getAccessContext();if(!context)return fail("请先登录",401);const org=context.organizationId;
 const result=await getD1().prepare(`SELECT v.id,v.status,v.reason,v.book_net_grams bookNetGrams,v.measured_net_grams measuredNetGrams,v.variance_grams varianceGrams,v.resolution_note resolutionNote,v.created_by createdBy,v.resolved_by resolvedBy,v.resolved_at resolvedAt,v.created_at createdAt,s.id spoolId,s.spool_code spoolCode,s.remaining_net_grams currentNetGrams,s.state,c.material,c.color_name colorName,c.color_hex colorHex,l.name locationName FROM material_variance_cases v JOIN material_spools s ON s.id=v.spool_id AND s.organization_id=v.organization_id JOIN material_catalog_items c ON c.id=s.catalog_item_id AND c.organization_id=v.organization_id JOIN inventory_locations_v2 l ON l.id=s.current_location_id AND l.organization_id=v.organization_id WHERE v.organization_id=? ORDER BY CASE v.status WHEN 'open' THEN 0 ELSE 1 END,v.id DESC LIMIT 200`).bind(org).all();
 return Response.json({canWrite:["owner","manager","warehouse"].includes(context.role),cases:result.results});
}

export async function POST(request:Request){
 const denied=await requireApiAccess(true,"inventory.write");if(denied)return denied;const context=await getAccessContext();if(!context)return fail("请先登录",401);
 try{const body=await request.json() as{caseId?:number;decision?:"accept"|"reject";reason?:string;note?:string},caseId=Number(body.caseId),reason=String(body.reason||""),note=String(body.note||"").trim().slice(0,500),db=getD1(),org=context.organizationId,now=new Date().toISOString();if(!reasons.has(reason)||!note)return fail("请选择差异原因并填写处理说明",400);
  const row=await db.prepare(`SELECT v.id,v.status,v.spool_id spoolId,v.book_net_grams bookNetGrams,v.measured_net_grams measuredNetGrams,v.variance_grams varianceGrams,s.remaining_net_grams currentNetGrams,s.current_location_id locationId FROM material_variance_cases v JOIN material_spools s ON s.id=v.spool_id AND s.organization_id=v.organization_id WHERE v.id=? AND v.organization_id=?`).bind(caseId,org).first<{id:number;status:string;spoolId:number;bookNetGrams:number;measuredNetGrams:number;varianceGrams:number;currentNetGrams:number;locationId:number}>();if(!row)return fail("差异单不存在",404);if(row.status!=="open")return fail("差异单已经处理",409);
  if(body.decision==="reject"){if(reason!=="scale_error")return fail("驳回称重只能选择称重误差",400);await db.prepare("UPDATE material_variance_cases SET status='rejected',reason=?,resolution_note=?,resolved_by=?,resolved_at=?,updated_at=? WHERE id=? AND organization_id=? AND status='open'").bind(reason,note,context.email,now,now,row.id,org).run();await recordAudit(context,"inventory_v2.variance.rejected","material_variance_case",String(row.id),{spoolId:row.spoolId,reason});return Response.json({id:row.id,status:"rejected"});}
  if(body.decision!=="accept")return fail("请选择接受调整或驳回称重",400);if(Math.abs(Number(row.currentNetGrams)-Number(row.bookNetGrams))>0.001)return fail("该耗材卷账面余量已变化，请重新称重后再处理",409);if(row.varianceGrams>0&&["loss","moisture","print_consumption"].includes(reason))return fail("实测余量高于账面时不能选择消耗或损耗原因",400);
  const movementType=row.varianceGrams<0&&["loss","moisture"].includes(reason)?"loss":"adjust",key=`variance:${row.id}`,movement=await db.prepare(`INSERT INTO material_spool_movements(organization_id,spool_id,movement_type,from_location_id,to_location_id,net_grams_delta,idempotency_key,operator_email,note) VALUES(?,?,?,?,?,?,?,?,?) RETURNING id`).bind(org,row.spoolId,movementType,row.locationId,row.locationId,row.varianceGrams,key,context.email,`差异处理：${reason} · ${note}`).first<{id:number}>();
  await db.batch([db.prepare("UPDATE material_spools SET remaining_net_grams=?,state=CASE WHEN ?<=0 THEN 'empty' ELSE state END,updated_at=? WHERE id=? AND organization_id=? AND remaining_net_grams=?").bind(row.measuredNetGrams,row.measuredNetGrams,now,row.spoolId,org,row.bookNetGrams),db.prepare("UPDATE material_variance_cases SET status='resolved',reason=?,resolution_note=?,adjustment_movement_id=?,resolved_by=?,resolved_at=?,updated_at=? WHERE id=? AND organization_id=? AND status='open'").bind(reason,note,movement!.id,context.email,now,now,row.id,org)]);
  await recordAudit(context,"inventory_v2.variance.resolved","material_variance_case",String(row.id),{spoolId:row.spoolId,reason,varianceGrams:row.varianceGrams,movementId:movement!.id});return Response.json({id:row.id,status:"resolved"});
 }catch(error){const message=error instanceof Error?error.message:"处理差异失败";return fail(message.includes("UNIQUE constraint")?"差异单已经生成调整流水":message,message.includes("UNIQUE constraint")?409:400)}
}
