import {getD1} from "../db";
import {buildReplenishmentForecast,type ForecastInput} from "./forecast";
type Row=Record<string,unknown>;const number=(value:unknown)=>Number(value)||0;

export async function getReplenishmentForecast(organizationId:number){
 const db=getD1(),today=new Date().toISOString().slice(0,10);
 const [materialsResult,usageResult,commitmentResult,offersResult]=await Promise.all([
  db.prepare(`SELECT c.id catalogItemId,c.catalog_code catalogCode,c.material,c.color_name colorName,c.color_hex colorHex,c.default_net_grams defaultNetGrams,c.target_stock_spools targetStockSpools,COALESCE(SUM(CASE WHEN s.remaining_net_grams>0 THEN s.remaining_net_grams ELSE 0 END),0) onHandGrams,COALESCE((SELECT SUM(poi.ordered_spools-poi.received_spools) FROM purchase_order_items poi JOIN purchase_orders po ON po.id=poi.purchase_order_id AND po.organization_id=poi.organization_id WHERE poi.organization_id=c.organization_id AND poi.catalog_item_id=c.id AND po.status IN ('ordered','partially_received')),0) incomingSpools FROM material_catalog_items c LEFT JOIN material_spools s ON s.catalog_item_id=c.id AND s.organization_id=c.organization_id WHERE c.organization_id=? GROUP BY c.id ORDER BY c.catalog_code`).bind(organizationId).all<Row>(),
  db.prepare(`SELECT s.catalog_item_id catalogItemId,COALESCE(SUM(COALESCE(u.measured_grams,u.settled_grams,u.estimated_grams)),0) consumed30dGrams,COUNT(DISTINCT date(u.settled_at)) sampleDays FROM print_material_usage_lines u JOIN material_spools s ON s.id=u.spool_id AND s.organization_id=u.organization_id WHERE u.organization_id=? AND u.settled_at IS NOT NULL AND datetime(u.settled_at)>=datetime('now','-30 days') GROUP BY s.catalog_item_id`).bind(organizationId).all<Row>(),
  db.prepare(`SELECT s.catalog_item_id catalogItemId,COALESCE(SUM(u.estimated_grams),0) committedGrams FROM print_material_usage_lines u JOIN material_spools s ON s.id=u.spool_id AND s.organization_id=u.organization_id WHERE u.organization_id=? AND u.settled_at IS NULL GROUP BY s.catalog_item_id`).bind(organizationId).all<Row>(),
  db.prepare(`SELECT o.catalog_item_id catalogItemId,s.name supplierName,o.lead_time_days leadTimeDays,o.min_order_spools minOrderSpools,o.unit_price_cents_per_spool unitPriceCentsPerSpool,o.tax_rate_bps taxRateBps,o.freight_cents_per_order freightCents FROM supplier_material_offers o JOIN suppliers s ON s.id=o.supplier_id AND s.organization_id=o.organization_id WHERE o.organization_id=? AND o.status='active' AND o.valid_from<=? AND (o.valid_until IS NULL OR o.valid_until>=?) ORDER BY o.catalog_item_id,(o.unit_price_cents_per_spool+o.freight_cents_per_order)`).bind(organizationId,today,today).all<Row>(),
 ]);
 const usage=new Map((usageResult.results??[]).map(row=>[number(row.catalogItemId),row])),commitments=new Map((commitmentResult.results??[]).map(row=>[number(row.catalogItemId),row])),offers=new Map<number,Row>();for(const row of offersResult.results??[]){const id=number(row.catalogItemId);if(!offers.has(id))offers.set(id,row)}
 const forecasts=(materialsResult.results??[]).map(row=>{const id=number(row.catalogItemId),used=usage.get(id),committed=commitments.get(id),offer=offers.get(id),input:ForecastInput={catalogItemId:id,catalogCode:String(row.catalogCode),material:String(row.material),colorName:String(row.colorName),colorHex:String(row.colorHex||""),defaultNetGrams:number(row.defaultNetGrams),targetStockSpools:number(row.targetStockSpools),onHandGrams:number(row.onHandGrams),incomingSpools:number(row.incomingSpools),committedGrams:number(committed?.committedGrams),consumed30dGrams:number(used?.consumed30dGrams),sampleDays:number(used?.sampleDays),supplierName:String(offer?.supplierName||""),leadTimeDays:number(offer?.leadTimeDays),minOrderSpools:number(offer?.minOrderSpools),unitPriceCentsPerSpool:number(offer?.unitPriceCentsPerSpool),taxRateBps:number(offer?.taxRateBps),freightCents:number(offer?.freightCents)};return buildReplenishmentForecast(input)}).filter(row=>row.suggestedSpools>0||row.risk==="urgent"||row.risk==="soon").sort((a,b)=>{const priority={urgent:0,soon:1,stable:2,insufficient_history:3};return priority[a.risk]-priority[b.risk]||(a.orderByDays??99999)-(b.orderByDays??99999)});
 return {forecasts,summary:{urgent:forecasts.filter(row=>row.risk==="urgent").length,soon:forecasts.filter(row=>row.risk==="soon").length,plannedSpendCents:forecasts.reduce((sum,row)=>sum+row.forecastCostCents,0),suggestedSpools:forecasts.reduce((sum,row)=>sum+row.suggestedSpools,0),missingOffers:forecasts.filter(row=>row.suggestedSpools>0&&!row.supplierName).length},cashflow:Array.from({length:8},(_,offset)=>{const start=new Date();start.setDate(1);start.setMonth(start.getMonth()+offset);const month=start.toISOString().slice(0,7),cents=forecasts.filter(row=>row.cashflowDate?.startsWith(month)).reduce((sum,row)=>sum+row.forecastCostCents,0);return {month,cents}})};
}
