import {getAccessContext,recordAudit} from "../../access-control";
import {requireApiAccess} from "../../api-auth";
import {getD1} from "../../../db";
import {materialCostCents,settledGramsForRow,validateSlicePayload} from "../../../cost-settlement/domain";

const fail=(error:string,status=400)=>Response.json({error},{status});
const id=(value:unknown)=>{const n=Number(value);return Number.isInteger(n)&&n>0?n:0};
const json=(value:unknown)=>{try{return JSON.parse(String(value||"{}")) as Record<string,unknown>}catch{return{}}};
type CostBreakdown={purpose:unknown;toolhead:unknown;lineCount:number;estimatedGrams:number;settledGrams:number;measuredGrams:number;costCents:number;pendingLines:number};
type CostSessionSummary={sessionId:number;filename:unknown;status:unknown;startedAt:unknown;completedAt:unknown;jobId:unknown;jobNo:unknown;quantity:number;orderId:unknown;orderNo:unknown;customer:unknown;itemId:unknown;sku:unknown;itemName:unknown;estimatedGrams:number;settledGrams:number;measuredGrams:number;materialCostCents:number;pendingLines:number;breakdown:CostBreakdown[]};
type SettlementLine={id:number;spoolId:number|null;purpose:string;estimatedGrams:number;measuredGrams:number|null;settledAt:string|null;remainingGrams:number|null;locationId:number|null;centsPerKg:number};
type PendingSettlement=SettlementLine&{actual:number;cost:number};

export async function GET(request:Request){
 const denied=await requireApiAccess();if(denied)return denied;const context=await getAccessContext();if(!context)return fail("请先登录",401);
 const db=getD1(),org=context.organizationId,url=new URL(request.url),sessionId=id(url.searchParams.get("sessionId"));
 const where=sessionId?" AND ps.id=?":"",bind=<T extends {bind:(...values:unknown[])=>T}>(statement:T)=>sessionId?statement.bind(org,sessionId):statement.bind(org);
 const rows=await bind(db.prepare(`SELECT ps.id sessionId,ps.filename,ps.status,ps.started_at startedAt,ps.completed_at completedAt,ps.job_id jobId,j.job_no jobNo,j.quantity,o.id orderId,o.order_no orderNo,o.customer,i.id itemId,i.sku,i.name itemName,
   u.purpose,u.toolhead,COUNT(u.id) lineCount,SUM(u.estimated_grams) estimatedGrams,SUM(COALESCE(u.settled_grams,0)) settledGrams,SUM(COALESCE(u.measured_grams,0)) measuredGrams,SUM(u.cost_cents) costCents,
   SUM(CASE WHEN u.spool_id IS NULL OR u.purpose='unknown' OR u.settled_at IS NULL THEN 1 ELSE 0 END) pendingLines
   FROM print_sessions ps JOIN print_material_usage_lines u ON u.print_session_id=ps.id AND u.organization_id=ps.organization_id
   LEFT JOIN print_jobs j ON j.id=ps.job_id AND j.organization_id=ps.organization_id LEFT JOIN orders o ON o.id=j.order_id AND o.organization_id=ps.organization_id LEFT JOIN print_items i ON i.id=j.item_id
   WHERE ps.organization_id=?${where} GROUP BY ps.id,u.purpose,u.toolhead ORDER BY ps.last_observed_at DESC,u.purpose,u.toolhead`)).all();
 const sessions=new Map<number,CostSessionSummary>();for(const row of rows.results as Record<string,unknown>[]){const sessionId=Number(row.sessionId),current=sessions.get(sessionId)??{sessionId,filename:row.filename,status:row.status,startedAt:row.startedAt,completedAt:row.completedAt,jobId:row.jobId,jobNo:row.jobNo,quantity:Number(row.quantity||0),orderId:row.orderId,orderNo:row.orderNo,customer:row.customer,itemId:row.itemId,sku:row.sku,itemName:row.itemName,estimatedGrams:0,settledGrams:0,measuredGrams:0,materialCostCents:0,pendingLines:0,breakdown:[]};current.estimatedGrams+=Number(row.estimatedGrams||0);current.settledGrams+=Number(row.settledGrams||0);current.measuredGrams+=Number(row.measuredGrams||0);current.materialCostCents+=Number(row.costCents||0);current.pendingLines+=Number(row.pendingLines||0);current.breakdown.push({purpose:row.purpose,toolhead:row.toolhead,lineCount:Number(row.lineCount),estimatedGrams:Number(row.estimatedGrams),settledGrams:Number(row.settledGrams),measuredGrams:Number(row.measuredGrams),costCents:Number(row.costCents),pendingLines:Number(row.pendingLines)});sessions.set(sessionId,current)}
 return Response.json({sessions:[...sessions.values()].map(item=>({...item,unitMaterialCostCents:item.quantity>0?Math.round(item.materialCostCents/item.quantity):null}))});
}

export async function POST(request:Request){
 const denied=await requireApiAccess(true,"inventory.write");if(denied)return denied;const context=await getAccessContext();if(!context)return fail("请先登录",401);
 const body=await request.json() as Record<string,unknown>,action=String(body.action||""),db=getD1(),org=context.organizationId,now=new Date().toISOString();
 try{
  if(action==="import"){
   const payload=validateSlicePayload(body.payload),printerId=id(body.printerId);if(!printerId)return fail("请选择这份切片适用的打印机");
   const owned=await db.prepare("SELECT 1 FROM printer_bindings WHERE organization_id=? AND printer_id=? LIMIT 1").bind(org,printerId).first();if(!owned)return fail("打印机不属于当前组织",404);
   const key=`slice:${payload.file.fingerprint}`,existing=await db.prepare("SELECT id FROM print_sessions WHERE organization_id=? AND external_session_key=?").bind(org,key).first<{id:number}>();if(existing){const count=await db.prepare("SELECT COUNT(*) count FROM print_material_usage_lines WHERE organization_id=? AND print_session_id=?").bind(org,existing.id).first<{count:number}>();if(Number(count?.count)===payload.usage.length)return Response.json({sessionId:existing.id,fingerprint:payload.file.fingerprint,idempotent:true});if(Number(count?.count)!==0)return fail("该指纹的用量明细不完整，需要人工检查",409);const repair=payload.usage.map(row=>db.prepare("INSERT INTO print_material_usage_lines(organization_id,print_session_id,toolhead,purpose,estimate_source,estimated_grams) VALUES(?,?,?,?,?,?)").bind(org,existing.id,row.toolhead,row.feature,payload.file.format,row.estimatedGrams));if(repair.length)await db.batch(repair);return Response.json({sessionId:existing.id,fingerprint:payload.file.fingerprint,idempotent:true,repaired:true})}
   const snapshot=JSON.stringify({sliceMetadata:payload,importState:"canonical"}),session=await db.prepare("INSERT INTO print_sessions(organization_id,printer_id,source,external_session_key,filename,status,last_observed_at,telemetry_snapshot) VALUES(?,?,'manual',?,?,'unmatched',?,?) RETURNING id").bind(org,printerId,key,payload.source.fileName,payload.source.observedAt,snapshot).first<{id:number}>();
   const statements=payload.usage.map(row=>db.prepare("INSERT INTO print_material_usage_lines(organization_id,print_session_id,toolhead,purpose,estimate_source,estimated_grams) VALUES(?,?,?,?,?,?)").bind(org,session!.id,row.toolhead,row.feature,payload.file.format,row.estimatedGrams));if(statements.length)await db.batch(statements);
   await recordAudit(context,"cost_settlement.slice.imported","print_session",String(session!.id),{fingerprint:payload.file.fingerprint,usageLines:payload.usage.length});return Response.json({sessionId:session!.id,fingerprint:payload.file.fingerprint,idempotent:false},{status:201});
  }
  if(action==="reserve"){
   const sessionId=id(body.sessionId),fingerprint=String(body.fingerprint||"").toLowerCase(),target=await db.prepare("SELECT id,printer_id printerId,telemetry_snapshot snapshot FROM print_sessions WHERE id=? AND organization_id=?").bind(sessionId,org).first<{id:number;printerId:number;snapshot:string}>();if(!target)return fail("打印会话不存在",404);
   const canonical=await db.prepare("SELECT telemetry_snapshot snapshot FROM print_sessions WHERE organization_id=? AND external_session_key=?").bind(org,`slice:${fingerprint}`).first<{snapshot:string}>();if(!canonical)return fail("切片指纹尚未导入",404);const payload=validateSlicePayload(json(canonical.snapshot).sliceMetadata);
   const current=json(target.snapshot),existing=await db.prepare("SELECT COUNT(*) count FROM print_material_usage_lines WHERE organization_id=? AND print_session_id=?").bind(org,sessionId).first<{count:number}>();if(current.reservedFingerprint===fingerprint&&Number(existing?.count)===payload.usage.length)return Response.json({sessionId,idempotent:true});if(Number(existing?.count))return fail("该打印会话已有其他或不完整的材料预留",409);
   const mappings=new Map<number,number>((Array.isArray(body.feedPositionByFilament)?body.feedPositionByFilament:[]).map((x:Record<string,unknown>)=>[Number(x.filament),Number(x.feedPositionId)]));const resolved=new Map<number,{positionId:number;spoolId:number}>();
   for(const [filament,positionId] of mappings){const binding=await db.prepare(`SELECT f.id positionId,b.spool_id spoolId FROM printer_feed_positions f JOIN spool_bindings b ON b.feed_position_id=f.id AND b.organization_id=f.organization_id AND b.status='active' JOIN material_spools s ON s.id=b.spool_id AND s.organization_id=b.organization_id WHERE f.id=? AND f.organization_id=? AND f.printer_id=?`).bind(positionId,org,target.printerId).first<{positionId:number;spoolId:number}>();if(!binding)return fail(`耗材 ${filament} 的供料位置没有明确绑定实体卷`,409);resolved.set(filament,binding)}
   const statements=payload.usage.map(row=>{const match=resolved.get(row.filament);return db.prepare("INSERT INTO print_material_usage_lines(organization_id,print_session_id,spool_id,feed_position_id,toolhead,purpose,estimate_source,estimated_grams) VALUES(?,?,?,?,?,?,?,?)").bind(org,sessionId,match?.spoolId??null,match?.positionId??null,row.toolhead,row.feature,payload.file.format,row.estimatedGrams)});if(statements.length)await db.batch(statements);
   current.sliceMetadata=payload;current.reservedFingerprint=fingerprint;current.reservationState="reserved";current.reservedAt=now;await db.prepare("UPDATE print_sessions SET telemetry_snapshot=?,started_at=COALESCE(started_at,?),updated_at=? WHERE id=? AND organization_id=?").bind(JSON.stringify(current),now,now,sessionId,org).run();
   await recordAudit(context,"cost_settlement.material.reserved","print_session",String(sessionId),{fingerprint,mappedFilaments:[...resolved.keys()]});return Response.json({sessionId,idempotent:false,pendingBindings:payload.usage.filter(row=>!resolved.has(row.filament)).length});
  }
  if(action==="measure"){
   const sessionId=id(body.sessionId),lineId=id(body.usageLineId),measured=Number(body.measuredGrams);if(!sessionId||!lineId||!Number.isFinite(measured)||measured<0)return fail("称重校准参数无效");
   const result=await db.prepare("UPDATE print_material_usage_lines SET measured_grams=?,estimate_source='scale',updated_at=? WHERE id=? AND print_session_id=? AND organization_id=? AND settled_at IS NULL RETURNING id").bind(measured,now,lineId,sessionId,org).first();if(!result)return fail("用量行不存在或已经结算",409);
   await recordAudit(context,"cost_settlement.usage.measured","print_material_usage",String(lineId),{sessionId,measured});return Response.json({lineId,measured});
  }
  if(action==="settle"){
   const sessionId=id(body.sessionId),outcome=String(body.outcome||""),terminal=["completed","failed","cancelled"];if(!sessionId||!terminal.includes(outcome))return fail("结算状态无效");
   const session=await db.prepare("SELECT id,job_id jobId,telemetry_snapshot snapshot FROM print_sessions WHERE id=? AND organization_id=?").bind(sessionId,org).first<{id:number;jobId:number|null;snapshot:string}>();if(!session)return fail("打印会话不存在",404);const snapshot=json(session.snapshot);let sliceMetadata=snapshot.sliceMetadata;if(!sliceMetadata){const reservation=await db.prepare("SELECT detail FROM audit_logs WHERE organization_id=? AND action='cost_settlement.material.reserved' AND resource='print_session' AND resource_id=? ORDER BY id DESC LIMIT 1").bind(org,String(sessionId)).first<{detail:string}>(),fingerprint=String(json(reservation?.detail).fingerprint||"");if(fingerprint){const canonical=await db.prepare("SELECT telemetry_snapshot snapshot FROM print_sessions WHERE organization_id=? AND external_session_key=?").bind(org,`slice:${fingerprint}`).first<{snapshot:string}>();sliceMetadata=json(canonical?.snapshot).sliceMetadata;snapshot.sliceMetadata=sliceMetadata;snapshot.reservedFingerprint=fingerprint}}const payload=validateSlicePayload(sliceMetadata),lastLayerByPlate=(body.lastLayerByPlate??{}) as Record<string,number>;
   const lines=(await db.prepare(`SELECT u.id,u.spool_id spoolId,u.purpose,u.estimated_grams estimatedGrams,u.measured_grams measuredGrams,u.settled_at settledAt,s.remaining_net_grams remainingGrams,s.current_location_id locationId,COALESCE(l.unit_cost_cents_per_kg,0) centsPerKg FROM print_material_usage_lines u LEFT JOIN material_spools s ON s.id=u.spool_id AND s.organization_id=u.organization_id LEFT JOIN material_purchase_lots l ON l.id=s.purchase_lot_id AND l.organization_id=s.organization_id WHERE u.organization_id=? AND u.print_session_id=? ORDER BY u.id`).bind(org,sessionId).all()).results as unknown as SettlementLine[];
   if(lines.length!==payload.usage.length)return fail("预留用量与切片元数据不一致",409);const deductions=new Map<number,number>(),settlements:PendingSettlement[]=[];
   lines.forEach((line,index)=>{const source=payload.usage[index],hasLayer=Number.isFinite(Number(lastLayerByPlate[String(source.plate)])),pending=!line.spoolId||source.feature==="unknown"||(outcome!=="completed"&&line.measuredGrams==null&&!hasLayer);const calculated=settledGramsForRow(source,payload.layers,lastLayerByPlate,outcome==="completed"),actual=line.measuredGrams==null?calculated:Number(line.measuredGrams);if(!pending&&!line.settledAt){deductions.set(Number(line.spoolId),(deductions.get(Number(line.spoolId))||0)+actual);settlements.push({...line,actual,cost:materialCostCents(actual,Number(line.centsPerKg||0))})}});
   for(const [spoolId,total] of deductions){const available=Number(lines.find(x=>Number(x.spoolId)===spoolId)?.remainingGrams||0);if(total>available+0.0001)return fail(`实体卷 #${spoolId} 余量不足，结算已暂停`,409)}
   const statements=[];for(const row of settlements){const key=`consume:${sessionId}:${row.id}`;statements.push(db.prepare("UPDATE print_material_usage_lines SET settled_grams=?,cost_cents=?,settled_at=?,updated_at=? WHERE id=? AND organization_id=? AND settled_at IS NULL").bind(row.actual,row.cost,now,now,row.id,org),db.prepare("UPDATE material_spools SET remaining_net_grams=remaining_net_grams-?,state=CASE WHEN remaining_net_grams-?<=0 THEN 'empty' ELSE state END,updated_at=? WHERE id=? AND organization_id=?").bind(row.actual,row.actual,now,row.spoolId,org),db.prepare("INSERT INTO material_spool_movements(organization_id,spool_id,movement_type,from_location_id,usage_line_id,net_grams_delta,idempotency_key,operator_email,note) VALUES(?,?,'consume',?,?,?, ?,?,?)").bind(org,row.spoolId,row.locationId,row.id,-row.actual,key,context.email,`${outcome} 会话 #${sessionId} · ${row.purpose}`))}if(statements.length)await db.batch(statements);
   const pending=lines.length-settlements.length-lines.filter(x=>x.settledAt).length,costRow=await db.prepare("SELECT COALESCE(SUM(cost_cents),0) total FROM print_material_usage_lines WHERE organization_id=? AND print_session_id=?").bind(org,sessionId).first<{total:number}>(),totalCost=Number(costRow?.total||0);snapshot.reservationState=pending>0?"partially_settled":"settled";snapshot.settlement={outcome,lastLayerByPlate,pendingLines:pending,settledAt:now};await db.prepare("UPDATE print_sessions SET status=?,completed_at=COALESCE(completed_at,?),telemetry_snapshot=?,updated_at=? WHERE id=? AND organization_id=?").bind(outcome,now,JSON.stringify(snapshot),now,sessionId,org).run();
   if(session.jobId&&pending===0){const job=await db.prepare("SELECT order_id orderId FROM print_jobs WHERE id=? AND organization_id=?").bind(session.jobId,org).first<{orderId:number|null}>();await db.prepare("INSERT INTO profit_cost_entries(organization_id,order_id,job_id,category,basis,amount_cents,occurred_at,note,created_by) SELECT ?,?,?,'material','classified_spool_settlement',?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM profit_cost_entries WHERE organization_id=? AND note=?)").bind(org,job?.orderId??null,session.jobId,totalCost,now,`print-session:${sessionId}`,context.email,org,`print-session:${sessionId}`).run()}
   await recordAudit(context,"cost_settlement.session.settled","print_session",String(sessionId),{outcome,settledLines:settlements.length,pendingLines:pending,totalCost});return Response.json({sessionId,outcome,settledLines:settlements.length,pendingLines:pending,materialCostCents:totalCost});
  }
  return fail("不支持的成本结算操作");
 }catch(error){const message=error instanceof Error?error.message:"结算失败";if(message.includes("UNIQUE")){if(action==="import"){const fingerprint=String(body.payload?.file?.fingerprint||"").toLowerCase(),row=await db.prepare("SELECT id FROM print_sessions WHERE organization_id=? AND external_session_key=?").bind(org,`slice:${fingerprint}`).first<{id:number}>();if(row)return Response.json({sessionId:row.id,fingerprint,idempotent:true})}return fail("相同结算请求已经处理",409)}return fail(message,400)}
}
