import {getD1} from "../db";

type Row=Record<string,unknown>;
const number=(value:unknown)=>Number(value)||0;
export type InventoryValueBucket={bucket:string;spools:number;grams:number;valueCents:number;unknownCostSpools:number};
export type InventoryValueMaterial={catalogCode:string;material:string;colorName:string;colorHex:string;spools:number;grams:number;valueCents:number;averageCostCentsPerKg:number};
export type InventoryValueLot={lotNo:string;supplierName:string;receivedAt:string;spools:number;remainingGrams:number;unitCostCentsPerKg:number;valueCents:number;reconciled:boolean};

export async function getInventoryValueReport(organizationId:number){
 const db=getD1();
 const [bucketResult,materialResult,lotResult,varianceResult,usageResult]=await Promise.all([
  db.prepare(`WITH valued AS (SELECT s.id,s.remaining_net_grams grams,COALESCE(l.unit_cost_cents_per_kg,0) unit_cost,CASE WHEN EXISTS(SELECT 1 FROM spool_bindings b WHERE b.organization_id=s.organization_id AND b.spool_id=s.id AND b.status='active') THEN 'in_use' WHEN s.state='sealed' THEN 'sealed' WHEN s.state IN ('open_storage','opened') THEN 'open_storage' ELSE 'other' END bucket FROM material_spools s LEFT JOIN material_purchase_lots l ON l.id=s.purchase_lot_id AND l.organization_id=s.organization_id WHERE s.organization_id=? AND s.remaining_net_grams>0) SELECT bucket,COUNT(*) spools,COALESCE(SUM(grams),0) grams,COALESCE(SUM(ROUND(grams*unit_cost/1000.0)),0) valueCents,SUM(CASE WHEN unit_cost=0 THEN 1 ELSE 0 END) unknownCostSpools FROM valued GROUP BY bucket ORDER BY bucket`).bind(organizationId).all<Row>(),
  db.prepare(`SELECT c.catalog_code catalogCode,c.material,c.color_name colorName,c.color_hex colorHex,COUNT(s.id) spools,COALESCE(SUM(s.remaining_net_grams),0) grams,COALESCE(SUM(ROUND(s.remaining_net_grams*COALESCE(l.unit_cost_cents_per_kg,0)/1000.0)),0) valueCents,CASE WHEN SUM(s.remaining_net_grams)>0 THEN ROUND(SUM(s.remaining_net_grams*COALESCE(l.unit_cost_cents_per_kg,0))/SUM(s.remaining_net_grams)) ELSE 0 END averageCostCentsPerKg FROM material_spools s JOIN material_catalog_items c ON c.id=s.catalog_item_id AND c.organization_id=s.organization_id LEFT JOIN material_purchase_lots l ON l.id=s.purchase_lot_id AND l.organization_id=s.organization_id WHERE s.organization_id=? AND s.remaining_net_grams>0 GROUP BY c.id ORDER BY valueCents DESC,c.catalog_code LIMIT 100`).bind(organizationId).all<Row>(),
  db.prepare(`SELECT l.lot_no lotNo,COALESCE(v.name,'未登记供应商') supplierName,COALESCE(l.received_at,'') receivedAt,COUNT(s.id) spools,COALESCE(SUM(s.remaining_net_grams),0) remainingGrams,l.unit_cost_cents_per_kg unitCostCentsPerKg,COALESCE(SUM(ROUND(s.remaining_net_grams*l.unit_cost_cents_per_kg/1000.0)),0) valueCents,CASE WHEN l.reconciled_invoice_id IS NULL THEN 0 ELSE 1 END reconciled FROM material_purchase_lots l LEFT JOIN suppliers v ON v.id=l.supplier_id AND v.organization_id=l.organization_id LEFT JOIN material_spools s ON s.purchase_lot_id=l.id AND s.organization_id=l.organization_id AND s.remaining_net_grams>0 WHERE l.organization_id=? GROUP BY l.id HAVING COUNT(s.id)>0 ORDER BY l.received_at DESC,l.id DESC LIMIT 100`).bind(organizationId).all<Row>(),
  db.prepare(`SELECT COALESCE(SUM(CASE WHEN status IN ('matched','approved') THEN approved_total_cents ELSE 0 END),0) approvedTotalCents,COALESCE(SUM(CASE WHEN status IN ('matched','approved') THEN actual_total_cents ELSE 0 END),0) actualTotalCents,COALESCE(SUM(CASE WHEN status IN ('matched','approved') THEN variance_cents ELSE 0 END),0) varianceCents,SUM(CASE WHEN status='pending_review' THEN 1 ELSE 0 END) pendingInvoices,COALESCE((SELECT SUM(CASE WHEN status='applied' THEN 1 ELSE 0 END) FROM material_cost_adjustments WHERE organization_id=?),0) adjustedLots,COALESCE((SELECT SUM(CASE WHEN status='skipped_settled' THEN 1 ELSE 0 END) FROM material_cost_adjustments WHERE organization_id=?),0) protectedLots FROM supplier_invoices WHERE organization_id=?`).bind(organizationId,organizationId,organizationId).first<Row>(),
  db.prepare(`SELECT purpose,COUNT(*) lines,COALESCE(SUM(COALESCE(measured_grams,settled_grams,estimated_grams)),0) grams,COALESCE(SUM(cost_cents),0) costCents FROM print_material_usage_lines WHERE organization_id=? AND settled_at IS NOT NULL GROUP BY purpose ORDER BY costCents DESC`).bind(organizationId).all<Row>(),
 ]);
 const buckets=(bucketResult.results??[]).map(row=>({bucket:String(row.bucket),spools:number(row.spools),grams:number(row.grams),valueCents:number(row.valueCents),unknownCostSpools:number(row.unknownCostSpools)} satisfies InventoryValueBucket));
 const materials=(materialResult.results??[]).map(row=>({catalogCode:String(row.catalogCode),material:String(row.material),colorName:String(row.colorName),colorHex:String(row.colorHex||""),spools:number(row.spools),grams:number(row.grams),valueCents:number(row.valueCents),averageCostCentsPerKg:number(row.averageCostCentsPerKg)} satisfies InventoryValueMaterial));
 const lots=(lotResult.results??[]).map(row=>({lotNo:String(row.lotNo),supplierName:String(row.supplierName),receivedAt:String(row.receivedAt),spools:number(row.spools),remainingGrams:number(row.remainingGrams),unitCostCentsPerKg:number(row.unitCostCentsPerKg),valueCents:number(row.valueCents),reconciled:Boolean(row.reconciled)} satisfies InventoryValueLot));
 const variance=varianceResult??{},usage=(usageResult.results??[]).map(row=>({purpose:String(row.purpose),lines:number(row.lines),grams:number(row.grams),costCents:number(row.costCents)}));
 return {buckets,materials,lots,usage,summary:{inventoryValueCents:buckets.reduce((sum,row)=>sum+row.valueCents,0),inventoryGrams:buckets.reduce((sum,row)=>sum+row.grams,0),spools:buckets.reduce((sum,row)=>sum+row.spools,0),unknownCostSpools:buckets.reduce((sum,row)=>sum+row.unknownCostSpools,0),approvedTotalCents:number(variance.approvedTotalCents),actualTotalCents:number(variance.actualTotalCents),varianceCents:number(variance.varianceCents),pendingInvoices:number(variance.pendingInvoices),adjustedLots:number(variance.adjustedLots),protectedLots:number(variance.protectedLots),settledMaterialCostCents:usage.reduce((sum,row)=>sum+row.costCents,0)}};
}
