"use client";
import{FormEvent,useCallback,useEffect,useMemo,useState}from"react";import styles from"./models.module.css";
type ModelFile={id:number;asset_id:number;name:string;category:string;description:string;asset_layer:"original"|"project"|"production";format:string;filename:string;size_bytes:number;version:string;source_platform:string;source_url:string;source_author:string;license_name:string;sha256:string;created_at:string;tags:string};
const layerNames={original:"原始模型",project:"切片工程",production:"生产文件"},categories=["未分类","手办","工具件","治具","备件","装饰品","客户定制","测试模型","生产零件"],size=(bytes:number)=>bytes>=1048576?`${(bytes/1048576).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`;
export default function ModelLibraryClient({canWrite}:{canWrite:boolean}){const[files,setFiles]=useState<ModelFile[]>([]),[query,setQuery]=useState(""),[layer,setLayer]=useState(""),[category,setCategory]=useState(""),[showUpload,setShowUpload]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
const load=useCallback(async()=>{setLoading(true);const params=new URLSearchParams();if(query)params.set("q",query);if(layer)params.set("layer",layer);if(category)params.set("category",category);try{const response=await fetch(`/api/models?${params}`,{cache:"no-store"}),body=await response.json() as{files?:ModelFile[];error?:string};if(!response.ok)throw new Error(body.error||"读取失败");setFiles(body.files||[])}catch(error){setMessage(error instanceof Error?error.message:"读取失败")}finally{setLoading(false)}},[query,layer,category]);
useEffect(()=>{const timer=setTimeout(()=>void load(),180);return()=>clearTimeout(timer)},[load]);const counts=useMemo(()=>files.reduce((result,file)=>({...result,[file.asset_layer]:(result[file.asset_layer]||0)+1}),{} as Record<string,number>),[files]);
async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setMessage("");const form=event.currentTarget;try{const response=await fetch("/api/models",{method:"POST",body:new FormData(form)}),body=await response.json() as{error?:string;message?:string;duplicate?:boolean};if(!response.ok)throw new Error(body.error||"上传失败");setMessage(body.duplicate?body.message||"文件已存在":"模型已安全存入资产库");if(!body.duplicate){form.reset();setShowUpload(false);await load()}}catch(error){setMessage(error instanceof Error?error.message:"上传失败")}finally{setSaving(false)}}
return <main className={styles.shell}><header className={styles.header}><a href="/" className={styles.back}>← 返回工作台</a><div><h1>模型资产库</h1><p>统一管理原始模型、Bambu 工程和可下发生产文件</p></div>{canWrite&&<button className={styles.primary} onClick={()=>setShowUpload(true)}>上传模型</button>}</header>
<section className={styles.summary}><div><strong>{files.length}</strong><span>当前结果</span></div><div><strong>{counts.original||0}</strong><span>原始模型</span></div><div><strong>{counts.project||0}</strong><span>切片工程</span></div><div><strong>{counts.production||0}</strong><span>生产文件</span></div></section>
<section className={styles.toolbar} aria-label="筛选模型"><input aria-label="搜索模型" value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索名称、文件或说明"/><select aria-label="资产层级" value={layer} onChange={event=>setLayer(event.target.value)}><option value="">全部层级</option><option value="original">原始模型</option><option value="project">切片工程</option><option value="production">生产文件</option></select><select aria-label="分类" value={category} onChange={event=>setCategory(event.target.value)}><option value="">全部分类</option>{categories.map(item=><option key={item}>{item}</option>)}</select></section>
{message&&<div className={styles.notice} role="status">{message}<button onClick={()=>setMessage("")} aria-label="关闭提示">×</button></div>}<section className={styles.library}>{loading?<div className={styles.empty}>正在读取模型资产…</div>:files.length===0?<div className={styles.empty}><strong>模型库还是空的</strong><span>上传 STL、3MF、STEP、OBJ 或 G-code，建立第一份可追溯资产。</span></div>:files.map(file=><article className={styles.row} key={file.id}><div className={`${styles.fileIcon} ${styles[file.asset_layer]}`}>{file.format.toUpperCase()}</div><div className={styles.main}><div><h2>{file.name}</h2><span className={styles.layer}>{layerNames[file.asset_layer]}</span></div><p>{file.filename} · {size(file.size_bytes)} · {file.version}</p><div className={styles.tags}><span>{file.category}</span>{file.tags.split(",").filter(Boolean).map(tag=><span key={tag}>#{tag}</span>)}</div></div><div className={styles.source}><span>{file.source_platform}</span><strong>{file.source_author||"内部资产"}</strong><small>{file.license_name||"未注明许可证"}</small></div><div className={styles.actions}>{file.source_url&&<a href={file.source_url} target="_blank" rel="noreferrer">查看来源</a>}<a href={`/api/models?download=${file.id}`}>下载文件</a></div></article>)}</section>
{showUpload&&<div className={styles.overlay} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setShowUpload(false)}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="upload-title"><header><div><h2 id="upload-title">上传模型资产</h2><p>文件保存在 R2，数据库仅记录可检索元数据。</p></div><button onClick={()=>setShowUpload(false)} aria-label="关闭">×</button></header><form onSubmit={upload}><label className={styles.fileInput}><span>模型文件</span><input name="file" type="file" accept=".stl,.3mf,.step,.stp,.obj,.gcode,.gco" required/><small>支持 STL、3MF、STEP、OBJ、G-code，最大 200MB</small></label><div className={styles.formGrid}><label><span>资产名称</span><input name="name" maxLength={160} placeholder="默认使用文件名"/></label><label><span>资产层级</span><select name="layer" defaultValue="original"><option value="original">原始模型</option><option value="project">切片工程</option><option value="production">生产文件</option></select></label><label><span>分类</span><select name="category" defaultValue="未分类">{categories.map(item=><option key={item}>{item}</option>)}</select></label><label><span>标签</span><input name="tags" maxLength={500} placeholder="手办, 客户定制, 多色"/></label><label><span>来源平台</span><input name="sourcePlatform" maxLength={60} placeholder="本地上传 / MakerWorld"/></label><label><span>来源作者</span><input name="sourceAuthor" maxLength={120}/></label><label><span>来源链接</span><input name="sourceUrl" type="url" maxLength={1000} placeholder="https://"/></label><label><span>许可证</span><input name="license" maxLength={120} placeholder="例如 CC BY-NC 4.0"/></label><label><span>版本</span><input name="version" maxLength={30} defaultValue="v1"/></label><label className={styles.wide}><span>说明</span><textarea name="description" maxLength={1200} rows={3}/></label></div><footer><button type="button" onClick={()=>setShowUpload(false)}>取消</button><button className={styles.primary} disabled={saving}>{saving?"正在校验并上传…":"保存到模型库"}</button></footer></form></section></div>}</main>}
