"use client";
import {useCallback,useEffect,useState} from "react";
import styles from "./feed-bindings.module.css";

type Spool={id:number;spoolCode:string;state:string;remainingNetGrams:number;rfidUid:string;catalogItemId:number;catalogCode:string;material:string;brand:string;colorName:string;colorCode:string;colorHex:string;locationName:string};
type Slot={id:number;printerId:number;printerName:string;amsUnit:number|null;slotIndex:number|null;feedKind:string;toolhead:string;telemetrySlotId:number|null;material:string;colorHex:string;remainingPercent:number|null;tagUid:string;active:boolean;lastSeenAt:string};
type Alias={catalogItemId:number;aliasType:string;aliasValue:string};type Data={canWrite:boolean;spools:Spool[];unboundSlots:Slot[];aliases:Alias[]};
type Candidate={spool:Spool;score:number;confidence:"高"|"中"|"低";reasons:string[]};
const hex=(value:string)=>value.replace("#","").slice(0,6).toUpperCase();
const normalizeCode=(value:string)=>value.trim().toUpperCase().replace(/^LT:SPOOL:/,"");
const position=(slot:Slot)=>slot.feedKind==="external"?(slot.toolhead==="auxiliary"?"辅助工具头外置料盘":"主工具头外置料盘"):`${slot.feedKind.toUpperCase()} ${Number(slot.amsUnit??0)+1}-${Number(slot.slotIndex??0)+1}`;
function candidates(slot:Slot,spools:Spool[],aliases:Alias[]):Candidate[]{return spools.map(spool=>{let score=0;const reasons:string[]=[],own=aliases.filter(alias=>alias.catalogItemId===spool.catalogItemId),materialValues=new Set([spool.material.toUpperCase(),...own.filter(x=>["material","rfid_material"].includes(x.aliasType)).map(x=>x.aliasValue.toUpperCase())]),hexValues=new Set([hex(spool.colorHex),...own.filter(x=>x.aliasType==="color_hex").map(x=>hex(x.aliasValue))]);if(slot.tagUid&&spool.rfidUid&&slot.tagUid===spool.rfidUid){score+=100;reasons.push("RFID完全一致")}if(slot.material&&materialValues.has(slot.material.toUpperCase())){score+=35;reasons.push(own.some(x=>x.aliasValue.toUpperCase()===slot.material.toUpperCase())?"材质别名一致":"材质一致")}if(hex(slot.colorHex)&&hexValues.has(hex(slot.colorHex))){score+=30;reasons.push("颜色值一致")}if(spool.remainingNetGrams>0){score+=5;reasons.push("库存可用")}return{spool,score,confidence:score>=100?"高":score>=65?"中":"低",reasons}}).filter(item=>item.score>=5).sort((a,b)=>b.score-a.score||a.spool.spoolCode.localeCompare(b.spool.spoolCode)).slice(0,6)}

export default function FeedBindingClient(){
 const[data,setData]=useState<Data>({canWrite:false,spools:[],unboundSlots:[],aliases:[]}),[selected,setSelected]=useState<Record<number,string>>({}),[scan,setScan]=useState<Record<number,string>>({}),[message,setMessage]=useState(""),[saving,setSaving]=useState(0),[focusId,setFocusId]=useState(0);
 const load=useCallback(async()=>{const[inventoryResponse,masterResponse]=await Promise.all([fetch("/api/inventory-v2",{cache:"no-store"}),fetch("/api/material-master",{cache:"no-store"})]),[inventory,master]=await Promise.all([inventoryResponse.json(),masterResponse.json()]);if(!inventoryResponse.ok)throw new Error(inventory.error||"读取供料位置失败");setData({...inventory,aliases:masterResponse.ok?master.aliases||[]:[]})},[]);useEffect(()=>{setFocusId(Number(new URLSearchParams(window.location.search).get("feedId"))||0);void load().catch(error=>setMessage(error.message))},[load]);
 const available=data.spools.filter(spool=>["sealed","open_storage"].includes(spool.state)&&Number(spool.remainingNetGrams)>0),quality=data.unboundSlots.map(slot=>({slot,candidates:candidates(slot,available,data.aliases)}));
 useEffect(()=>{if(focusId&&quality.length)requestAnimationFrame(()=>document.getElementById(`feed-${focusId}`)?.scrollIntoView({behavior:"smooth",block:"center"}))},[focusId,quality.length]);
 function scanCode(slot:Slot,value:string){setScan(current=>({...current,[slot.id]:value}));const code=normalizeCode(value),match=available.find(spool=>spool.spoolCode.toUpperCase()===code);setSelected(current=>({...current,[slot.id]:match?String(match.id):""}))}
 async function bind(slot:Slot){const spoolId=Number(selected[slot.id]);if(!spoolId)return setMessage("请先扫码或明确选择实体卷");setSaving(slot.id);const response=await fetch("/api/inventory-v2",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"issue",spoolId,feedPositionId:slot.id})}),body=await response.json() as{error?:string};setMessage(response.ok?"实体卷已绑定到供料位置；库存资产未减少，后续打印结算将扣减实际克重。":body.error||"绑定失败");setSaving(0);if(response.ok)await load()}
 return <main className={styles.page}><header><div><a href="/inventory">← 返回耗材库存</a><small>AMS · EXTERNAL · AUXILIARY FEED</small><h1>实体卷绑定向导</h1><p>Bambu 数据用于识别和推荐，库存实体卷必须由扫码或人工确认后才能绑定。</p></div><strong>{data.unboundSlots.length}<small>待绑定位置</small></strong></header>{message?<div className={styles.message}>{message}<button onClick={()=>setMessage("")}>×</button></div>:null}
  <section className={styles.kpis}><article><span>实时检测</span><b>{quality.filter(item=>item.slot.telemetrySlotId).length}</b></article><article><span>RFID 高置信候选</span><b>{quality.filter(item=>item.candidates[0]?.confidence==="高").length}</b></article><article><span>材质未知</span><b>{quality.filter(item=>!item.slot.material).length}</b></article><article><span>无可靠候选</span><b>{quality.filter(item=>!item.candidates.length||item.candidates[0].confidence==="低").length}</b></article></section>
  <section className={styles.rules}><span>不按槽位自动猜实体卷</span><span>RFID 一致仍需人员点击确认</span><span>绑定只改变仓位，不减少组织资产</span><span>实际克重在打印结算时扣减</span></section>
  <section className={styles.list}>{quality.map(({slot,candidates:matches})=>{const chosen=available.find(spool=>String(spool.id)===selected[slot.id]);return <article key={slot.id} id={`feed-${slot.id}`} className={focusId===slot.id?styles.focus:""}><header><i style={{background:hex(slot.colorHex)?`#${hex(slot.colorHex)}`:"#d8ddda"}}/><span><b>{slot.printerName} · {position(slot)}</b><small>{slot.material||"材质未知"} · {slot.remainingPercent==null?"余量未知":`设备估算 ${slot.remainingPercent}%`} · {slot.telemetrySlotId?"实时数据":"尚无实时数据"}</small></span><em>{slot.tagUid?"检测到 RFID":"无 RFID"}</em></header><div className={styles.detect}><span>设备颜色<b>{hex(slot.colorHex)?`#${hex(slot.colorHex)}`:"未知"}</b></span><span>标签 UID<b>{slot.tagUid||"未上报"}</b></span><span>最近上报<b>{slot.lastSeenAt?new Date(slot.lastSeenAt).toLocaleString("zh-CN"):"—"}</b></span></div><div className={styles.candidates}><h3>候选实体卷</h3>{matches.map(match=><button key={match.spool.id} className={selected[slot.id]===String(match.spool.id)?styles.selected:""} onClick={()=>setSelected(current=>({...current,[slot.id]:String(match.spool.id)}))}><i style={{background:`#${hex(match.spool.colorHex)}`}}/><span><b>{match.spool.spoolCode} · {match.spool.material} {match.spool.colorName}</b><small>{match.spool.brand} · {match.spool.remainingNetGrams.toFixed(0)}g · {match.spool.locationName}</small><small>{match.reasons.join(" · ")}</small></span><em data-confidence={match.confidence}>{match.confidence} · {match.score}</em></button>)}{!matches.length?<p>没有可用实体卷，请先采购入库或完成实物盘点。</p>:null}</div>{data.canWrite?<footer><label>扫码确认<input value={scan[slot.id]||""} onChange={event=>scanCode(slot,event.target.value)} placeholder="扫描 LT:SPOOL:FIL-..."/></label><select value={selected[slot.id]||""} onChange={event=>setSelected(current=>({...current,[slot.id]:event.target.value}))}><option value="">人工选择实体卷</option>{available.map(spool=><option key={spool.id} value={spool.id}>{spool.spoolCode} · {spool.material} {spool.colorName} · {spool.remainingNetGrams.toFixed(0)}g</option>)}</select><button disabled={!chosen||saving===slot.id} onClick={()=>void bind(slot)}>{saving===slot.id?"正在绑定…":"确认绑定实体卷"}</button></footer>:null}</article>})}{!quality.length?<p className={styles.empty}>当前所有已检测供料位置都已绑定实体卷。</p>:null}</section>
 </main>
}
