"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./receivables.module.css";
type Invoice={id:number;invoiceNo:string;orderNo:string;customerName:string;amountCents:number;paidCents:number;balanceCents:number;status:string;dueDate:string;agingBucket:string};
type Data={invoices:Invoice[];orders:Array<{id:number;orderNo:string;customer:string;amountCents:number}>;aging:Record<string,number>;signals:Array<{invoiceId:number}>;canManage:boolean};
const money=(n:number)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:"MYR"}).format(n/100);
const labels:Record<string,string>={draft:"草稿",issued:"已开具",partially_paid:"部分回款",paid:"已付清",void:"已作废",overdue:"已逾期"};
export default function ReceivablesClient(){const [data,setData]=useState<Data>({invoices:[],orders:[],aging:{},signals:[],canManage:false}),[message,setMessage]=useState("");const load=useCallback(async()=>{const r=await fetch("/api/receivables"),v=await r.json();if(r.ok)setData(v);else setMessage(v.error)},[]);useEffect(()=>{void load()},[load]);
  const send=async(event:FormEvent<HTMLFormElement>,action:string)=>{event.preventDefault();const form=event.currentTarget,payload={action,...Object.fromEntries(new FormData(form))};const r=await fetch("/api/receivables",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),v=await r.json();setMessage(r.ok?(v.idempotent?"该回款引用已处理，无需重复登记":"保存成功"):v.error);if(r.ok){form.reset();await load()}};
  const transition=async(id:number,action:string)=>{const r=await fetch("/api/receivables",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action})}),v=await r.json();setMessage(r.ok?"状态已更新":v.error);if(r.ok)await load()};
  return <main className={styles.page}><header><span>FINANCE · MYR</span><h1>开票、应收与回款</h1><p>订单金额、发票、分次回款、账龄和逾期信号形成内部财务闭环。</p></header>{message&&<div className={styles.message}>{message}</div>}<section className={styles.stats}>{["未到期","1-30天","31-60天","61-90天","90天以上"].map(k=><article key={k}><span>{k}</span><strong>{money(data.aging[k]??0)}</strong></article>)}</section>
  {data.canManage&&<section className={styles.forms}><form onSubmit={e=>void send(e,"create")}><h2>从订单生成发票</h2><select name="orderId" required defaultValue=""><option value="">选择尚未开票订单</option>{data.orders.map(o=><option key={o.id} value={o.id}>{o.orderNo} · {o.customer} · {money(o.amountCents)}</option>)}</select><input name="dueDate" type="date" required/><button>创建草稿</button></form><form onSubmit={e=>void send(e,"payment")}><h2>登记回款</h2><select name="invoiceId" required defaultValue=""><option value="">选择待收发票</option>{data.invoices.filter(i=>["issued","partially_paid","overdue"].includes(i.status)).map(i=><option key={i.id} value={i.id}>{i.invoiceNo} · 余额 {money(i.balanceCents)}</option>)}</select><div className={styles.row}><input name="amountCents" type="number" min="1" step="1" placeholder="金额 cents" required/><input name="paymentReference" placeholder="银行流水/回款引用" required/></div><div className={styles.row}><input name="paidAt" type="datetime-local" required/><select name="method" defaultValue="bank_transfer"><option value="bank_transfer">银行转账</option><option value="cash">现金</option><option value="other">其他</option></select></div><input name="note" placeholder="备注"/><button>确认登记</button></form></section>}
  <section className={styles.panel}><h2>应收台账 · {data.invoices.length}</h2><div className={styles.table}><div className={styles.head}><b>发票 / 客户</b><b>金额</b><b>回款 / 余额</b><b>到期 / 账龄</b><b>状态</b><b>操作</b></div>{data.invoices.map(i=><div className={styles.line} key={i.id}><span><strong>{i.invoiceNo}</strong><small>{i.orderNo} · {i.customerName}</small></span><span>{money(i.amountCents)}</span><span>{money(i.paidCents)}<small>{money(i.balanceCents)}</small></span><span>{i.dueDate}<small>{i.agingBucket}</small></span><span className={i.status==="overdue"?styles.overdue:styles.status}>{labels[i.status]??i.status}</span><span>{data.canManage&&i.status==="draft"&&<button onClick={()=>void transition(i.id,"issue")}>开具</button>}{data.canManage&&["draft","issued","overdue"].includes(i.status)&&i.paidCents===0&&<button className={styles.secondary} onClick={()=>void transition(i.id,"void")}>作废</button>}</span></div>)}</div></section></main>}
