"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./after-sales.module.css";
type CaseRow={id:number;caseNo:string;customerName:string;orderNo:string|null;itemName:string|null;status:string;priority:string;subject:string;slaDueAt:string;slaState:string;refundCents:number};
type Option={id:number;name?:string;orderNo?:string;sku?:string};
type Data={cases:CaseRow[];customers:Option[];orders:Option[];items:Option[]};
const labels:Record<string,string>={opened:"已受理",triaged:"已分诊",in_progress:"处理中",resolved:"已解决",closed:"已关闭",reopened:"重新打开"};
const money=(cents:number)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:"MYR"}).format(cents/100);
export default function AfterSalesClient({canEdit}:{canEdit:boolean}){
 const [data,setData]=useState<Data>({cases:[],customers:[],orders:[],items:[]}),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const response=await fetch("/api/after-sales"),value=await response.json();if(response.ok)setData(value);else setMessage(value.error)},[]);useEffect(()=>{void load()},[load]);
 const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget,body=Object.fromEntries(new FormData(form));const response=await fetch("/api/after-sales",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"case",...body})}),value=await response.json();setMessage(response.ok?"售后问题已建立":value.error);if(response.ok){form.reset();await load()}};
 const change=async(caseId:number,status:string)=>{const response=await fetch("/api/after-sales",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({caseId,status,refundCents:0})}),value=await response.json();setMessage(response.ok?"状态已更新":value.error);if(response.ok)await load()};
 const rework=async(row:CaseRow)=>{const reason=window.prompt("请输入返工原因",row.subject);if(!reason)return;const response=await fetch("/api/after-sales",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"rework",caseId:row.id,quantity:1,reason,idempotencyKey:crypto.randomUUID()})}),value=await response.json();setMessage(response.ok?`已建立返工任务 ${value.jobId}，等待预检与排产`:value.error);if(response.ok)await load()};
 return <main className={styles.page}><header><span>AFTER SALES</span><h1>售后与返工闭环</h1><p>从客户问题、责任分析到返工生产与退款，保留完整时间线和 SLA 风险。</p></header>{message?<div className={styles.message}>{message}</div>:null}
 {canEdit?<form className={styles.form} onSubmit={create}><h2>登记售后问题</h2><select name="customerId" required defaultValue=""><option value="" disabled>选择客户</option>{data.customers.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select name="orderId" defaultValue=""><option value="">关联订单（可选）</option>{data.orders.map(x=><option value={x.id} key={x.id}>{x.orderNo}</option>)}</select><select name="itemId" defaultValue=""><option value="">关联产品（返工必需）</option>{data.items.map(x=><option value={x.id} key={x.id}>{x.sku} · {x.name}</option>)}</select><select name="priority" defaultValue="normal"><option value="normal">普通</option><option value="high">高</option><option value="critical">紧急</option><option value="low">低</option></select><input name="subject" required placeholder="问题主题"/><input name="slaHours" type="number" min="1" max="8760" defaultValue="48"/><textarea name="description" placeholder="现象、影响范围和客户反馈"/><button>建立问题</button></form>:null}
 <section className={styles.panel}><h2>问题队列</h2><div className={styles.table}><div className={styles.head}><b>问题 / 客户</b><b>关联</b><b>SLA</b><b>状态</b><b>处置</b></div>{data.cases.map(row=><div className={styles.line} key={row.id}><span><strong>{row.caseNo} · {row.subject}</strong><small>{row.customerName} · {row.priority}</small></span><span>{row.orderNo||"无订单"}<small>{row.itemName||"未关联产品"}</small></span><span className={row.slaState==="breached"?styles.danger:""}>{row.slaState==="breached"?"已超时":row.slaState==="stopped"?"已停止":"进行中"}<small>{new Date(row.slaDueAt).toLocaleString("zh-CN")}</small></span><span>{labels[row.status]||row.status}<small>{row.refundCents?money(row.refundCents):"无退款"}</small></span><span className={styles.actions}>{canEdit&&["opened","reopened"].includes(row.status)?<button onClick={()=>void change(row.id,"triaged")}>分诊</button>:null}{canEdit&&["triaged","reopened"].includes(row.status)?<button onClick={()=>void change(row.id,"in_progress")}>处理</button>:null}{canEdit&&!(["resolved","closed"].includes(row.status))?<button onClick={()=>void rework(row)}>返工</button>:null}{canEdit&&row.status==="resolved"?<button onClick={()=>void change(row.id,"closed")}>关闭</button>:null}</span></div>)}</div></section></main>
}
